### ISSUE TITLE
Neoscrypt performance

### ISSUE THREAD

**Issue by jagauthier** [nicehash/excavator#100]
I would really like to use this software, but Neoscrypt performance is worse than with ccminer.

For instance, on my GTX 1050Ti,

ccminer:
[2017-12-22 07:26:10] accepted: 2/2 (diff 0.527), 370.61 kH/s yes!

Excavator:
[07:22:05][0x00000498][info] core | Algorithm 'neoscrypt' total speed: 303.431680 kH/s

I'm not sure if there is some config I can change to tweak this.

**Comment by dropky** [comment]
We're aware of the performance gap and we're working on optimizations. Currently there is nothing you could do to get higher hash speed, sorry.
