### ISSUE TITLE
Unspecified launch error

### ISSUE THREAD

**Issue by winnal** [nicehash/excavator#101]
After running for around a day my excavator will shut down saying unspecified launch error. Anyone know what it means?

**Comment by winnal** [comment]
How can I run a restart script with bat file without the web monitor?

**Comment by winnal** [comment]
I just do :start
(Run command)
go to start
Right?

I heard it might be more stable and not have this issue with Linux too so if the restart script doesn’t work out I’ll try Linux out.

**Comment by dropky** [comment]
Does the unspecified launch error always happen at the same algorithm (if so, which one)? 

To start excavator without web monitor via excavator+web+restart_script.bat file you need to comment out `start cmd /c "@echo off & echo Please, wait %WEB_LAUNCH_DELAY% seconds for Excavator status page to open..` line. 

This might be an overclocking issue, please consider that as well. There is no difference in stability between Linux and Windows version.
