### ISSUE TITLE
Excavator file disappears suddenly

### ISSUE THREAD

**Issue by techbit2** [nicehash/excavator#103]
Hello,

Can you help me, im trying to mine with multipoolhub and followed all given instructions. when i create a new excavator folder in Bin file and extract it there and then i start mining by clicking the start-miningpoolhub.

however i get the below errors continuesly and when i go to the Bin folder i cant find the excavator folder i created or even the excavator files,

WARNING: Cannot download C:\Users\MINING\Desktop\multipool\Bin\Excavator\excavator.exe distributed at https://github.com/nicehash/excavator/releases/.
WARNING: Searching for C:\Users\MINING\Desktop\multipool\Bin\Excavator\excavator.exe.
WARNING: Cannot find C:\Users\MINING\Desktop\multipool\Bin\Excavator\excavator.exe distributed at https://github.com/nicehash/excavator/releases/.

**Comment by aaronsace** [comment]
You need to put it here: C:\Users\MINING\Desktop\multipool\Bin\Excavator\excavator.exe

**Comment by techbit2** [comment]
Thanks but i already mentioned that i put it there and disappears

**Comment by aaronsace** [comment]
Check your antivirus. 

If you are still having problems then log your issue: 
https://github.com/MultiPoolMiner/MultiPoolMiner/issues

**Comment by dropky** [comment]
As @aaronsace said you should disable your antivirus.

**Comment by techbit2** [comment]
you mean disable windows defender?

**Comment by dropky** [comment]
Yes and also any other antivirus you're using (if any). I had the same problem with comodo antivirus software, it deleted excavator.
