### ISSUE TITLE
CUDA error 'out of memory' in func 'cuda_neoscrypt.   NVIDIA GTX1070   Solved!!

### ISSUE THREAD

**Issue by reproteq** [nicehash/excavator#104]
I had the same problem when I was mining neoscrypt
and solve it like that:

format and reinstall all drv nvidia and gigabyte oc soft. and nicehash last version.
oc gigabyte soft alls gpus -20% power
open nicehash soft and make normal benchmark
now all it is working perfect , i can miner neoscrypt without errors cuda

solved
CUDA error 'out of memory' in func 'cuda_neoscrypt::init' line 1258

do not try to cheat the benchmark by doing the test with a configuration and then change it to mine

**Comment by dropky** [comment]
Increasing virtual memory size should solve the issue as well.

**Comment by bviktor** [comment]
That's the current recommendation? Does 60% of all VRAM still stand?

**Comment by dropky** [comment]
You should have as much virtual+regular mem as combined memory of all GPUs. 

For example if you have a rig with 5 x 1080 ti,  5x11 = 55 GB. If you have 16 GB of regular mem, that means having 39 of virtual memory is enough. Put 1 more to make it 40 just in case and you will be safe.

**Comment by bviktor** [comment]
Oh so it's basically VRAM := physical RAM + virtual RAM? Makes sensse, thanks a lot.

**Comment by reproteq** [comment]
my virtual ram is 60g

**Comment by dropky** [comment]
Please take a look here - https://github.com/nicehash/excavator/issues/78#issuecomment-357694885

**Comment by rajawali8** [comment]
Thanks, My Rigs 6x1070 ares works , For Advice

**Comment by adrianobezerra1** [comment]
Hello @rajawali8 , which of the alternatives did you use? I have 2 1080ti and 2 1070ti. Only 1080 you fail in NeoScrypt;
