### ISSUE TITLE
NiceHash program uninstalled right after close

### ISSUE THREAD

**Issue by luigi198** [nicehash/excavator#105]
I was mining for the first time with your software and decided it was enough, time to play my online games. So I stopped and close the program, play and before bed I was gonna leave it mining.

The program shortcut said: "the location of the program changed, remove shortcut"
Suddenly I couldn't find the program anywhere and has to reinstall, it happens every time I close the program.
Windows 7

**Comment by dropky** [comment]
Disable your antivirus.
