### ISSUE TITLE
CUDA error DRIVER: '999' in func 'run_single_stream' line 960

### ISSUE THREAD

**Issue by buraksakalli** [nicehash/excavator#108]
I have 6 Gigabyte Aorus 6GB Gtx1060(rev 2.0), 4GB RAM and 30GB Virtual Mem.
Nvidia driver version: 390.65 and also Nicehash version 2.0.1.6
![screenshot_5](https://user-images.githubusercontent.com/10114716/34910493-bd75b608-f8c7-11e7-8c06-19a751e3cef4.png)

I can start mining normally but, after 15-20 share accepted, this error comes out. Then nicehash restarts automatically and now only sees 5 GPUs.

**Comment by dropky** [comment]
This issue might be related to the newest NVIDIA drivers. If you downgrade the driver do you still get the same problem?

**Comment by buraksakalli** [comment]
Unfortunatelly, I downgraded to 384 that is on Gigabyte's official driver. Still get the same problem.

**Comment by dropky** [comment]
Does this only happens when running equihash or with other algorithms as well? Would you post the log file with -f 0?

**Comment by buraksakalli** [comment]
Now I'm just using Equihash also I'm trying to other algorithms. 
[log.txt](https://github.com/nicehash/excavator/files/1629385/log.txt)
[log1.txt](https://github.com/nicehash/excavator/files/1629387/log1.txt)

**Comment by Blacksuu** [comment]
@dropky your suggestion about driver it make me to undestend what was major thing what was cause Excavator to crash or hang on in past weks & now i undestend that was appear after i update driver from 384.94 to 387.92, 388.71, & 390.65 make Excavator impossible to be use because it will freeze / hang after random time at list on equihash algo

GPU: Gigabyte Windforce 2 NVIDIA GeForce GTX 1060 3GB (Samsung)
OS: Windows 7 Service Pack 1
Video Driver:  390.65
MSI Afterburn: 4.4.2

Other side other miner apps are working fine & i can say after i install 390.65 i seen a improvement on hrate on other miner apps, soo hope you will find a fix for Excavator son & hope it will bring a better speed

p.s. i can't provide logs because in my case Excavator it will just freeze & i need to force close him coz it not respond at all ...

**Comment by Blacksuu** [comment]
@buraksakalli try neoscrypt algo it seams is stable, low speed vs what suppose to be but is working ...

**Comment by dropky** [comment]
@Blacksuu Thanks for the feedback! We'll perform more thorough testing on the recent drivers and hopefully find out what's causing the issues.  

Regarding the nhm_setup_2.0.1.7, the NHM team is aware of this issue. This is only affecting brand new installs, if you want to test the alpha version, you need to install and setup the official version first.

**Comment by Blacksuu** [comment]
hmmm you want to say 2.0.1.7 it work only like an update on top 2.0.1.6 or older version ? hmm then i will pass on testing coz i will wait for a better version (alpha, beta not mater) but clean install or clean version, mixing old with new usual it get messy, anyway i will stick around & wait for any future version :)

**Comment by dropky** [comment]
@buraksakalli You mentioned that after the restart only 5 GPUs are detected, is it working fine then (when mining on only 5 GPUs) or it's still crashing?

**Comment by buraksakalli** [comment]
It's working fine after down 6th GPU.

**Comment by dropky** [comment]
It might be a PSU problem, you should check if your power supply is powerful enough. Also, if the "fallen out card" is always the same one, you should recheck your risers/connectors/cables, if everything is connected ok.

**Comment by diony7** [comment]
buraksakalli 
I have a same problem.
Your hardware spec exactly same of mine.
Fixed this problem?
I'm eager to fix this problem.

**Comment by buraksakalli** [comment]
@diony7 I fixed too another way. I use MSI Afterburner and I changed power limit then everything is fine.

**Comment by dropky** [comment]
This seems like it's resolved 👍 Closing it..

**Comment by Wirklich1** [comment]
@buraksakalli In what other way did you fix this issue. I am also curious as to what you changed your power limit setting to

**Comment by buraksakalli** [comment]
@Wirklich1 hi, this is my all settings on AfterBurner.
<img width="1037" alt="settings" src="https://user-images.githubusercontent.com/10114716/35083575-e49d0b8e-fc30-11e7-8412-49df09071c5a.png">

**Comment by Wirklich1** [comment]
Thank you very much!
