### ISSUE TITLE
1.2.6a -or parameter not working

### ISSUE THREAD

**Issue by cTn-dev** [nicehash/excavator#11]
Hi, i was wondering if anyone reported the -or parameter not resetting the overclock after miner closes?
I closed the console via the X button, i also tried CTRL+C, it doesn't seem to work either way.

I would really like for the miner to reset the overclock + TDP/power limit when it closes.

Drivers: 382.53
OS: Win 10 x64
I am using single MSI 1080 X+

**Comment by nicehashdev** [comment]
This parameter is not valid since version 1.2.x. You should use on_quit event to reset clocks to whatever you want.

**Comment by cTn-dev** [comment]
I see, thank you for the info.

In this, case i think the primary readme https://github.com/nicehash/excavator/blob/master/README.md
should be updated as it still mentions the -or parameter.

Regarding the on_quit event, i think it should be covered in more detail as well, as the only "example" i could find is scattered on the bitcointalk.org forum.

**Comment by nicehashdev** [comment]
True, thanks for the notice, we will update it shortly.

We will also include more command file examples.
