### ISSUE TITLE
API bind to LAN IP causes miner to stall

### ISSUE THREAD

**Issue by kyleboddy** [nicehash/excavator#111]
When I attempt to bind excavator's JSON-TCP port to anything different than its default (4000 it seems) and/or the LAN IP (not 127.0.0.1 but rather 192.168.x.x), the excavator server starts, tries to run the API on that IP:Port, then just stalls out. 

_(The webserver works fine if I take out the -p and -i switches.)_

Is there another setting to change in the configuration files to point the miner at that IP rather than the localhost:4000? I see a default port at 5100 for the API in the file but don't see how changing that would help. Thanks.

**Comment by kyleboddy** [comment]
Example of where it gets stuck:

![image](https://user-images.githubusercontent.com/746351/34926382-e3121004-f963-11e7-980c-0ddbe73a01dc.png)

**Comment by kyleboddy** [comment]
Log file excerpt - looks like it keeps looking for localhost at port 4000:

{"name":"NHM","hostname":"Dionysus","pid":5028,"level":30,"msg":"[excavator_server.KeepAliveClient] ReInit connection in 3 seconds (called from CheckConnectedInterval)","time":"2018-01-15T03:48:23.108Z","v":0}
{"name":"NHM","hostname":"Dionysus","pid":5028,"level":30,"msg":"[excavator_server.KeepAliveClient] Connecting","time":"2018-01-15T03:48:26.110Z","v":0}
{"name":"NHM","hostname":"Dionysus","pid":5028,"level":30,"msg":"[excavator_server.KeepAliveClient] Connection ERROR Error: connect ECONNREFUSED 127.0.0.1:4000","time":"2018-01-15T03:48:27.111Z","v":0}
{"name":"NHM","hostname":"Dionysus","pid":5028,"level":30,"msg":"[excavator_server.KeepAliveClient] Connection closed (had_error: true)","time":"2018-01-15T03:48:27.111Z","v":0}
{"name":"NHM","hostname":"Dionysus","pid":5028,"level":30,"msg":"[excavator_server.KeepAliveClient] ReInit SKIPPED (called from close)","time":"2018-01-15T03:48:27.111Z","v":0}
{"name":"NHM","hostname":"Dionysus","pid":5028,"level":30,"msg":"[excavator_server.KeepAliveClient] NEW setTimeout() Timeout Called will end","time":"2018-01-15T03:48:32.851Z","v":0}
{"name":"NHM","hostname":"Dionysus","pid":5028,"level":30,"msg":"[excavator_server.KeepAliveClient] ReInit connection in 2 seconds (called from CheckConnectedInterval)","time":"2018-01-15T03:48:33.110Z","v":0}
{"name":"NHM","hostname":"Dionysus","pid":5028,"level":30,"msg":"[excavator_server.KeepAliveClient] NEW setTimeout() Timeout Called will end","time":"2018-01-15T03:48:34.121Z","v":0}
{"name":"NHM","hostname":"Dionysus","pid":5028,"level":30,"msg":"[excavator_server.KeepAliveClient] Connecting","time":"2018-01-15T03:48:35.112Z","v":0}
{"name":"NHM","hostname":"Dionysus","pid":5028,"level":30,"msg":"[excavator_server.KeepAliveClient] Connection ERROR Error: connect ECONNREFUSED 127.0.0.1:4000","time":"2018-01-15T03:48:36.114Z","v":0}
{"name":"NHM","hostname":"Dionysus","pid":5028,"level":30,"msg":"[excavator_server.KeepAliveClient] Connection closed (had_error: true)","time":"2018-01-15T03:48:36.114Z","v":0}
{"name":"NHM","hostname":"Dionysus","pid":5028,"level":30,"msg":"[excavator_server.KeepAliveClient] ReInit SKIPPED (called from close)","time":"2018-01-15T03:48:36.115Z","v":0}
{"name":"NHM","hostname":"Dionysus","pid":5028,"level":30,"msg":"[excavator_server.KeepAliveClient] NEW setTimeout() Timeout Called will end","time":"2018-01-15T03:48:37.847Z","v":0}
{"name":"NHM","hostname":"Dionysus","pid":5028,"level":30,"msg":"[excavator_server.KeepAliveClient] NEW setTimeout() Timeout Called will end","time":"2018-01-15T03:48:42.848Z","v":0}
{"name":"NHM","hostname":"Dionysus","pid":5028,"level":30,"msg":"[excavator_server.KeepAliveClient] ReInit connection in 3 seconds (called from CheckConnectedInterval)","time":"2018-01-15T03:48:43.111Z","v":0}
{"name":"NHM","hostname":"Dionysus","pid":5028,"level":30,"msg":"[excavator_server.KeepAliveClient] Connecting","time":"2018-01-15T03:48:46.112Z","v":0}
{"name":"NHM","hostname":"Dionysus","pid":5028,"level":30,"msg":"[excavator_server.KeepAliveClient] Connection ERROR Error: connect ECONNREFUSED 127.0.0.1:4000","time":"2018-01-15T03:48:47.114Z","v":0}
{"name":"NHM","hostname":"Dionysus","pid":5028,"level":30,"msg":"[excavator_server.KeepAliveClient] Connection closed (had_error: true)","time":"2018-01-15T03:48:47.114Z","v":0}
{"name":"NHM","hostname":"Dionysus","pid":5028,"level":30,"msg":"[excavator_server.KeepAliveClient] ReInit SKIPPED (called from close)","time":"2018-01-15T03:48:47.114Z","v":0}
{"name":"NHM","hostname":"Dionysus","pid":5028,"level":30,"msg":"[excavator_server.KeepAliveClient] NEW setTimeout() Timeout Called will end","time":"2018-01-15T03:48:47.863Z","v":0}
{"name":"NHM","hostname":"Dionysus","pid":5028,"level":30,"msg":"[API] Pinging server interval","time":"2018-01-15T03:48:48.716Z","v":0}
{"name":"NHM","hostname":"Dionysus","pid":5028,"level":30,"msg":"[API] Recived method: sma","time":"2018-01-15T03:48:51.350Z","v":0}
{"name":"NHM","hostname":"Dionysus","pid":5028,"level":30,"msg":"[API] Recived method: balance","time":"2018-01-15T03:48:51.356Z","v":0}
{"name":"NHM","hostname":"Dionysus","pid":5028,"level":30,"msg":"[excavator_server.KeepAliveClient] NEW setTimeout() Timeout Called will end","time":"2018-01-15T03:48:52.866Z","v":0}
{"name":"NHM","hostname":"Dionysus","pid":5028,"level":30,"msg":"[excavator_server.KeepAliveClient] ReInit connection in 3 seconds (called from CheckConnectedInterval)","time":"2018-01-15T03:48:53.112Z","v":0}

**Comment by dropky** [comment]
You're right, it looks like NHM is ignoring the provided -wi and -p parameters and waiting for Excavator to start with default settings. I'll report this issue to the NHM team. Thanks!

**Comment by kyleboddy** [comment]
Thanks - this would be really useful for me. I can't find a workaround right now to redirect localhost to the LAN IP using other methods, so a software patch would be huge.

**Comment by kyleboddy** [comment]
Any chance this was fixed in the new Nicehash Miner release?

**Comment by dropky** [comment]
Sorry, not yet. It should be included in the next NHM release.

**Comment by kyleboddy** [comment]
Was this fixed in 2.0.1.9?

**Comment by dropky** [comment]
Unfortunately, no :(

**Comment by kyleboddy** [comment]
Darn. Folding into the next release, hopefully?

**Comment by dropky** [comment]
Hopefully ;)

**Comment by kyleboddy** [comment]
1.4.2a is now in Nicehash with support. Did this version get the JSON-TCP patch? Thanks!

**Comment by kyleboddy** [comment]
Merged?

**Comment by kyleboddy** [comment]
Alas, this is still broken.

![image](https://user-images.githubusercontent.com/746351/36093582-f0108c2a-0f9f-11e8-876b-518f8ed1ce68.png)

**Comment by dropky** [comment]
Sorry about that. The bug was reported to the NHM team and that's practically all we can do (hopefully they'll fix it soon). 

I'm closing this issue since it's a NHM bug.
