### ISSUE TITLE
Version 1.3.9 alpha NVIDIA - Nist5 test result

### ISSUE THREAD

**Issue by EvgeniyKorepov** [nicehash/excavator#114]
GTX 1070 - 46.5 MH/s (180W)
The slightest acceleration leads to a lack of stability. Even +100 on the core.

The results are no worse than those of ccminer-Alexis.

**Comment by EvgeniyKorepov** [comment]
GTX 1080 Ti : 
ccminer_alexis_Nist5  - 78 MH/s
Excavator 1.3.9 - 84 MH/s

GTX 1080 : 
ccminer_alexis_Nist5  - 62.9 MH/s
Excavator 1.3.9 - 60.5 MH/s

**Comment by dropky** [comment]
Almost there :)
