### ISSUE TITLE
Version 1.3.9.a Feedback

### ISSUE THREAD

**Issue by Blacksuu** [nicehash/excavator#119]
Hello & here it is feedback with 1.3.9.a:

Hardware Spec & setting:

GPU 0: Gigabyte Windforce 2 NVIDIA GeForce GTX 1060 3GB (Samsung) dedicate to mining
GPU 1: Gigabyte NVIDIA GeForce GTX 650 2GB only for own use, not for mining
OS: Windows 7 Service Pack 1
Video Driver:  390.65
MSI Afterburn: 4.4.2
Power limit:   72 => ~86 W
Temp  limit:   80
Core  Clock:   +168
Memmory Clock: +700 (i can be push to 920 but is good only for ETH)

A. **Equihash** Setting 2 worker set in **Mode 0** because _Mode 1_ is waaaay slower aka bearly hit 255 sol/s, noo other extra parameter used

{"id":1,"method":"worker.add","params":["0","0","0"]},
{"id":1,"method":"worker.add","params":["0","0","0"]}

a. 1.3.8.a = 282 Sol/s & very rare it goo down to 278
b. 1.3.9.a = 282 Sol/s & very rare it goo down to 278

- equihash algo speed: 282 Sol/s = no improvement
- running 2 hour farming Zencash, no crash / stall = good potential fix with new driver, need more time for testing, to be sure coz it was random
- reject % reduce a lot! i seen my few on one round when in 1.3.8.a usual 10% was something normal = improvement
- try to look on BTG coin it seams is something diferite vs other coin from this algoritm, Excavator react strange sometime
Other miner speed:

- DSTM 0.5.8  = ~300 Sol/s - very rare reject - very stable i use full weak with out problem
- EWBF 0.3.4b = 277 - 285 Sol/s - very rare reject - stable no issue

B. **Neoscript** default setting nothing change & test run was done on Feathercoin because is old & standard one

1.3.8.a B=603 (default) = 572 Kh/s => stable noo crash or stall
1.3.9.a B=603 (default) = 605 Kh/s => stable noo crash or stall

Other miner speed:

- Hsrminer by palginpav & alexkap = 710 - 720 Kh/s
- Nsgminer 0.9.4                             = 670 - 720 Kh/s
- Ccminer KlausT 8.18 cuda 9.1        = 643 Kh/s

- speed small improvement & it can be done much more for sure

cheers

**Comment by Blacksuu** [comment]
update 1.3.9.a about mining BTG result in this:
- Excavator window it became lagy switching between application (alt tab) it take few sec to be bring in front if was behind a browser let say
- It generate huge amount of reject "low difficultie reason" , Zencash test run was perfect BTG nop is messy
example:

Est. Shares : 32,983,930 (done: 103.41%)
Your Valid   : 580.7254
Your Invalid : 239.3974 (29.19%) TO MUCH
Time Since Last Block:    40 minutes 21 seconds (round not done)

& this is happen only with excavator dstm working fine, i will check later Zcash coin to see

**Comment by Blacksuu** [comment]
C. **Nist5 algorithm** test run, same seting like already post on beginin

Excavator v.1.3.9.a      = 26 - 27 MH/s
Ccminer.Tpruvot.2.2.4 = 26 Mh/s
Ccminer.KlausT.8.18    = 26 Mh/s

**Comment by dropky** [comment]
@Blacksuu thanks for your feedback! We're aware of some performance gaps and we're constantly working on optimizations. We'll look into BTG problem.

**Comment by Blacksuu** [comment]
@dropky hello
BTG > equihash 2 time Crash / Stall today

A.
Start 2018-01-17 09:44:36
Stall 2018-01-17 10:01:48

- Normal run GPU clock: 1835-1860 - ~282 Sol/s
- Stall  run GPU clock jump to: 2126 - speed get go down to 0 Sol/s in time & if i not force close miner pc it will froze

B.
Start 2018-01-17 10:03:18
Stall 2018-01-17 19:51:08

- Normal run GPU clock: 1835-1860
- Stall  run GPU clock jump: 2126 - get go down to 0 Sol/s

From logs

**working**
[[2018-01-17 19:50:58.960573] [thread=0x000014fc] [info]]

	core | Algorithm 'equihash' total speed: 283.153333 H/s 
**stall**
[[2018-01-17 19:56:09.446332] [thread=0x000014fc] [info]]

	core | Device #0-0 speed: 0.000000 H/s

Question is any parameter what can be add in json what to tell excavator to restart in case let say Speed is below 250 h/s ? because if i force close excavator (pressing x or from task manager, ctrl + x not no effect) & just start agen miner all is fine till it will random decide to stall
This is happen only with Excavator, any other miner what i use i can let them run days & they are fine

**Comment by dropky** [comment]
Sorry, there is no such parameter available at the moment but you could always use excavator's api to do that: https://github.com/nicehash/excavator/tree/master/api

I would suggest you to monitor equihash speed with [algorithm.list](https://github.com/nicehash/excavator/tree/master/api#-algorithmlist) method and if the speed goes bellow 250 hashes try to [free](https://github.com/nicehash/excavator/tree/master/api#-workersfree) and [re-add](https://github.com/nicehash/excavator/tree/master/api#-workersadd) all the workers that are not performing well.

**Comment by Blacksuu** [comment]
hmm nice suggestion but i am in a little trouble aka i not know how exactly to do it special part with detection & make a IF / Then sequence:
so there are need to be done 2 step:
- Step 1: Detect Speed
{"id":1,"method":"algorithm.workers.speed","params":["0","0","250"]}
- Step 2: If speed is 250 then do this, i choose reset option coz i think is much simple vs free & re-add
{"id":1,"method":"worker.reset","params":["0","0","0"]}

and all it will look like sequence like this ?
{"time":20,"loop":20,"commands":[
{"id":1,"method":"algorithm.workers.speed","params":["0","0","250"]}
{"id":1,"method":"worker.reset","params":["0","0","0"]}
]}

so is correct what i try to do ? & if is not can you make correct sequence pls ? :)
cheers

**Comment by dropky** [comment]
@Blacksuu hmm, there are multiple mistakes here. I would suggest you to carefully read our [api documentation ](https://github.com/nicehash/excavator/tree/master/api). 

- algorithm.workers.speed method does not exist! 
- the purpose of the worker.reset method is to achieve more accurate speeds by resetting the time interval. Worker.reset does not free & re-add worker. 
- worker.reset method has only one command parameter (not 3)

You can't achieve what you want by using only config file. You'll have to write a simple script that will make HTTP calls to excavator API.

**Comment by Blacksuu** [comment]
well if i can't achieve what i want only with json config file then i will wait Excavator team to fix issue, get in a deeper coding is out of my league,  my coding time was end long time agow in school with turbo pascal back in 90''is. Excavator_v1.4.1a still doo same thing, i was not try release with 9.1 but my 1 bet cent it will do same. Question about Neoscript what parameter it can be use to make run on intensity 16 or 18 ? B=?!?! & what is default intensity with it start ?

**Comment by Blacksuu** [comment]
By ze way Excavator it should i think have internal implementation to restart or stop in case speed it hit 0 my be a thing like this it will be add in future aka condition like this:
- No internet / pool connection miner: A. Stop use Gpu B. Retry connect C. restart / stop after 30 try reconnect
- 0 Speed Hrate miner: A. Stop use GPU B. Restart miner

cheers

**Comment by Blacksuu** [comment]
yup my bet 1 cent was real today i say let try see 1.4.1.a with 9.1 on Equihash:
Start:  2018-01-26 08:33:37.667281
Crash: 2018-01-26 08:45:16.192709
soo noo mater how much i like & love Excavator i can't releay on him is doing his job ...

**Comment by Blacksuu** [comment]
Hello @dropky 
I just take Version 1.4.3 alpha NVIDIA to see if  "bug fixes & improvements" what fix issue with equihash algoritm & NOP same problem same thing ...
- Miner Start
[[2018-02-02 12:44:36.164770] [thread=0x000010d8] [info]] 
- Miner Stall > Crash (i check log & see moment when speed was drop)
[[2018-02-02 13:00:47.461761] [thread=0x00000a10] [info]]
- I stop manually miner seen him stall, coming back from what i was need to do in house
[[2018-02-02 13:10:51.452607] [thread=0x000010d8] [info]]
Shutting down

How i know miner crash / stall is simple:
1. MSI AF: GPU Clock it will jump to 2126 from 1820-1880 what is suppose to be acording my AF setting 
2. Miner it will lose speed from ~280 h/s goin to 0 > GPU clock 2126 = instant drop ~270 h/s
3. Usual IF excavator is not close manually (force close, CTRL + X it try to stop but it no effect only press X on console or task manager work) S.O. it will have 50-50% to freeze consume 100% GPU power

so excavator on  equihash is _Unstable, Unreliable, Unpredictable_  & i will say my pc / gpu hardware is fine i can run other miner program with out problem, with out care, look on what a hell they do ... i wish to can use excavator but in this condition is impossible

cheers & sorry for bring bad news

**Comment by Blacksuu** [comment]
because usual i like to find a fix to a problem, after reading more about https://github.com/nicehash/excavator/tree/master/api i was say hey let try to use "device.set.power_limit" setting my be i will make Excavator to be stable & work nice agen!!! so i set 86W limit (this is my target set already in Afterburner) to be sure it will never exceed that value & GPU Clock it will never goo more that 1860 Mhz. SURPRISE Excavator FAIL to obey / fallow his OWN fraking setting ending crashing GPU clock (2088 - 2216) => ending crashing himself !!! Way ?!?!? i will like to undestend but that's dev job to look in code & see way is out of control, way he can't fallow his own setting ... way can't be stable
Setting extra add in json:
`	{"time":5,"commands":[
		{"id":1,"method":"device.set.power_limit","params":["0","86"]}
	]},`
i make a image to show working stable miner & unstable one on crash moment see below
[img]https://i.imgur.com/Zo2E3d8.png[/img]

**Comment by EvgeniyKorepov** [comment]
@Blacksuu device.set.power_limit and TDP (which you set in the Afterburner) - different things.
use {"time":5,"commands":[ {"id":1,"method":"device.set.tdp","params":["0","86"]} ]},

**Comment by Blacksuu** [comment]
@EvgeniyKorepov  Afterburner it use % of power = TDP, what means if i want to use Excavator api with TDP it means to use same value like Afterburner = 72 so set 86W what it is real W value what end to be consume is bad for TDP because it will result in more power ;)
this is what you probabil it will suggest
{"time":5,"commands":[ {"id":1,"method":"device.set.tdp","params":["0","72"]} ]}

**Comment by EvgeniyKorepov** [comment]
@Blacksuu see https://github.com/nicehash/excavator/issues/126#issuecomment-358980160

**Comment by Blacksuu** [comment]
yup i seen & for that i made a picture with other miner working & 2 setting done in AFB
[img]https://i.imgur.com/ejH72Yp.png[/img]

**Comment by dropky** [comment]
@Blacksuu Currently we don't have a solution for your problem (since we can't reproduce it). If that only happens when mining bitcoin gold, the best solution would be to avoid mining it with excavator (at the moment). We're working on equihash improvements & bug fixes so hopefully when they're released it will solve this issue as well.
