### ISSUE TITLE
Question - usage and support

### ISSUE THREAD

**Issue by imrecsoka** [nicehash/excavator#12]
1)
Without extracting the file and being alerted by macafee and getting fired from my job, is there a readme file inside which explains usage of the command ?

2.1)
Does nihashminer support this also?
2.2)
Which version?

3)
Is this supported by AMD and which algorithm does it do , or which coin?

Thank you

**Comment by nicehashdev** [comment]
Basic description: https://github.com/nicehash/excavator/blob/master/README.md

API description: https://github.com/nicehash/excavator/tree/master/api

For NVIDIA cards: https://github.com/nicehash/excavator/blob/master/nvidia/README.md

For AMD cards: https://github.com/nicehash/excavator/tree/master/amd

NHMv2 uses latest version of Excavator.
