### ISSUE TITLE
NiceHash Miner v2.0.1.8 stuck at Starting Excavator Server

### ISSUE THREAD

**Issue by PredatorAaron** [nicehash/excavator#120]
I just update the NiceHash Miner an hour ago and after finish updating I wanted to open my app it just stucks at the "Starting Excavator Server" I've been waiting for an hour already, does anyone encounter this problem after updating to v2.0.1.8?

**Comment by PredatorAaron** [comment]
The Excavator is not running

**Comment by PredatorAaron** [comment]
I also tried reinstall again and it still show me the same thing

**Comment by PredatorAaron** [comment]
They said "The code execution cannot proceed because OpenCL.dll was not found. Reinstalling the program may fix this problem" and I have no idea what is OpenCL.dll

**Comment by dropky** [comment]
Excavator doesn't require OpenCL.dll to run. Do you have excavator.exe in `C:\Users\your_username_\AppData\Roaming\nhm2\bin\excavator_server` directory?

**Comment by PredatorAaron** [comment]
Yes I do but when I press it it just show this "The code execution cannot proceed because OpenCL.dll was not found. Reinstalling the program may fix this problem" and I have no idea what is OpenCL.dll" error code

**Comment by dropky** [comment]
OpenCL.dll is a library. I'm not sure why it's required though. 

So here is a fix:
Download old version of excavator from here: https://github.com/nicehash/excavator/releases/tag/v1.3.8a

You should download excavator_v1.3.8a_NVIDIA_Win64.zip file. 

Inside the zip there is OpenCL.dll, you should copy OpenCL.dll file to C:\Users\your_username\AppData\Roaming\nhm2\bin\excavator_server directory.

Let me know if this solves your problem.

**Comment by RodAus** [comment]
@dropky Thanks solved!

**Comment by analbumcoverconnery** [comment]
@dropky no luck on my end.

**Comment by analbumcoverconnery** [comment]
Updated error log.  It disappears very quickly.  See attached
<img width="763" alt="nicehash error" src="https://user-images.githubusercontent.com/35506223/35011660-97d23a14-facc-11e7-944e-17e06d7e0d53.png">

**Comment by dropky** [comment]
@analbumcoverconnery You should disable neoscrypt on your primary gpu. The thing is that neoscrypt requires a lot of memory (more than other algos) and on the primary gpu some of it might already be in use by your system or some third party application.

**Comment by analbumcoverconnery** [comment]
@dropky 

That takes care of it.  not sure what happened between 2.0.1.7 and this new update, but appreciate it nonetheless

**Comment by blackthoghts** [comment]
![image](https://user-images.githubusercontent.com/35507625/35013807-884f6806-fb34-11e7-86be-f9f1f36499ad.png)
getting this issue..please help

**Comment by Asiandadvictim** [comment]
Disabling NeoScrypt on all my GPUs worked. Thanks!

**Comment by cgrohowski** [comment]
NiceHash is downloading excavator.exe to the folder %APPDATA%\Roaming\nhm2\bin\excavator_server but then it gets auto-deleted.  I checked both Malwarebytes and windows defender, they are not catching any viruses.  I tried the fix above, no luck.  2.0.1.7 was working fine, any other clues as to how to fix this?

**Comment by dropky** [comment]
@cgrohowski Disable all your antiviruses (temporarily).

**Comment by blackthoghts** [comment]
Tried disabling it, but it still disappears. Antivirus is disabled plus no trace on it even if it still deletes it.
Xmrstackcpuminer doesn't unpack, it shows up n disappears.

**Comment by dropky** [comment]
If you download excavator from github - https://github.com/nicehash/excavator/releases/tag/v1.3.9a does it gets deleted as well?

**Comment by blackthoghts** [comment]
Where can i find this? I don't even have the bin folder in nhm2

**Comment by dropky** [comment]
You should have the bin folder in `%USERPROFILE%\AppData\Roaming\nhm2\bin\excavator_server\`. If you don't see it there, try to restart NHM, if that doesn't help, uninstall and install NHM again.

**Comment by blackthoghts** [comment]
Yup its not there and tried all of that a few times but it doesn't show up. Temp_bin appears and then disappears almost instantly.

**Comment by S74nk0** [comment]
@blackthoghts If you can please post the logs folder `%USERPROFILE%\AppData\Roaming\nhm2\logs`.

**Comment by cgrohowski** [comment]
Here's how I fixed it.  I found an older install (2.0.1.0) and installed that version.  It started OK.  Then I stopped it, and reinstalled 2.0.1.8, then it started working.  I honestly have no idea why this sequence of events worked, I had uninstalled 2.0.1.8 and reinstalled it a couple times with no luck.  My antivirus' were off for the previous attempts so I'm chalking it up to a ghost in the machine or something.

**Comment by PredatorAaron** [comment]
Thanks @dropky for the file for OpenCL.dll and it works after I paste the file into the folder

**Comment by blackthoghts** [comment]
@cgrohowski thank you so very much, that worked for me too. I got (2.0.1.5)  and started mining and then updated and boom it was working again.
Thanks a ton mate.

**Comment by blackthoghts** [comment]
@dropky thank you as well. You were great help too.

**Comment by dropky** [comment]
For anyone having problems with NeoScrypt you should restart NHM, which will automatically download the newest version of excavator that addresses these issues. With Excavator version 1.4.0 Neoscrypt should work on primary cards as well.

**Comment by imtheq12** [comment]
for my miners that have windows 10 I had to manually install the 3 vr redist programs that are in the nicehash install folder and then the excavator would start

**Comment by Ratuls1** [comment]
![image](https://user-images.githubusercontent.com/40795247/42218587-5927b68a-7ef3-11e8-8357-bdebf6be3385.png)
please help my gpu can't mining

**Comment by dropky** [comment]
@Ratuls1 Can you post here a screenshot of excavator window?

**Comment by Ratuls1** [comment]
![image](https://user-images.githubusercontent.com/40795247/42240358-37b4b500-7f31-11e8-8881-c5bc5ae9eda6.png)
@dropky my gpu stuck on log started, and cmd.exe found algorithm in gpu, were the gpu can't mining, how i fixed is with excavator_v1.3.9a but it my gpu doesn't mining, please check my screenshot
![image](https://user-images.githubusercontent.com/40795247/42241478-e9f21e08-7f34-11e8-8def-4660b9bfd251.png)

**Comment by dropky** [comment]
@Ratuls1 Excavator 1.3.9a is not compatible with current NiceHash Miner. It has an old API that is not supported anymore. You'll have to update excavator to 1.5.4a or more recent version.

**Comment by Ratuls1** [comment]
@dropky My gpu can't mining after update old version excavator_v1.4.1a_NVIDIA_Win64, but in folder my excavator server find many log,  how to fixed this problem, because my rig life in 3 day, i stuck this problem please help me :(
![image](https://user-images.githubusercontent.com/40795247/42297400-56983f7a-8029-11e8-8967-50dafac1e80e.png)

**Comment by Ratuls1** [comment]
i mining with gtx 1050
