### ISSUE TITLE
Reported Hashrate Accounting Seems Broken on daggerhashimoto_decred

### ISSUE THREAD

**Issue by gordan-bobic** [nicehash/excavator#122]
Testing on a 980Ti, with daggerhashimoto_decred, the reported hash rate for both algorithms keeps going up forever, way beyond what he card could plausibly be capable of.

Testing just daggerhashimoto, the card tops out at:
[info] core | Algorithm 'daggerhashimoto' total speed: 12.092129 MH/s

With daggerhashimoto_decred the hash rate tops out at
[info] core | Algorithm 'daggerhashimoto_decred' total speed: 24.001905 MH/s & 768.060948 MH/s

daggerhashimoto_sia is similar:
[info] core | Algorithm 'daggerhashimoto_sia' total speed: 24.081646 MH/s & 308.245186 MH/s
but after a while (5-10 minutes) this starts to deflate back to sane sounding hash rates. This doesn't seem to happen with daggerhashimoto_decred

What is more puzzling is that nicehash dashboard repots the big set of second figures as well.

It is worth mentioning that daggerhashimoto_pascal doesn't exhibit this behaviour, the hash rate is in the same ball park as pure daggerhashimoto.

So I am not sure what is broken, but I cannot see how daggerhashimoto_decred could be producing double the daggerhashimoto throughput on daggerhashimoto alone.

If the figures are correct, then surely daggerhashimoto algorithm can be improved by at least a factor of 2 on the 980Ti. I haven't been able to reproduce this anomaly on other GPU models.

**Comment by dropky** [comment]
What OS are you using? If you're using Windows make sure you have enabled Optimize for compute and DSR factors in the NVIDIA ctrl panel. What about your pool speed? Is it similar to the speed reported by excavator?  

Here are the results of our latest benchmark on 980 Ti (linux env, stock settings):

```
Summary: daggerhashimoto
GeForce GTX 980 Ti: speed = 22.115 MH/s, 0.0000 H/s, power usage = 200.29 W

Summary: daggerhashimoto_decred
GeForce GTX 980 Ti: speed = 11.361 MH/s, 363.54 MH/s, power usage = 180.86 W

Summary: daggerhashimoto_pascal
GeForce GTX 980 Ti: speed = 11.127 MH/s, 623.11 MH/s, power usage = 238.52 W

Summary: daggerhashimoto_sia
GeForce GTX 980 Ti: speed = 11.363 MH/s, 145.44 MH/s, power usage = 171.53 W
```
As you can see, standalone dagger should reach twice the speed reached in dual mining.

**Comment by dropky** [comment]
Also, keep in mind that dual mining is not tuned for 980 Ti cards. https://github.com/nicehash/excavator/tree/master/nvidia#daggerhashimoto_decred . You may reach higher speeds by experimenting with input parameters (R_0, R_1).

**Comment by gordan-bobic** [comment]
Interesting, I cannot reproduce your numbers, for me the anomalously high one is dh-decred. The others are all around 11 MH/s, which is what I would expect from a 980Ti, that's what it makes with ethminer.

**Comment by dropky** [comment]
Is your pool speed also as high (when mining dh-decred)? If it is, than it's nothing wrong with the reported speed.

**Comment by dropky** [comment]
I performed benchmark for dagger and dagger_decred on my rig yesterday and got very interesting results - dagger benchmarked higher with dual mining than standalone (for around 2%) but that only happened with specific OC settings (low memory clock, high power limit and core clock). 

If NH dashboard (pool speed) shows the correct results there is nothing wrong  with the reported speed. You should check the power consumption in both cases, it should be higher when running dagger_decred (in your case much higher).
