### ISSUE TITLE
NHM2.0.18 - Excavator cuda error out of memory // line 1147 - GTX1060

### ISSUE THREAD

**Issue by bigFin** [nicehash/excavator#124]
Nicehashminer gets stuck in a loop at the Neoscrypt benchmark.

![nicehash crash](https://user-images.githubusercontent.com/14171586/35098917-0879fca4-fc24-11e7-9106-66d965d7ee24.png)

**Comment by dropky** [comment]
Increase your virtual memory. If that doesn't help disable neoscrypt.

**Comment by bigFin** [comment]
By virtual memory do you mean the windows paging file? If so, I bumped it from 4gb to 8gb with no effect.

**Comment by dropky** [comment]
@bigFin We released a new version that's addressing the neoscrypt memory issues - https://github.com/nicehash/excavator/releases/tag/v1.4.0a . 

Download the newest excavator, close NHM and replace the excavator.exe file in `%USERPROFILE%\AppData\Roaming\nhm2\bin\excavator_server\` .
