### ISSUE TITLE
Disable Log Rotation 

### ISSUE THREAD

**Issue by ugurguncer** [nicehash/excavator#125]
How can  disable log rotation and automatic log moving if i start server with -fn c:\logs\excavator.log -f 0 -d 2  paramaters

**Comment by dropky** [comment]
Rotation should be disabled when running with -fn parameter. Which OS are you using?

**Comment by ugurguncer** [comment]
@dropky NO its not disabling, maybe little bug with -fn parameter with rotating.  
*im using windows10 
(nice hash bundle version) 
Excavator version: 1.3.9a_nvidia | Build time: 2018-01-15 12:05:04 | Build number: 4345 

here is my start command 
excavator.exe -c %COMMAND_FILE% -d %CONSOLE_LOG_LEVEL% -f %FILE_LOG_LEVEL% -i %API_HOST% -p %API_PORT% -wp %WEB_PORT% -wi %WEB_HOST% -wa %WEB_AUTH_TOKEN% -fn C:\Users\xx\Downloads\Miners\Logs\excavator.log

![screen shot 2018-01-19 at 13 39 27](https://user-images.githubusercontent.com/27911623/35147047-33cf6470-fd1e-11e7-967c-1578f4b723ff.png)

**Comment by dropky** [comment]
We'll look into it.

**Comment by agiz** [comment]
This will be fixed in the next release.
