### ISSUE TITLE
JSON commands for adjusting clock speeds and power limits

### ISSUE THREAD

**Issue by gordan-bobic** [nicehash/excavator#126]
From readme.md:
"The API works over standard TCP port and is JSON-message based with '\n' terminated messages. Do note that once you build up such application, you virtually have no limits anymore. You can truly optimize your mining to the max; you can launch various algorithms (at the same time), you can randomly assign workers (turn devices on off), do dual/triple mining, algorithm switching, adjusting TDPs, core or memory clock and fan speeds. Additionally to that, you can also read various GPU parameters and algorithm speeds reached by GPUs."

This implies that excavator internally has a wah to adjust the card's clock speeds and power limits without having to externally set them using nvidia-settings and nvidia-smi. If that is true, can you please provide at least some indication regarding what JSON needs to be issued to control it? The default json example file doesn't seem to provide any clues and there is no source code to read for the information.

**Comment by dropky** [comment]
Please take a look at [command_file_example_1.json](https://github.com/nicehash/excavator/blob/master/command_file_example_1.json). 

There is an example included for setting power limit, core and memory clock:
```
{"time":5,"commands":[
 {"id":1,"method":"device.set.power_limit","params":["0","150"]},
 {"id":1,"method":"device.set.core_delta","params":["0","240"]},
 {"id":1,"method":"device.set.memory_delta","params":["0","-300"]},
...
```

All methods are also included in the api documentation: [device.set.tdp](https://github.com/nicehash/excavator/tree/master/api#device-set-power-limit), [device.set.core_delta](https://github.com/nicehash/excavator/tree/master/api#-devicesettdp), [device.set.memory_delta](https://github.com/nicehash/excavator/tree/master/api#-devicesetcore_delta) etc.

**Comment by gordan-bobic** [comment]
I see here:
https://github.com/nicehash/excavator/tree/master/api
that there is both device.set.tdp and device.set.power_limit

Are those just aliases for the same thing, or are they different things? If different, what is the difference?

**Comment by dropky** [comment]
TDP and power limit are not the same thing. Power limit tries to control the maximum power while TDP or thermal design power controls the maximum amount of heat generated by the GPU (to prevent overheating).

You can read more about it here: https://en.wikipedia.org/wiki/Thermal_design_power

**Comment by EvgeniyKorepov** [comment]
@dropky, do you plan to add gpu_tdp_min and gpu_tdp_max to the results of the device.get method?

**Comment by gordan-bobic** [comment]
Right, but normally the only control availble externally is
nvidia-smi --power-limit
Which of tdp and power_limit does that correspond to?

**Comment by gordan-bobic** [comment]
Setting the power_limit using the API results in the power limit on the card being set to 0-3W less than the value that was passed. Nvidia-smi sets it exactly/correctly.

Setting clock speeds seemingly always returns an error "unable to set" even when running as root.

**Comment by dropky** [comment]
@gordan-bobic what OS are you using?

**Comment by gordan-bobic** [comment]
@dropky I'm on Linux.

**Comment by dropky** [comment]
@gordan-bobic You need to add Coolbits option to your xorg.conf file.

https://wiki.archlinux.org/index.php/NVIDIA/Tips_and_tricks#Enabling_overclocking

**Comment by gordan-bobic** [comment]
@dropky 
Already did that, otherwise nvidia-settings wouldn't work either.
But in the case I'm seeing here, using the API via excavator doesn't work, using nvidia-settings does, for any of the settings (fan speed, clock offsets).

**Comment by nicehashdev** [comment]
You need to launch excavator with admin privs to control clocks. Closing.
