### ISSUE TITLE
Excavator NeoScrypt overclocking the GPU

### ISSUE THREAD

**Issue by EvgeniyKorepov** [nicehash/excavator#128]
Excavator NeoScrypt overclocking the GPU - what are the best parameters to overclock at your own risk? 
CoreClock or MemoryClock? Or both?

**Comment by dropky** [comment]
Sorry, can't help you here. I'm sure if you experiment a little you'll find the "optimal" settings for your card :)

**Comment by EvgeniyKorepov** [comment]
The Google translator did not correctly express my question ;-)
I will rephrase - on what algorithm speed depends? Core or memory performance? I wanted to know the insider's opinion :-)
I learn the exact meaning myself - I created the ExcavatorLab application that allows me to test the parameters of the device and the workers in cycles. But your hint will greatly accelerate finding the optimal results.
Thank you in advance for your response!
