### ISSUE TITLE
Version 1.4.0 alpha NVIDIA - NeoScrypt test result

### ISSUE THREAD

**Issue by EvgeniyKorepov** [nicehash/excavator#129]
<img width="277" alt="excavator1 4 0" src="https://user-images.githubusercontent.com/35364901/35149279-8a98a2f0-fd26-11e7-9e99-6baa07fb66f4.PNG">

GTX 1070
{"id":1,"method":"device.set.tdp","params":["0","100"]},
{"id":1,"method":"device.set.core_delta","params":	["0","100"]},
{"id":1,"method":"device.set.memory_delta","params":["0","300"]},

GTX 1080
{"id":1,"method":"device.set.tdp","params":["0","100"]},
{"id":1,"method":"device.set.core_delta","params":["0","110"]},
{"id":1,"method":"device.set.memory_delta","params":["0","0"]}

GTX 1080 Ti :
{"id":1,"method":"device.set.tdp","params":["0","100"]},
{"id":1,"method":"device.set.core_delta","params":["0","130"]},
{"id":1,"method":"device.set.memory_delta","params":["0","0"]}

GTX 1080 - disappointing :-(
GTX 1080 Ti - one graphics card in the system! Awesome results!

Why is the increase in TDP greater than 100 leads to an error (CUDA error 'unspecified launch failure' in func 'cuda_neoscrypt::run' line 1264) on all cards.

**Comment by dropky** [comment]
@EvgeniyKorepov thanks for the feedback! Just a remark - the goal of this version of excavator was to fix the 'cuda out of memory' issues (not speed optimizations). 

My guess, ''unspecified launch failure' happens due to OC settings, not much we can do about it.
