### ISSUE TITLE
Running in administrator mode

### ISSUE THREAD

**Issue by ColossusFX** [nicehash/excavator#13]
`Build time: 2017-06-21 20:31:09
Build number: 412
Provided startup commandline:
        ..\excavator  -c ..\default_command_file.json

[14:29:39][0x000008d4][info] Log started
[14:29:42][0x000008d4][info] opencl | Loaded phymem for direct PCIe access.
Press any key to continue . . .`

Then program exits.

Running "excavator+web+restart_script.bat" in admin mode is just an endless loop of excavator has crashed

**Comment by nicehashdev** [comment]
Let us know your hardware, your OS, OS version and driver version.

**Comment by ColossusFX** [comment]
**OS**
Build 14393.rs1_release.160715-1616

**GPU Driver**
Crimson 17.6.2 
atikmdag-patcher-1.4.5.zip
Running in test mode

**GPU's**
6 x rx480 ASUS STRIX
1 x rx480 MSI

I have reset bios/clocks - No difference
Upgraded drivers from 16.9.11 (without patcher and testmode) -> 17.6.2  - No difference 

Running 190.9 MH/S without hardware acceleration on excavator (now back to modded bios)

**Comment by nicehashdev** [comment]
Os is Windows 7, 8 or 10?

**Comment by ColossusFX** [comment]
Windows 10 sorry forgot to add that

**Comment by ColossusFX** [comment]
Still the same issue in 1.29a version

**Comment by nicehashdev** [comment]
Try again with latests version and reopen the issue if it isn't fixed.
