### ISSUE TITLE
Fan speed not properly reported in Ubuntu

### ISSUE THREAD

**Issue by Anx2k** [nicehash/excavator#130]
With 1.3.9a (and previous versions) running the xenial linux build fan speed isn't properly reported - instead it just reports "-1 RPM".  nvidia-smi correctly reports the fan speed (as a percentage), so presumably it's available.

**Comment by dropky** [comment]
@Anx2k thanks for the report. This will be fixed in an upcoming release.

**Comment by Anx2k** [comment]
Great - to be clear, the percentage (gpu_fan_speed) is reported correctly in the JSON device.get request, just not gpu_fan_speed_rpm.  While I'd like to have both, it probably would also make more sense to use gpu_fan_speed and not RPM in the Web UI.

**Comment by dropky** [comment]
We'll take a look into all your suggestions for the Web UI (#131, #132 ). Thanks for the feedback!

**Comment by nicehashdev** [comment]
Ubuntu not supported. Closing.
