### ISSUE TITLE
Add SubVendor Name or ID to device.list

### ISSUE THREAD

**Issue by Anx2k** [nicehash/excavator#132]
It would be great to have the SubVendor name or ID in the device.list JSON query, so when showing the decorated names of each card, the specific manufacturer could be shown (such as MSI, Gigabyte, etc).  This would also be nice in the GUI when you have multiple rigs and want a quick way to see what (generally) is in them.

**Comment by agiz** [comment]
Hi @Anx2k and thanks for the suggestion. This will be added in an upcoming release.
