### ISSUE TITLE
lyra2rev2 crashing - can I adjust the intensity? 

### ISSUE THREAD

**Issue by phenomeus** [nicehash/excavator#134]
hi everybody,

i have 2x 1070ti, OC with +200/+700 @58TDP - rocksolid everywhere, but not in lyra2rev2 with excavator. its crashing always. so quickly that I cant get an screenshot. 

is there a parameter to adjust intensity? already tried "-i 15" but its not starting at all

thanks for any help

**Comment by EvgeniyKorepov** [comment]
https://github.com/nicehash/excavator/tree/master/nvidia#lyra2rev2

**Comment by dropky** [comment]
You can change the "intensity" with T parameter. Default number of threads for 1070 Ti is 2334720 (9120 * 256).

**Comment by phenomeus** [comment]
thank you. I will try 8000*256 . is it RAM CLOCK * INTERFACE?

**Comment by Braintelligence** [comment]
@dropky I have a lot of 1070 Tis in use and I can't get them to work with this parameter. What card did you test this "intensity" with?
