### ISSUE TITLE
When internet is unavailable miner continues operating

### ISSUE THREAD

**Issue by Anx2k** [nicehash/excavator#136]
I've run into this a couple times with the Linux version 1.3.9a, where our mine's internet connection drops for some reason, the miner continues to consume power at the same rate as if it was still connected.  Ideally if the miner looses connection to the pool, or doesn't receive a new getwork packet within some period of time, it should stop mining and idle until the connection is restored.

**Comment by dropky** [comment]
@Anx2k thanks for the bug report, this is a problem for sure.

**Comment by agiz** [comment]
Timeout is OS dependent. On windows it's 2 minutes, on linux it's 20 minutes.

**Comment by dredwilliams** [comment]
Is this something we can change via a parameter or API call?

**Comment by Anx2k** [comment]
That's the solution?  Every other miner app handles it correctly, but excavator can't stop mining when it's not connected?  How does this script determine that nicehash is back online?  It just launches and kills excavator over and over?  It certainly can't hit the stratum server and determine if there's something wrong beyond just a port responding.

Monitoring it with another script is truly a ghetto solution, really surprised because everything else seems to be engineered in a pretty solid way.
