### ISSUE TITLE
Wrong gpu_power_usage for a MSI  GTX 1050 Ti GAMING X 4Go

### ISSUE THREAD

**Issue by thierryleroy** [nicehash/excavator#137]
Good morning,

I don't know this is normal because of my card model : MSI  GTX 1050 Ti GAMING X 4Go. I can't get the gpu_power_usage, I get -2.

The result of device.get :

{"device_id":0,"name":"GeForce GTX 1050 Ti","gpgpu_type":1,"details":{"cuda_id":0,"sm_major":6,"sm_minor":1,"bus_id":6},"uuid":"GPU-100c07ff-d762-c8b7-c26a-04e0d2861172","gpu_temp":67,"gpu_load":100,"gpu_load_memctrl":63,"gpu_power_usage":-2.0,"gpu_power_limit_current":90.00000762939453,"gpu_power_limit_min":66.0,"gpu_power_limit_max":113.00000762939453,"gpu_tdp_current":100.0,"gpu_clock_core_max":1759,"gpu_clock_memory":3504,"gpu_fan_speed":38,"gpu_fan_speed_rpm":-1,"gpu_memory_free":851247104,"gpu_memory_used":3383754752,"id":0,"error":null}

Best regards.

**Comment by evanvz** [comment]
Hi @thierryleroy

Power readiing for the 1050Ti is not supported by nvidia-smi

Max power for 1050TI is 75W

Hope this helps.
E

**Comment by dropky** [comment]
It's like @evanvz said. 

If you run nvidia-smi (on windows it's located in `C:\Program Files\NVIDIA Corporation\NVSMI` directory) you'll see N/A under the power usage column.

**Comment by thierryleroy** [comment]
yes indeed, i get  'ERR! /  90W' with nvidia-smi. 
Thank you.
