### ISSUE TITLE
A few API questions

### ISSUE THREAD

**Issue by EvgeniyKorepov** [nicehash/excavator#139]
1. How fast can I send API commands? Do I need a timeout between the commands? If necessary, what is the recommended value?

2. Correctly I understand - receiving a response to the command ensures that the command has already been executed? Or are the commands put in the queue?

3. How much more profitable to use the TCP interface? Or is HTTP not too heavy for the system?

**Comment by agiz** [comment]
Hi @EvgeniyKorepov, may I ask what are you trying to achieve? I will try to answer to my best of knowledge.

1. This all depends on what kind of command you send. Lookup commands are fast but starting algorithm for example is a bit slower.

2. Depends on the command (Look at 1.).

3. The difference is negligible.

**Comment by EvgeniyKorepov** [comment]
Hence the sequence of deletion and addition of the Algorithm can be sent without pauses, just waiting for the response "{" id ": 1," error ": null}" after each command? 
Here's an example:
{"id":1,"method":"device.set.tdp","params":["0","100"]}
{"id":1,"method":"device.set.core_delta","params":["0","0"]}
{"id":1,"method":"device.set.memory_delta","params":["0","0"]}
{"id":1,"method":"algorithm.remove","params":["170"]}
{"id":1,"method":"algorithm.add","params":["neoscrypt","neoscrypt.eu.nicehash.com:3341","***.node10"]}
{"id":1,"method":"worker.add","params":["171","0"]}
{"id":1,"method":"device.set.tdp","params":["0","100"]}
{"id":1,"method":"device.set.core_delta","params":["0","130"]}
{"id":1,"method":"device.set.memory_delta","params":["0","0"]}
And in the end, of course with a pause in a couple of seconds :
{"id":1,"method":"worker.reset","params":["0"]}

The "worker.rest" command is optional? As I understand it, it serves for a more accurate display of speed in the beginning of the algorithm?

**Comment by dropky** [comment]
Yes, worker.reset command is optional, its purpose is (as you said) to reset the time interval to achieve more accurate speeds.

Regarding the timeline of the commands, you should wait for the response to be returned. 

FYI: I would like to mention here that we encountered some problems when algorithm was added and then immediately removed (within the same second). From time to time it came to the race condition between initialisation and deinitialisation - algorithm wasn't fully initialised yet but it has been already removed.

**Comment by EvgeniyKorepov** [comment]
Thank you all for the explanation!
Changed the code, removed all timeouts. The work of the application and the excavator remained very stable.
The results are impressive! Switching between algorithms is less than a second. Here is a screenshot from the Afterburner (1 second update rate)
<img width="176" alt="screenshot003" src="https://user-images.githubusercontent.com/35364901/35305972-adc6cbce-00ac-11e8-9fc8-881505c13403.PNG">

And in the application you need to think about adding milliseconds to logs ;-)
<img width="783" alt="screenshot004" src="https://user-images.githubusercontent.com/35364901/35306062-1774229c-00ad-11e8-8ec0-ac158d95a3d3.PNG">

@dropky , on your advice the name and icon of the application has changed. I attached a horn to the smiley - I think this is a sufficient change to not break the rules? ;-)

**Comment by dropky** [comment]
I'm not a legal expert, but I'm pretty sure you're not allowed to add horns to the NH logo :D 

Copy/paste from our [webpage](https://www.nicehash.com/media):
"This means that distorting, stretching, changing colors, changing fonts, adding or removing any part of the logo, cobranding with another company or addition of extra effects are forbidden."

**Comment by EvgeniyKorepov** [comment]
@dropky , I sent a request to Nicehash about the permission to use the logo. I will wait for the result...

**Comment by dropky** [comment]
@EvgeniyKorepov Ok, I hope it goes well :)
