### ISSUE TITLE
Random cuda error: "The launch timed out and was terminated"

### ISSUE THREAD

**Issue by oherman** [nicehash/excavator#141]
I'm getting a strange error with the new excavator which does so well with neoscrypt.

At first I thought this was overclock issues, but it happens completely at random, happens for the first 5 tries and completely stops at like, the 6th or 7th retry.

My cards are 1050ti and 750ti.

![screenshot 2018-01-24 03 43 24](https://user-images.githubusercontent.com/4970522/35298585-9790d140-00bd-11e8-9e74-e48861a7289d.png)

**Comment by dropky** [comment]
Can you (temporarily) disable 750ti in NiceHash Miner? Do you still get this error if you're mining only on 1050 ti?

There might be some issues with 750 ti default parameters.

**Comment by oherman** [comment]
I'll try that and will let you know. What I've tried is reseting all overclocks and using legacy miner. 

I found legacy miner has a similar thing going on, I might think it's the same error but terminates without saying so, but less verbose.

I'll try this with and without overclock.

**Comment by dropky** [comment]
Ok, let me know how it goes.

**Comment by oherman** [comment]
Ok here's how it went.

Without disabling 750 ti: Same crash but stabilizes at a certain interval.
Without disabling 750 ti but reseting overclock: longer stable duration, stilll crashes.
Disabling 750ti: More stabiliity, some crash but far fewer.
Disabling 750ti and reset overclock: Low hash rates but rarely  crashes.

Never had this problem when  the  750ti was in another unit separate.

**Comment by oherman** [comment]
Another update:

Forced reboot, used EVGA overclock utility (was using MSI afterburner), kept OC rates at 150 and 500 for core and memory respectively. I did this while nicehash miner was not running.

Now running perfectly even with 750ti for an hour and counting. Should I push my luck with putting the optimal OC rates but with the same precautions?

**Comment by dropky** [comment]
Yes, you should definitely do that, start with stock settings, and then try to OC them slowly until you found a stable settings. I'm closing this issue since it's an overclocking problem.
