### ISSUE TITLE
Long initialization of the Excavator

### ISSUE THREAD

**Issue by EvgeniyKorepov** [nicehash/excavator#143]
Very rarely there is a situation with a long initialization. Every few days. I suspect that it's not in the excavator, but in Windows. But I want to understand the reason.
Win 7 Pro x64, GTX 1080, nvidia driver 388.13

Pay attention to the time in the logs. Beetwen "Log started" and "Found CUDA device" 15 second. Usually this happens instantly.
`[[2018-01-24 11:03:47.288085] [thread=0x00000284] [info]]
	Log started
[[2018-01-24 11:04:03.196289] [thread=0x00000284] [info]]
	core | Found CUDA device: GeForce GTX 1080
[[2018-01-24 11:04:25.032226] [thread=0x00000284] [info]]
	api | Listening on 0.0.0.0:33333
[[2018-01-24 11:04:25.036132] [thread=0x00000284] [info]]
	http | Listening on 0.0.0.0:38080
[[2018-01-24 11:04:25.040039] [thread=0x00000284] [debug]]
	Adding command with 15 seconds execution delay and 15 seconds loop time: 
        {"id":1,"method":"algorithm.print.speeds","params":[]}
[[2018-01-24 11:04:25.040039] [thread=0x00000284] [debug]]
	Adding on quit command:
	{"id":1,"method":"device.set.tdp","params":["0","100"]}
[[2018-01-24 11:04:25.040039] [thread=0x00000284] [debug]]
	Adding on quit command:
	{"id":1,"method":"device.set.core_delta","params":["0","0"]}
[[2018-01-24 11:04:25.040039] [thread=0x00000284] [debug]]
	Adding on quit command:
	{"id":1,"method":"device.set.memory_delta","params":["0","0"]}
[[2018-01-24 11:04:25.040039] [thread=0x00000284] [info]]
	core | Initialized!
`

**Comment by dropky** [comment]
Between the "Log started" and "Found CUDA device" [NVAPI library](https://developer.nvidia.com/nvapi) has to be loaded. Now, as you already figured it out sometimes it takes a little more time than the usual. There could be multiple reasons for that - all Windows related (nvapi is already in the memory and loading isn't even required, longer scanning for the free space in the device address space, ... ).

You can get more info about how library loading works here:
http://blog.aaronballman.com/2011/08/what-happens-when-you-load-a-library/
