### ISSUE TITLE
Request: Add device ID information to log

### ISSUE THREAD

**Issue by UselessGuru** [nicehash/excavator#144]
Please add the complete list of detected mining devices to the log output.

This will make it easy to see how Excavator is identifying and enumerating devices.
Ideally the output will list each device with the same numbering scheme that is used for add.worker, e.g. 

{"id":1,"method":"worker.add","params":["0","**0**"]
{"id":1,"method":"worker.add","params":["0","**1**"]
{"id":1,"method":"worker.add","params":["0","**2**"]

**Log output:**
Found CUDA device: GeForce GTX 1080 Ti (DeviceID **0**)
Found CUDA device: GeForce GTX 1070 (DeviceID **1**)
Found CUDA device: GeForce GTX 1060 3GB (DeviceID **2**)

Q: What is the numbering scheme in mixed rigs (AMD and NVIDIA cards in the same box)?

**Comment by dropky** [comment]
Devices are identified by excavator in the same order as they are outputted to the log (starting with zero). Regarding the mix rigs, I honestly don't know, sorry. If you have access to one you can start excavator on the rig and test it.

**Comment by dropky** [comment]
I'm not sure if adding device id to log output is really necessary since as I mentioned the numbering is correlated to the output. Also, you can get the device id through  [device.list](https://github.com/nicehash/excavator/tree/master/api#-devicelist) method. I'll think about it.

**Comment by UselessGuru** [comment]
> Devices are identified by excavator in the same order as they are outputted to the log 

If I had a mixed rig, would AMD or NVIDIA devices be listed first? I'd like to understand the logic behind the numbering so that I can create JSON files based on OpenGL calls.

> If you have access to one you can start excavator on the rig and test it

I don't... i wish I did.

> Also, you can get the device id through device.list

I know, but that is not practical for my use case. I would like to build JSON files without executing Excavator first.

**Comment by dropky** [comment]
If you would have a mixed rig, first NVIDIA devices would be listed and then AMD. Anyway, since we removed the support for AMD you should only see NVIDIA gpus. 

You could start the excavator without any parameters just to see how devices are outputted to the log and then prepare the config file. If you're not gonna make any hardware changes the gpus should be always listed in the same order.  

I don't see how device id in the log would help your case. You would still have to run excavator first in order to get the info.

**Comment by UselessGuru** [comment]
> I don't see how device id in the log would help your case. You would still have to run excavator first in order to get the info.

It would make it easier for trouble shooting purposes. But I understand your point. Closed :-)
