### ISSUE TITLE
nicehash/escavator go up and down - often restarting 

### ISSUE THREAD

**Issue by Studmin** [nicehash/excavator#145]
I need help. I increesed my rig from 6 to 9 Nvidia gtx 1080 and now nicehash doesn't work well.
I have 8gb RAM on my motherboard and I fixed the virtual memory to 60000MB min/max.
Nicehash often restarting. What I have to do? I tried also with 16GB Ram but It is  the same.

**Comment by dropky** [comment]
Hi @Studmin, you should check if your power supply is strong enough, also configure your virtual memory (page file) to the at least amount of total GPU memory of all cards combined together, in your case 9 x 8gb = 72 gb.  

If you still encounter the problems refer to this thread here: #121

**Comment by Studmin** [comment]
Thank you so much the problem was the power supply. Too many Watts. Now It works correctly!
