### ISSUE TITLE
CUDA 9.1

### ISSUE THREAD

**Issue by MichaelMiner** [nicehash/excavator#147]
I have a 3 rigs.
1. 8 x EVga 1080Ti Black Edition
2. 7 x Gygabite 1070Ti
3. 2 Х Gygabite 1080Ti AORUS  + 6 Х Gygabite 1070Ti OC
With KUDA9,1 all algorithms in 3 rigs added from 8 to 10% MH/s
Excellent work
Comment
1. At 1 Rig (EVGA), the algorithm of the neoscript - "Out of memory"

**Comment by dropky** [comment]
Thanks for the feedback, if there won't be any big issues with the CUDA 9.1 we'll migrate to it for further releases. 

If you run the build compiled with CUDA 8 (excavator_v1.4.1a_NVIDIA_Win64.zip) on your first rig, do you also get the 'out of memory' error?

**Comment by MichaelMiner** [comment]
Excavator 1.4.1a Cuda 9.1

Virtual memory 48 GB
Rig 8 x Evga 1080 Ti

Please, allocmem less 48 Gb (32 typ), becouse allmost miners have SSD 64-120 Gb


>Четверг, 25 января 2018, 22:29 +03:00 от dropky <notifications@github.com>:
>
>Thanks for the feedback, if there won't be any big issues with the CUDA 9.1 we'll migrate to it for further releases.
>If you run the build compiled with CUDA 8 (excavator_v1.4.1a_NVIDIA_Win64.zip) on your first rig, do you also get the 'out of memory' error?
>—
>You are receiving this because you authored the thread.
>Reply to this email directly,  view it on GitHub , or  mute the thread .


-- 
Михаил Филимонов

**Comment by MichaelMiner** [comment]
Screen is bad,  but error line can be see 


>Четверг, 25 января 2018, 22:29 +03:00 от dropky <notifications@github.com>:
>
>Thanks for the feedback, if there won't be any big issues with the CUDA 9.1 we'll migrate to it for further releases.
>If you run the build compiled with CUDA 8 (excavator_v1.4.1a_NVIDIA_Win64.zip) on your first rig, do you also get the 'out of memory' error?
>—
>You are receiving this because you authored the thread.
>Reply to this email directly,  view it on GitHub , or  mute the thread .


-- 
Михаил Филимонов

**Comment by dropky** [comment]
You should set virtual memory to at least 88 GB. If you don't have enough SSD try set it to as much as you can and see if it still crashes (60GB of virtual memory should/could be enough). You could also try to decrease the number of blocks.

**Comment by dropky** [comment]
@MichaelMiner Thanks again for the feedback! I'm closing this. We released a new version today build with cuda 9.1.
