### ISSUE TITLE
How to use the algorithm parameters?

### ISSUE THREAD

**Issue by Kayfolom** [nicehash/excavator#15]
How to use the algorithm parameters?
Where should I enter them?

For example, I want to use [https://github.com/nicehash/excavator/tree/master/amd#equihash](url) , But the documentation does not say where to insert the parameters 
`1	0 or 1	Disable/enable binary kernels
2	0 or 1	Disable/enable the Global Data Share (requires admin privileges)`

It is logical that we need a method algorithm.add https://github.com/nicehash/excavator/tree/master/api#algorithm-add
`Example usage:
{"id":1,"method":"algorithm.add","params":
["equihash","equihash.eu.nicehash.com:3357","34HKWdzLxWBduUfJE9JxaFhoXnfC6gmePG.test2:x"]}`

????????????????????????????

**Comment by Kayfolom** [comment]
I found the answer! Your creator of documentation needs to be dismissed

In https://github.com/nicehash/excavator/tree/master/api#algorithm-add
> worker.add
>Creates a new worker by linking certain device with an algorithm.
>Command parameter #	Type	Description
>1	string	Algorithm ID.
>2	string	Device ID.
>3+	string	OPTIONAL Additional parameters. See details of supported algorithms for NVIDIA and AMD.

But on the page https://github.com/nicehash/excavator/tree/master/amd there is no mention of the method worker.add

**Comment by nicehashdev** [comment]
You found the answer. Closing.
