### ISSUE TITLE
Automatic resetting of app possible?

### ISSUE THREAD

**Issue by SS2006** [nicehash/excavator#151]
For whatever reason after a day or 2 of running my miner just hangs, it seems open but its not really mining, i found out by realizing i havent been paid out ether over a week. Is there a setting or line i can add to cause multipool miner to reset itself say every 24 hours?
Thanks!

**Comment by EvgeniyKorepov** [comment]
Add to config file:
```
{"time":86400,"commands":[
		{"id":1,"method":"quit","params":[]}
]},
```
86400 = 60 sec * 60 min * 24 hour = one day
But first test at a lower value (10-15 minutes for example)

**Comment by dropky** [comment]
You could do as @EvgeniyKorepov suggested and then rerun the excavator startup command using simple script.
