### ISSUE TITLE
Empty source files

### ISSUE THREAD

**Issue by monodrone** [nicehash/excavator#153]
Nothing in the git source to compile for Debian Jessie

**Comment by dropky** [comment]
This project is closed source. For every release, we upload linux packages as well  - https://github.com/nicehash/excavator/releases/tag/v1.4.1a. Officially we only support Ubuntu 16.04 LTS and Ubuntu 14.04 LTS, but you can try to extract the linux package and run the excavator binary. It should work on most linux distributions.
