### ISSUE TITLE
New Miner guy

### ISSUE THREAD

**Issue by Anonymousman138** [nicehash/excavator#154]
I'm a rookie digger. I want to ask My machine must What's up? Thank You

GTX1080Ti Asus Strix O11G
GTX1070 Asus Dual OC 8GB x3
Ram 4 GB DDR4
Intel G4400
PSU 750W X2

**Comment by dropky** [comment]
I don't understand what's the question here :) Are you asking if your hardware specifications are fine? If so, I suggest you to turn to reddit - https://www.reddit.com/r/NiceHash/, there is a really good community of experienced miners that can help you out.
