### ISSUE TITLE
GTX 1070 Version 1.4.2 strange behavior

### ISSUE THREAD

**Issue by EvgeniyKorepov** [nicehash/excavator#155]
GTX 1070 x 5
Version 1.4.2 
Win 10 x64
Driver 390.77
Strange behavior :
1. The algorithm neoscrypt worked 1:10:30
2. Algorithm change to lyra2rev2
Immediately after the addition of the workers, the Excavator began to seriously brake.
The interface of Windows was almost completely frozen.
The excavator stopped responding to API requests, but for some time it was still trying to mine.

neoscrypt Devices_TDP_CoreDelta_MemoryDelta : [95, 0, 0]
lyra2rev2 Devices_TDP_CoreDelta_MemoryDelta : [95, 120, -1000]

Excavator log:
[log_2018-01-30_23-18-44.322.log](https://github.com/nicehash/excavator/files/1679278/log_2018-01-30_23-18-44.322.log)

Full log of Excavator commands and responses:
[node07_192.168.0.156_rig.20180130-221345.log](https://github.com/nicehash/excavator/files/1679279/node07_192.168.0.156_rig.20180130-221345.log)

Time of problem start (by node07_192.168.0.156_rig.20180130-221345.log)
> 30.01.2018 23:24:16 Algorithm node07 Rig stop neoscrypt (worked 1:10:30)
> 30.01.2018 23:24:16 Algorithm node07 Rig start lyra2rev2

**Comment by EvgeniyKorepov** [comment]
The problem is perfectly reproduced. Again, the same switching algorithms led to a freeze :
> 30.01.2018 23:58:31 Algorithm node07 Rig stop neoscrypt (worked 0:07:45)
> 30.01.2018 23:58:31 Algorithm node07 Rig start lyra2rev2
<img width="1201" alt="werqwertqwer" src="https://user-images.githubusercontent.com/35364901/35591437-fccb15ea-061a-11e8-9bd4-df0f2120a7d7.PNG">

**Comment by EvgeniyKorepov** [comment]
Change algoritms:
> 00:27:50 Algorithm node07 Rig stop neoscrypt (worked 0:12:15)
> 00:27:50 Algorithm node07 Rig start equihash
All is well, no problems

**Comment by dropky** [comment]
Hmm.. I think I might know what's causing the problem. I'll take a look into it.

**Comment by dropky** [comment]
@EvgeniyKorepov Please check if the latest version (1.4.3a) solves this issue.

**Comment by EvgeniyKorepov** [comment]
@dropky I confirm - the problem is solved! Thank you for the wonderful work!
