### ISSUE TITLE
'CUDA error 'incompatible driver context' in func 'cuda_neoscrypt::init' for just my Founder's Edition 1070ti 1/5 cards

### ISSUE THREAD

**Issue by winnal** [nicehash/excavator#156]
On my rig with the latest excavator update using the latest NVIDIA driver, I have 5 1070ti cards 3 of them ROG STRIX 1 ZOTAC and 1 Founder's Edition. When I run excavator using Neoscrypt algo, I get this right at the beginning and I'm pretty sure it's just the Founder's Edition card...

[13:39:55][0x00001254][fatal] wrkr2-2 | CUDA error 'incompatible driver context' in func 'cuda_neoscrypt::init' line 1382

Anyone know what's going on?

EDIT: So I've been actually running excavator directly since I don't switch algos, and it doesn't seem to occur when I run excavator using Nicehash Miner 2 (latest ver). Any ideas?

**Comment by JackVaughn23** [comment]
Since you closed this out were you able to find a solution? I am having this same problem with just my third card and haven't been able to find any solutions online.
