### ISSUE TITLE
Miner excavator_server_91 is missing

### ISSUE THREAD

**Issue by CavedRuinKid** [nicehash/excavator#157]
I updated to Nicehash v 2.0.1.10

When I tried running it i got this error

![image](https://user-images.githubusercontent.com/26149860/35600119-78093e6c-05e9-11e8-84f2-9e6b6b6574ae.png)

coupled with this error
![image](https://user-images.githubusercontent.com/26149860/35600176-d8d6b094-05e9-11e8-8d4f-2dbd0ab86962.png)

Sure enough, I looked in the Roaming/nhm2/ folder and there was no bin folder. 
I manually created the bin folder, then the excavator_server folder and placed the contents of the "excavator_v1.4.2a_NVIDIA_Win64.zip" in there. 

But it still doesn't work.

This is what my excavator_server folder looks like:
![image](https://user-images.githubusercontent.com/26149860/35600298-79f032ac-05ea-11e8-8c40-21bfc7204a7a.png)

**Comment by CavedRuinKid** [comment]
Additionally, I keep getting an error that the SMA is down

**Comment by CavedRuinKid** [comment]
Also, in hindsight this probably shouldn't have gone in excavator

**Comment by dropky** [comment]
It looks like excavator didn't download automatically, restarting NHM usually helps. If not, you can copy excavator in the bin directory manually, but you should rename subfolder to `excavator_cuda9.1 ` not to `excavator_server ` (this is new in the v2.0.1.10).

![capture](https://user-images.githubusercontent.com/10920195/35611002-e0b4699e-0663-11e8-8e90-903af2337433.PNG)

excavator_server folder contains the old version of excavator (v1.4.1), it's purpose is backward compatibility for users that have older drivers, excavator_cuda9.1 directory contains the newest excavator (v1.4.2) - NHM will use it if your drivers are 387.xx or more recent.

**Comment by dropky** [comment]
In your case you should rename `excavator_server ` folder to `excavator_cuda9.1`.

**Comment by CavedRuinKid** [comment]
Thank you! I suspected it was something like that, I just needed the name of the folder!
I'm still having an issue with the SMA being down, but that seems to be unrelated.

**Comment by GibaWaldhelm** [comment]
In my case, After all this changes the message, after a long time of benchmark wait, now is :

"SMA is Down"
"You are unable to mine at this moiment vecause there are SMA service issues"
![err 4](https://user-images.githubusercontent.com/17165364/35769362-e81c9afa-08f0-11e8-85d0-fc5193c72e37.jpg)

**Comment by GibaWaldhelm** [comment]
Help me please :-(

**Comment by EvgeniyKorepov** [comment]
@CavedRuinKid  Try use https://github.com/EvgeniyKorepov/MinerPro-for-NiceHash - this application caches SMA data and in case of its fall (and this happens very often) allows you to continue working

**Comment by GibaWaldhelm** [comment]
Thank you very much @CavedRuinKid It works very well.
