### ISSUE TITLE
1.4.2a only using 2 out of 3 gpus

### ISSUE THREAD

**Issue by geckah** [nicehash/excavator#159]
Mining rig specs:
2x gtx 1070, 1x 1080, 4gb ram, 60gb virtual memory

Tried rebooting and disabling/enabling the gpus. Tried 1.4.1a as well. Algos used were nist5 and lyra2v2.
When running, excavator picks up all 3 gpus, but msi afterburner shows the 1080 idling.

Went back to ccminer and all three gpus were running

**Comment by dropky** [comment]
How many GPUs do you see in excavator?

**Comment by geckah** [comment]
i see all 3 gpus in excavator. Ran the test for 3 minutes and the gtx 1080 was still idling

**Comment by dropky** [comment]
What do you mean by "run the test"? What test?

**Comment by dropky** [comment]
Try running excavator with the next config file (excavator.exe -c config.json):
```
[
	{"time":0,"commands":[
		{"id":1,"method":"algorithm.add","params":["equihash","equihash.usa.nicehash.com:3357","34HKWdzLxWBduUfJE9JxaFhoXnfC6gmePG.testrig"]}
	]},
	{"time":3,"commands":[
		{"id":1,"method":"worker.add","params":["0","0"]},
		{"id":1,"method":"worker.add","params":["0","1"]},
		{"id":1,"method":"worker.add","params":["0","2"]}
	]},
	{"time":10,"loop":10,"commands":[
		{"id":1,"method":"algorithm.print.speeds","params":[]}
	]}
]
```

**Comment by geckah** [comment]
I'm using multipoolminer. This is what was generated int the json file
{
    "time": 1,
    "commands": [
      {
        "id": 1,
        "method": "worker.add",
        "params": [
          "0",
          "1"
        ]
      },
      {
        "id": 1,
        "method": "worker.add",
        "params": [
          "0",
          "2"
        ]
      },
      {
        "id": 1,
        "method": "worker.add",
        "params": [
          "0",
          "3"
        ]
      }
    ]
  },
  {
    "time": 10,
    "loop": 10,
    "commands": [
      {
        "id": 1,
        "method": "algorithm.print.speeds",
        "params": [
          "0"
        ]
      }
    ]
  }

i assume it is similar?

**Comment by geckah** [comment]
> What do you mean by "run the test"? What test?

i meant to say benchmark

**Comment by dropky** [comment]
Ok, I see what's the problem. Wrong device ids in worker.add methods. 

This
```
"method": "worker.add","params": ["0","1"]
"method": "worker.add","params": ["0","2"]
"method": "worker.add","params": ["0","3"]
```
Should be:
```
"method": "worker.add","params": ["0","0"]
"method": "worker.add","params": ["0","1"]
"method": "worker.add","params": ["0","2"]
```

Device ID of your first GPU is 0 not 1 and so on.. 

You're adding worker to a device with id 3 but that device doesn't exist, in the mean time your first GPU doesn't get a worker, that's the reason it's idle.

**Comment by geckah** [comment]
thanks!
