### ISSUE TITLE
external algorithm.add (through HTTP) always fails

### ISSUE THREAD

**Issue by cTn-dev** [nicehash/excavator#16]
Hi (cTnko from forums) here, i am working on an GUI for the excavator and i ran into an odd problem.
For some reason the address sent through JSON gets received as lowercase (which obviously isn't valid).

You can use this example (from the API) to test it out, in chrome.
`http://127.0.0.1:38080/api?command={"id":1,"method":"algorithm.add","params":["equihash","equihash.eu.nicehash.com:3357","34HKWdzLxWBduUfJE9JxaFhoXnfC6gmePG.test2:x"]}`

This is on the latest version 1.2.8 alpha.

Can you confirm?

**Comment by nicehashdev** [comment]
You are correct. We will fix that in following version.

**Comment by cTn-dev** [comment]
Thanks for letting me know, ill keep an eye on a new version.
I am working on a GUI that doesn't use a command.json, that's how i found this bug, without the algorithm.add i can't progress much further at the moment.

Is there any ETA?

**Comment by nicehashdev** [comment]
Yes, most likely tomorrow, because there is another critical bug with phymem.sys that has to be fixed as well.

Currently, using socket API, this method works correctly. We recommend doing socket API anyway - less overhead.

**Comment by cTn-dev** [comment]
Awesome!
I will check out the socket API while i wait for the new version, thanks for the tip!

**Comment by Kayfolom** [comment]
I do not want to upset the developers, but the socket API does not work properly. The answer comes in 85% of cases, 15% the command in a socket leaves in anywhere

**Comment by nicehashdev** [comment]
What exactly doesn't work properly? Give some proofs with log files...

**Comment by cTn-dev** [comment]
Hi, any update on the new version?
To be honest i would even be happy with just a dev build (as long it has the API fix), but i don't know if you guys do that ?

**Comment by nicehashdev** [comment]
This fix has been applied, but we have other fixes working on currently.

**Comment by cTn-dev** [comment]
Thank you for the update, i can confirm this is fixed in 1.2.9a.
