### ISSUE TITLE
1070 Ti is not optimized for NeoScrypt

### ISSUE THREAD

**Issue by borzaka** [nicehash/excavator#166]
In the [readme](https://github.com/nicehash/excavator/tree/master/nvidia#-neoscrypt):

> WARNING: NeoScrypt is tuned for next cards: 1080 Ti, 1080, 1070, 1060 6GB, 1060 3GB, 1050 Ti, 1050, 1030, P104-100, P106-100 and TITAN V. You may reach higher speeds by experimenting with parameters when using a different card.

Probably related issue: #164

**Comment by dropky** [comment]
This is a mistake in readme documentation. Neoscrypt is optimised for the 1070 Ti cards. I'll update the readme asap. Anyway, this shouldn't be an issue. When the algorithm isn't optimised for the card it means that we didn't perform tuning on default parameters. For 1070 Ti cards default startup parameters would be the same as for 1070.

**Comment by dropky** [comment]
I updated the readme file.
