### ISSUE TITLE
Missing excavator server 91

### ISSUE THREAD

**Issue by AppaXD** [nicehash/excavator#167]
![image](https://user-images.githubusercontent.com/24938580/35754911-33d2c24e-0833-11e8-9270-65107bbfb605.png)
I have Windows Defender and my antiviruses disabled, I have uninstalled and reinstalled multiple times. It seems that I'm missing "excavator.exe" from the bin folder, but when I try to copy the file over to them, Windows tells me:
![image](https://user-images.githubusercontent.com/24938580/35754957-62cc7a36-0833-11e8-8515-f2811295df10.png)
I tried giving myself full control, and everything I could find online.

**Comment by dropky** [comment]
Close NiceHash Miner and try to copy it then.

**Comment by AppaXD** [comment]
It was closed when I tried.

**Comment by evanvz** [comment]
Exclude that folder in Windows AV & copy the files again. Hope it helps.

**Comment by AppaXD** [comment]
I have it disabled.

**Comment by AppaXD** [comment]
It isn't an antivirus doing it.

**Comment by dropky** [comment]
If you copy only the excavator.exe file (not the whole folder) to `excavator_cuda9.1/excavator.exe`, does it work or do you still have issues with denied access? You could also try to remove `excavator_cuda9.1` folder, create new folder and rename it to` excavator_cuda9.1` (please refer to https://github.com/nicehash/excavator/issues/157 in order to correctly copy/rename the content of the bin directory).

**Comment by CavedRuinKid** [comment]
I suspect you're having the same issue referenced here:
[https://github.com/nicehash/NiceHashMiner/issues/1460#issuecomment-362391082](url)

Like me, even if you get excavator installed in the right location, you'll get the the SMA is down warning. 

Try using a VPN to get up and running again.

**Comment by faton721** [comment]
what is the problem how can resolve it????

**Comment by drewbitt** [comment]
I also get this error and creating a /bin/excavator_cuda9.1 folder in my AppData/Roaming/nhm2/ folder and placing the excavator contents does not work. No antivirus is effecting this and is likely more of a bug with NiceHash not installing correctly.

**Comment by AppaXD** [comment]
I went into safe mode and copied the excavator_cuda9.1 folder to the directory, and it worked.

**Comment by Emon172** [comment]
Guys please help me. See my problem here's the link
https://github.com/nicehash/excavator/issues/193
