### ISSUE TITLE
XmrStackCPUMiner is missing

### ISSUE THREAD

**Issue by GibaWaldhelm** [nicehash/excavator#168]
I have the message :
The following miners seem to be missing
XmrStackCPUMiner
But my antivirus is disabled.
I tried to unnistall and install againg and the folder BIN is not created on instation, so I download the folder bin, and now the message is the above.
Somebody can help me ?

**Comment by dropky** [comment]
Please take a look here - https://github.com/nicehash/excavator/issues/157#issuecomment-361853442. Check there the correct content of the bin directory (be careful with the folder naming, it has to be exactly the same as in the screenshot or NHM won't recognise it). You should copy the XmrStackCPUMiner to `bin/xmr-stack-cpu` folder. 

Btw, this has nothing to do with excavator :)
