### ISSUE TITLE
Proposal for a Supplement to API

### ISSUE THREAD

**Issue by EvgeniyKorepov** [nicehash/excavator#169]
In my practice, the device.list is always called first, then the device.get calls are listed.
I have never had to use these methods separately.
Can I add the result of the device.get directly into device.list?
This would reduce the overhead for API calls, especially for farms with a large number of GPUs

For example:
```
{
	"devices": [{
		"device_id": 0,
		"name": "GeForce GTX 1080",
		"gpgpu_type": 1,
		"details": {
			"cuda_id": 0,
			"sm_major": 6,
			"sm_minor": 1,
			"bus_id": 4
		},
		"uuid": "GPU-39d6e841-c9d6-3807-ecf4-fa8cc8814be9",
		"gpu_temp": 73,
		"gpu_load": 99,
		"gpu_load_memctrl": 75,
		"gpu_power_usage": 201.50900268554688,
		"gpu_power_limit_current": 200.0,
		"gpu_power_limit_min": 100.0,
		"gpu_power_limit_max": 216.0,
		"gpu_tdp_current": 100.0,
		"gpu_clock_core_max": 2100,
		"gpu_clock_memory": 4513,
		"gpu_fan_speed": 64,
		"gpu_fan_speed_rpm": 2425,
		"gpu_memory_free": 3540930560,
		"gpu_memory_used": 5049004032
	}],
	"id": 1,
	"error": null
}
```

**Comment by dropky** [comment]
@EvgeniyKorepov thanks for the suggestion, we will take it into consideration.

**Comment by EvgeniyKorepov** [comment]
:-(

**Comment by dropky** [comment]
Well... the thing is that device.list data is static, it doesn't change, so basically you only have to call it once at the startup and then remember the state. On the other hand device.get data changes all the time...

**Comment by EvgeniyKorepov** [comment]
may be add deviceS.get ? as workers command group

**Comment by dropky** [comment]
Yes, it will be included in the next release.

**Comment by dropky** [comment]
See API changes in version 1.5.1a. We added devices.get method.
