### ISSUE TITLE
Setting TDP doesn't work on 1080Ti + Only 80% power utilization on default?

### ISSUE THREAD

**Issue by Twente-Farm** [nicehash/excavator#17]
Hello,
 
First of, good work on this new miner. Keep up the progress.
I'm having an issue with my 1080TI rigg.
On default it uses only 80% of the power limit set.
When i try to change this trough the config it won't do anything with that setting.

i'll include my config, if i missed something please let me know.
If this is indeed a bug, is there an ETA on a fix? 

`	{"id":1,"method":"device.set.power_limit","params":["0","275"]},
	{"id":1,"method":"device.set.power_limit","params":["1","275"]},
	{"id":1,"method":"device.set.power_limit","params":["2","275"]},
	{"id":1,"method":"device.set.power_limit","params":["3","275"]}
`
it also gives me an error from time to time

`
Net error: JSON member "result" not expected type: Array
`

After this error all cards seem to start using only 1 thread.

Regards,
Twente-Farm

**Comment by nicehashdev** [comment]
Hello!

Power limit depends on cards you have. Some have TDP set very high and cannot utilize 100% TDP, then you can see 80% only. So this is normal.

Regarding your net error; that is issue with some pools. You are probably not using NiceHash? Majority of other pools don't really follow stratum specs and Excavator only works according to official stratum specifications. You may change your pool or contact pool operator and inform about the bug in their communication protocol.

**Comment by Twente-Farm** [comment]
Hello nicehashdev.

Thank you for your reply, no thanks for closing it.
The powerlimit for my card is much higher then your miner is using. this IS an issue with your miner.
In afterburner i only see an 80% usage of the powerlimit set in afterburner. 

In regards to the net error, i am using nicehash pool.

` {"id":1,"method":"algorithm.add","params":["equihash","equihash.eu.nicehash.com:3357","MYADRESS"]} `

Thank you

**Comment by nicehashdev** [comment]
Please, run the miner with -f 0 and once you see the net error, zip your log files and attach them here.

As I said regarding power limit, your card may not be able to reach the full power limit (100%). You can get some more power draw, if you overclock the card.

**Comment by Twente-Farm** [comment]
will add that command.

I find that very strange, other miners do push it to the powerlimit, im hitting 600sol/s this way, but at full 100% TDP usage I should hit 720ish per card. just like EWBF miner does. When i set it manually it will completely ignore the setting.

**Comment by Twente-Farm** [comment]
I didn't get the net error again.

**Comment by 008** [comment]
nope, you didnt shoud hit 720 with nicehash miner, only with EWBF
