### ISSUE TITLE
Excavator is very slowly reaching the maximum hashrate

### ISSUE THREAD

**Issue by borzaka** [nicehash/excavator#170]
- It needs approx. 10 minutes to stabilize the hashrate. It starts allways from a higher number and than slowly decreases.
- 1 minute is not enough to reach some algorithms maximum hashrate during benchmarks (NHM 2).
- It reacts very slowly to realtime overclocks as well. Again I have to wait about 10 minutes to see my overclock results.

**Comment by EvgeniyKorepov** [comment]
Use https://github.com/nicehash/excavator/tree/master/api#worker-reset  10 seconds after workers.add (or change device params).

**Comment by borzaka** [comment]
Like this? I'am adding workers at `"time": 3`
```
{
	"time": 13,
	"commands": [
		{"id":1,"method":"worker.reset","params":["0"]},
		{"id":1,"method":"worker.reset","params":["1"]},
		{"id":1,"method":"worker.reset","params":["2"]},
		{"id":1,"method":"worker.reset","params":["3"]},
		{"id":1,"method":"worker.reset","params":["4"]},
		{"id":1,"method":"worker.reset","params":["5"]}
	]
}
```

What does it do exactly? How does it help?

**Comment by EvgeniyKorepov** [comment]
Helps, you can experiment in my MinerPro https://github.com/EvgeniyKorepov/MinerPro-for-NiceHash

When you start workers, the speed is initially zero, then in a short period of time it increases to the maximum. But the initial zero spoils the picture in the arithmetic mean speed. Zero is leveled with time. Here, of course, the question is to the developers and metatology of speed calculation.
worker.reset starts counting the average speed again, which allows almost instantly see the real speed

**Comment by dropky** [comment]
As @EvgeniyKorepov said, the purpose of worker.reset method is to reset the time interval to achieve more accurate speeds.
