### ISSUE TITLE
Tracking workers' work to avoid inefficient interruptions

### ISSUE THREAD

**Issue by GrossoMoreira** [nicehash/excavator#175]
Hi,

I'm implementing my own algo switcher. I notice that when my program tells excavator to switch algorithms, my miner's profitability graph on NiceHash website drops to 0 for one data point  (~5 minutes), and then comes back up (mining another algo). This should not happen because my GPU was mining almost the whole time, as it only needs 1 second to switch from one algo to another.

I suspect this happens because when my program stops an algorithm, excavator immediately interrupts the current work, wasting some mining time. I'd like to avoid this waste of mining work but currently there is no way to know when to stop an algo without wasting any 'shares' that are currently being processed. The API's algorithms.list provides:

- algorithms[i]/details/total_shares
- algorithms[i]/details/total_accepted
- algorithms[i]/details/total_rejected
- algorithms[i]/details/last_efficiency

But that only gives me how many shares have been processed, not how many are **currently** being processed . I need to have a way to graciously stop an algorithm without wasting any work, even if I have to wait a few seconds for it to finish what it's doing, or if it mines slower while it's waiting to stop.

Is there a way to achieve this already? If not, I leave it as a suggestion.

**Comment by EvgeniyKorepov** [comment]
In my MinerPro (https://github.com/EvgeniyKorepov/MinerPro-for-NiceHash), I use a little trick - if I need to switch, and the running algorithm does not have any accepted share, then I expect at least one of the share to be accepted before switching.
It's hard to judge whether this strategy is profitable or not, but at least there is a moral satisfaction that the algorithm worked for several minutes not in an empty ;-)
You can use this method.

**Comment by dropky** [comment]
@GrossoMoreira Your profitability graph shouldn't drop to zero (it's completely understandable that the pool speeds drops for a bit but definitely not to zero). Anyway.. wasted mining work when switching from one algorithm to another is negligible. 

FYI. We're planning to add a switching method (`worker.switch("to_algo", worker_id) `) to the api in the future.

**Comment by GrossoMoreira** [comment]
Well, the graph definitely drops to zero. You can see it yourself on this test account (it's an i7 7700K and a GTX1070):
https://www.nicehash.com/miner/38wBvGAvj7bAyQPQ8Et9QqN6kQCd9L9Q87

There are periods where I turned it off for an hour or two (we can ignore those) but there are also some data points where the profitability is 0.0000. This machine was not doing any other task while mining.

In fact, the profitability dropped to zero both with my algo switcher or the NiceHash client itself, so it's not even a bug in my program.

You claim that the wasted mining time is negligible when switching algos, but is it really? Over the course of 24h my program switched algos more than 90 times. If we multiply this by the number of GPUs I'll be running it might be a very significant amount, don't you think? Unfortunately I don't have enough data to make a proper calculation of how much is wasted. Certainly you have more information, and I'd really appreciate if you could share it with me. Until then I remain with the idea that my hashing power is being wasted for no reason, and that there's nothing I can do about it, which is unsettling. In fact, the NiceHash miner itself appears to have the same flaw, except that maybe it switches algos less frequently so the waste is less noticeable.

Finally, I think it's nice that a `function` method will be added in the future. Is there an estimate for when this will be delivered? Will this feature solve my issue, or will it simply be syntactic sugar for simply stopping an algo and starting another like we do now?

**Comment by dropky** [comment]
Your hashing power is not wasted. The process of finding shares is completely random, you could find 5 shares in 10 seconds or not find any for over a minute or more (depends on the algorithm and its difficulty). Let's look at two cases:

1. You're mining the same algorithm (without switching) and you don't find a share for over a minute
Your current accepted pool speed is for example 10mhs. If you don't find any shares for a minute the accepted speed will drop, but it will still be bigger than zero, meaning your profitability graph will look just fine.  

2. You just switched and you don't find a share for over a minute
When you switch to a different algorithm the accepted pool speed is zero, now if you don't find any shares the pool speed is still zero hence the profitability graph will show you zero for that time.

Also, when it comes to excavator we're cancelling hashing process before or after the share/nonce calculation (equihash is an exception, hashing can be cancelled in the middle as well to avoid high rates of stale jobs, but we're talking about microseconds here). 

Another thing you should take into consideration: Let's say that you just switched to algo1, you're running it for 2 minutes and then you switch to algo2. It could happen that you didn't find any shares in that 2 minutes, meaning your pool speed and profitability would be zero. 

Another example.. Cryptonight difficulty is quite high these days and the shares send to the pool are very rare. Even without switching you can see the drops to zero, but these drops don't affect the overall profitability.

Once again, your hashing power is not wasted.

**Comment by GrossoMoreira** [comment]
Ok @dropky, thank you very much for this explanation! These explanations are really hard to find, you know..

This is enough to close this issue (as this is only the excavator's repo and not a NiceHash support forum), but if you can still answer more questions I'd love to keep reading your explanations.

Everything about the NiceHash service gives the impression that miners are payed based on their hashrates. However your explanation makes it look like they are paid 'per share', regardless of hashrate. Naturally, higher hashrates increase the probability of shares being accepted more frequently.

It's important to know if miners are paid per share or per hashrate:
- If they are paid per share then I don't mind switching algos often, for the reasons you already explained.
- If they are paid per hashrate, then I can't switch algos often, otherwise NiceHash will see that my hashrate is always close do 0, resulting in very low overall profitability.

So, could you please clarify how the rewards are calculated? Thank you!

**Comment by dropky** [comment]
Miners are paid per accepted shares - higher the difficulty higher the value of the share. Frequency of shares is also used to calculate the accepted pool speed (based on difficulty), so practically it's the same. 

Note: pool speed != miner speed; Miner speed is the hashrate reported to you by excavator, pool speed is what you see on the website;
