### ISSUE TITLE
Excavator benchmarks itselft all the time

### ISSUE THREAD

**Issue by niknewb** [nicehash/excavator#176]
The problem is that every time I close\stop excavator or NHM2 on my working PC(1080Ti x2, i7 3770k 4.7Ghz, 12GB ram Windows 10 x64 16299 RTM)  I have to benchmark some of the algos over and over again and this is really uncomfortable. Same thing happens on my mining rigs. It isn't much of a deal on my dedicated mining rigs but still after each NHM2 update I have to benchmark all my 10 GPUs and this is very time consuming. What can I do about this?

**Comment by EvgeniyKorepov** [comment]
@niknewb, try use https://github.com/EvgeniyKorepov/MinerPro-for-NiceHash
- All data is located in his folder with the application, but not in the depths of AppData.
- When benchmarking and saving, backup copies of all rewritable data are made.
- You can customize the overclocking of video cards for each algorithm individually. And only at the expense of it to receive 5-10% of the additional income and economy of an electricity.
- And many other advantages.
<img width="952" alt="screenshot008" src="https://user-images.githubusercontent.com/35364901/35989076-4e2bf4ac-0d11-11e8-931c-e512182b40b7.PNG">

**Comment by dropky** [comment]
@niknewb I reported this issue to the NHM team.

**Comment by dropky** [comment]
@EvgeniyKorepov The purpose of the issues is to report a bug or feature request to improve the product and to find the solution for the problem. We would appreciate if you wouldn't promote your miner here.

**Comment by dropky** [comment]
@niknewb Your benchmark files could be corrupted. Go to `C:\Users\username\AppData\Roaming\nhm2\configs` folder and delete all `benchmark_GPU*` files. Open NHM, perform benchmark, close/open NHM again to see if it worked. Let me know if this solves the issue.

**Comment by dropky** [comment]
@niknewb You can find the temporary solution here - https://www.reddit.com/r/NiceHash/comments/7we5xq/benchmarking_crashes_and_repetitive_benchmarking/
