### ISSUE TITLE
API Feature Request: Return current difficulty from running worker

### ISSUE THREAD

**Issue by gordan-bobic** [nicehash/excavator#178]
Unfortunately, even on relatively high end GPUs,occasional difficulty spikes (typically corellating with price spikes) mean that the device will never return a hash before the job goes stale. This means wasting resources on hashing jobs that are unattainable.

It is currently not possible to specify max. difficulty of jobs to accept, nor is it possible to query the difficulty of a currently running job to abort it.

Stdout outputs difficulty of the job just received but there is no way to tell which worker on which GPU the job is running on. At the very least, can excavator please output to stdout an identifiable worker or GPU ID that can be used to abort it so as to not continue wasting resources on what will never be submitted before it goes stale?

**Comment by nicehashdev** [comment]
You can adjust running time of kernel by reducing number of blocks thus reducing amount of time spent waiting for kernel to finish. Reduction will yield slower hashrate but decrease likelyhood of stale shares. Problem fixed. Closing.
