### ISSUE TITLE
1.2.9 not starting -> illegal memory access

### ISSUE THREAD

**Issue by Twente-Farm** [nicehash/excavator#18]
Hello again,

i'm testing the new version. And i'm being met with an error:
 'an illegal memory access was encountered' in func 'cuda_eq_
This also crashes the NVidia driver.

running in admin mode gives
CUDA error 'unspecified launch failure' in func 'cuda_eq_run' line 2380
running in admin does not crash driver.

[log_2017-06-29_16-31-10.1913.zip](https://github.com/nicehash/excavator/files/1114367/log_2017-06-29_16-31-10.1913.zip)

thank you in advance

**Comment by nicehashdev** [comment]
These kind of errors are due to unstable overclock. If it happens every few hours, you have nothing to worry about - restart script will put the excavator back on.

**Comment by Twente-Farm** [comment]
hm, strange.  It won't start miners at all anymore.
Cards were running at stock settings.
Even EWBF stopped working. reinstalling drivers now. 

Will comment again if there's progress.
thank you

**Comment by Twente-Farm** [comment]
gave up, switched to linux., cards running perfect again. 740 sol each with another miner. you can close this one

**Comment by nicehashdev** [comment]
Well, if any miner didn't work, then this is def. not an issue with Excavator but something OS-driver related.

**Comment by Twente-Farm** [comment]
yeah windows was shite with these cards. founder editions work great. also in excavator. on linux all my problems dissipated like snow before the sun.
