### ISSUE TITLE
Excavator stops after a few hours of operation

### ISSUE THREAD

**Issue by AlwaysCandr** [nicehash/excavator#180]
Hello,

I seem to be having a problem with the latest Excavator. The problem is that after a few hours of mining equihash, excavator stalls, displaying this:

```
[10:25:47][0x000000bbc][info] core | Algorithm 'equihash' total speed: 752.810000 H/s
[
```

The [ sign is the last thing that appears. After that, I need to restart the excavator in order to continue mining. The GPU used is 1080Ti Aorus, slightly overclocked. Latest drivers. No antivirus. Windows 10. The pool is zec.suprnova.cc.

**Comment by dropky** [comment]
This is a windows 10 cmd issue, it usually happens after you use scrolling tab.  If you check the pool speed you'll notice that excavator continues mining and is responsive to API commands as well, meaning excavator works just fine, only the writing to console is disabled (thread that writes to cmd gets suspended).

**Comment by dropky** [comment]
We might add a fix for this in the future, but it's not our priority right now since mining continues normally.
