### ISSUE TITLE
Version 1.4.4 - wonderful results on GTX 1070 neoscrypt!

### ISSUE THREAD

**Issue by EvgeniyKorepov** [nicehash/excavator#182]
Algorithm neoscrypt.

GTX 1070 x 5 (TDP/Core/Memory=95/90/0) 🥇 👍 
- Version 1.4.3 - 5,687 MH/s, 824W 
- Version 1.4.4 - 6,164 MH/s, 830W

GTX 1080 (TDP/Core/Memory=100/100/0)
- Version 1.4.3 - 1,299 MH/s, 201W 
- Version 1.4.4 - 1,312 MH/s, 201W 

GTX 1080 Ti (TDP/Core/Memory=100/130/200) Speed remains the same
- Version 1.4.3 - 1,919 MH/s, 253W 
- Version 1.4.4 - 1,919 MH/s, 253W

**Comment by EvgeniyKorepov** [comment]
We are waiting for the description of the parameter M in https://github.com/nicehash/excavator/tree/master/nvidia#neoscrypt

**Comment by dropky** [comment]
We didn't do any speed improvements for 1080 (Ti) cards so your results are as expected :)

Regarding the M parameter, the current version of excavator includes different implementations of neoscrypt - kernels might vary a bit from one mode to another and some modes work better on the specific card than others. For example, you'll notice that 1070 card uses mode 2 while 1080 uses mode 3. We opened the M parameter to the API because on cards that are not optimized (all Maxwell cards for example) different mode could perform better than the default one.

**Comment by dropky** [comment]
Btw, as always.. Thanks for the feedback! :)

**Comment by EvgeniyKorepov** [comment]
@dropky Thanks for the info!
Immediately received improved results:
- GTX 960, M=1 (default) - 306 KH/s
- GTX 960, M=3 - 332 KH/s
- GTX 960, M=5  - 333 KH/s

**Comment by kingyem** [comment]
> We didn't do any speed improvements for 1080 (Ti) cards so your results are as expected :)

I'm not sure but for my set up, the benchmark result for my 2 1080tis increased from 4.01(1.4.3) to 4.11(1.4.4) MH/s

for both,
power 100, undervolted to 0.962(have 2 different brand cards and don't have the same peak for their respective curves), memory +400

**Comment by EvgeniyKorepov** [comment]
@kingyem Does memory overclocking affect neoscrypt?
Now quickly tested:
1. Reducing the memory frequency greatly reduces the speed (tens of percent).
2. Increasing the memory frequency to +200 at 1080 Ti slightly increases the speed. A further increase in the memory frequency does not affect the speed.

**Comment by kingyem** [comment]
@EvgeniyKorepov I did the overclock for core and memory for gaming actually, and was lazy to setup profiles for different usages, so i stuck with the same settings for all application, not efficient i know.

tried playing around with the values for M with values 4 and 5, it resulted in a significant reduction from 4.11 to 3.13 or so MH/s for both cases, so i just left it as the default setting

great work by the team,kudos

**Comment by borzaka** [comment]
Sorry guys, I have to ruin the party: #184
