### ISSUE TITLE
Version 1.4.4 - NeoScrypt speed is NOT improved

### ISSUE THREAD

**Issue by borzaka** [nicehash/excavator#184]
I'am having terrible performance loss with Version 1.4.4 alpha
- 3x 1080 Ti + 3x 1070 Ti
- Hashrate dropped from ~10,25 MH/s (previous version) to ~8,87 MH/s (current version) with the same overclock settings
- Driver: 388.71
- OS: Windows 10 64 bit, 8GB RAM, 60GB virtual memory

```
[00:25:07][0x000005b0][info] wrkr5-2 | Algorithm: CUDA-neoscrypt parameters: B=540 M=2
[00:25:07][0x00000be0][info] wrkr2-0 | Algorithm: CUDA-neoscrypt parameters: B=1792 M=3
[00:25:07][0x00001f6c][info] wrkr3-4 | Algorithm: CUDA-neoscrypt parameters: B=540 M=2
[00:25:07][0x000013b0][info] wrkr4-5 | Algorithm: CUDA-neoscrypt parameters: B=540 M=2
[00:25:08][0x00000964][info] wrkr0-1 | Algorithm: CUDA-neoscrypt parameters: B=1792 M=3
[00:25:08][0x00001a90][info] wrkr1-3 | Algorithm: CUDA-neoscrypt parameters: B=1792 M=3
```

This was the previous version default start parameters (the `B` was 720 for the 1070 Ti's):
```
[00:43:40][0x00001d98][info] wrkr2-0 | Algorithm: CUDA-neoscrypt parameters: B=1792
[00:43:40][0x000000d0][info] wrkr4-5 | Algorithm: CUDA-neoscrypt parameters: B=720
[00:43:40][0x00002148][info] wrkr1-3 | Algorithm: CUDA-neoscrypt parameters: B=1792
[00:43:40][0x00001640][info] wrkr5-2 | Algorithm: CUDA-neoscrypt parameters: B=720
[00:43:40][0x000011ec][info] wrkr3-4 | Algorithm: CUDA-neoscrypt parameters: B=720
[00:43:40][0x00001fe8][info] wrkr0-1 | Algorithm: CUDA-neoscrypt parameters: B=1792
```

Note: I don't know which card is having performance degradation; the 1080 Ti's, the 1070 Ti's or both.
Switching back to 1.4.3 the hashrate is again around 10,25 MH/s.

**Comment by aKra-NL** [comment]
Here with only 1080 Ti's it's actually the same, maybe try changing (actually adding it) the worker M=2 to M=3 for the 1070 Ti?

**Comment by dropky** [comment]
@borzaka Try updating your driver (I'm using 390.65). If the performance is still worse please try to detect on which card (1070 or 1080 Ti). What are your OC settings?

**Comment by EvgeniyKorepov** [comment]
@borzaka I think can help MinerPro (it's not advertising, it's just faster and more visual than creating hand configs and testing).
Just create two rigs. In one place 1080, in another 1070. You visually see the speed of rigs, then you can without stopping MinerPro change the version of the excavator and drivers.
Here I showed an example https://github.com/EvgeniyKorepov/MinerPro-for-NiceHash/issues/10
Try different values of the parameter M (1..5), although for my 1080, 1080 Ti, 1070, the default M parameter is ideal.
Here is an example for testing the parameters https://github.com/EvgeniyKorepov/MinerPro-for-NiceHash/issues/16

**Comment by borzaka** [comment]
I can tell that the 1070 Ti's are having degraded performance with the 1.4.4 version.

Screenshots are from @EvgeniyKorepov's MinerPro for NiceHash. Thank you, I was able to test different settings easily.

1.4.4
![144a](https://user-images.githubusercontent.com/1230402/36198492-1298e61a-1177-11e8-8912-74ec0f1616e1.PNG)

1.4.3
![143a](https://user-images.githubusercontent.com/1230402/36198557-2fc07046-1177-11e8-9784-04c8749abc7b.PNG)

Playing with the 1070 Ti's:
- `B=540,M=2` 2,981 MH/s (default 1.4.4 settings)
- `B=540,M=3` 4,257 MH/s
- `B=720,M=2` 3,024 MH/s (default `B` setting in 1.4.3)
- `B=720,M=3` 4,314 MH/s (best settings for 1070 Ti so far, it's almost the same as was in 1.4.3)

Overclock settings:
- 1070 Ti: 100%, +200/+600
- 1080 Ti: 100%, +100/+600

All in all, my hashrate is almost the same as was in 1.4.3. Maybe 0,05 MH/s lower.

Note: I have not updated my driver. It's still 388.71

**Comment by dropky** [comment]
Please update your drivers and check the performance then. I tested it on the 1070 Ti today and v1.4.4 works better compared to v1.4.3.

**Comment by borzaka** [comment]
I have updated my NVIDIA drivers to 390.77, but nothing is changed: my 3 1070 Ti cards are still performing worse with 1.4.4

The custom `B=720,M=3` settings are still the best for these cards in my setup, and performing the same (maybe a little higher) as in 1.4.3

**Comment by dropky** [comment]
> Overclock settings:
> 1070 Ti: 100%, +200/+600

I re-checked it with the same overclock settings that you have and I get similar results. It looks like the optimal default parameters for 1070 Ti vary from different OC settings to another. I suggest you to use the one that you found for now (B=720, M=3). We're gonna perform some more thorough testing on 1070 Ti and update the default parameters in upcoming release (if necessary).

**Comment by dropky** [comment]
@borzaka I've run some tests on 1070 Ti, I get the best performance with B=608 and M=5 parameters (a bit better than with B=722, M=3).

**Comment by borzaka** [comment]
In my longer testing with your and my parameters with 3 1070 Ti:
- `B=608,M=5` 4,310 MH/s
- `B=720,M=3` 4,295 MH/s

For comparison, with the previous 1.4.3 version with default `B=720` parameter:
- 4,300 MH/s

Too many combinations to play with :)

**Comment by dropky** [comment]
I updated the latest zip with new excavator.exe that has different default parameters for 1070 Ti (B=608, M=5). @borzaka Thanks for your help!
