### ISSUE TITLE
WebServer does not work :(

### ISSUE THREAD

**Issue by michalss** [nicehash/excavator#185]
Hi all,

Not sure what is wrong but excavator webserver does not work for me. Trying to access http://127.0.0.1:4000/api?command={%22id%22:1,%22method%22:%22device.list%22,%22params%22:[]}

but it does not show anything in webbrowser. Can i actually use get or require post ? Btw i was trying telnet and it is working correctly  which is very strange. Pls help..

**Comment by agiz** [comment]
Is excavator web API running on port 4000?

**Comment by michalss** [comment]
Yes, as far as i can see in api document, it says we need to use -wp para, but how can i do that with NiceHash2 application, its starting it automatically without this para. :( Its acting very strange to be honest..

**Comment by agiz** [comment]
Set `-wp` parameter in `C:\Users\<user>\AppData\Roaming\nhm2\configs\General.json`.
You have to append `-wp <http_port>` to `"ExcavatorExtraStartupParameters": "-f 0",` so it looks something like `"ExcavatorExtraStartupParameters": "-f 0 -wp 3457",`. Now you can communicate with web api through port 3457.

**Comment by michalss** [comment]
Thx that did the trick :)

**Comment by EvgeniyKorepov** [comment]
@michalss add "-wi 0.0.0.0"
