### ISSUE TITLE
Neoscrypt Performance Artefact

### ISSUE THREAD

**Issue by gordan-bobic** [nicehash/excavator#186]
With 1.4.4 neoscrypt performance on a 1070 is 1.22MH/s, but on 1070Ti with the exact same settings it is 700KH/s.

For cross-check, ccminer manages 1.16MH/s on the same 1070Ti with the same settings. Kernel parameter auto detection bug?

**Comment by dropky** [comment]
Check here: https://github.com/nicehash/excavator/issues/184#issuecomment-365928967 

Try to run it with different default settings (B=720, M=3).

**Comment by dropky** [comment]
Please refer to #184
