### ISSUE TITLE
Excavator API function workers.add

### ISSUE THREAD

**Issue by MichaelMiner** [nicehash/excavator#188]
Please, check the workers.add function,
sometimes it does not work

**Comment by dropky** [comment]
Do you have an example (or log file) when it doesn't work?

**Comment by MichaelMiner** [comment]
Hi
I'm not have log file? but create it later

**Comment by dropky** [comment]
You have to run excavator with -f 0 parameter.

**Comment by dropky** [comment]
What do you mean by no parameter for log file? How are you running excavator?

**Comment by MichaelMiner** [comment]
-f not used

**Comment by dropky** [comment]
How are you running excavator? Are you using command prompt? If yes, you have to start excavator with following command: `.\excavator.exe -f 0 -c config_file.json`

If you're using NiceHash Miner or any third party miner that's using excavator let me know.

**Comment by MichaelMiner** [comment]
Excavator starts from my program use Excavator API

**Comment by dropky** [comment]
Which program do you use? If you can't get the log file, could you at least explain what is the problem with the workers.add method (workers aren't added, they're added to the wrong algorithm/device ... )?

**Comment by EvgeniyKorepov** [comment]
@dropky I suspect that this is a continuation of the topic https://github.com/nicehash/excavator/issues/70 and the problem is not exactly in the Excavator.

**Comment by MichaelMiner** [comment]
I.m use MY PROGRAM.

**Comment by dropky** [comment]
@MichaelMiner As @EvgeniyKorepov suggested, is this the same issue that was mentioned in #70 ?

**Comment by MichaelMiner** [comment]
Hi,
See attach for log files

**Comment by dropky** [comment]
I don't see any log files, please upload them here at github (not via email reply). If the file is too big you can always send them to support@nicehash.com (state in email that the logs are for the excavator team).

**Comment by MichaelMiner** [comment]
Logs
[Logs.zip](https://github.com/nicehash/excavator/files/1738887/Logs.zip)

**Comment by gordan-bobic** [comment]
If you are seeing workers added to wrong devices, are you sure you aren't mixing nvidia-smi device ID numbers and CUDA device ID numbers?

You may want to look into using the following environment variable:
CUDA_DEVICE_ORDER=PCI_BUS_ID
