### ISSUE TITLE
NiceHash Miner v2.0.1.10 - Beta Starting Excavator Server...

### ISSUE THREAD

**Issue by KotoyoChan** [nicehash/excavator#189]
Help me guys, my nicehash is stuck at starting excavator server.

I've tried reinstalling it, but that didn't solve the issue.
No error pop-ups for me either.

**Comment by dropky** [comment]
Check if you have excavator.exe in `C:\Users\user_name\AppData\Roaming\nhm2\bin\excavator_cuda9.1` folder. If yes, try to run it (double click) and report back if you see any errors. If you don't have it there you can manually download it from [github](https://github.com/nicehash/excavator/releases). If that's the case, check your antivirus (it probably detected excavator as a virus and removed it).

**Comment by KotoyoChan** [comment]
Thank you so much.
As it appears, my excavator.exe was missing from C:\Users\user_name\AppData\Roaming\nhm2\bin\excavator_cuda9.1 folder.

After adding it I was able to fix the issue.
