### ISSUE TITLE
CUDA error DRIVER: '999' in func 'run_single_stream' line 978

### ISSUE THREAD

**Issue by tinkyisretarded** [nicehash/excavator#190]
7 x 1070 (4xGA WF OC2, 1x GA Aorus, 2x MSI Armor)
90.77 nvidia drivers
1.4.4a excavator
72Gb virtual memory
1500W PSU
BIOS up to date
no software for overclock

![capture](https://user-images.githubusercontent.com/34728495/36346618-5828a4ce-144a-11e8-9539-1143545bcff7.PNG)
it crashes on Neoscrypt, Equihash, Lyra2rev2, Nist5.

tried to use overclock software to reduce power at 50%. still crashing
any solution?

**Comment by EvgeniyKorepov** [comment]
Are you trying to run two algorithms at the same time? The screenshot shows Equihash and Lyra2rev2. 
Show your json config.

**Comment by tinkyisretarded** [comment]
{
	"ConfigFileVersion": {
		"Major": 2,
		"Minor": 0,
		"Build": 1,
		"Revision": 10
	},
	"VersionString": "2.0.1.10",
	"Language": 0,
	"DisplayCurrency": "",
	"DebugConsole": false,
	"LoginType": 1,
	"BitcoinAddress": "",
	"NicehashEmail": "",
	"WorkerName": "",
	"ServiceLocation": 0,
	"AutomaticServiceLocation": true,
	"AutoStartMining": false,
	"HideMiningWindows": false,
	"MinimizeToTray": false,
	"SwitchProfitabilityThreshold": 0.05,
	"MinerAPIQueryInterval": 5,
	"MinerRestartDelayMS": 500,
	"DisableDetectionCPU": false,
	"DisableDetectionAMD": false,
	"DisableDetectionNVIDIA": false,
	"SpeedAverageType": 1,
	"StartMiningWhenIdle": false,
	"MinIdleSeconds": 60,
	"LogToFile": true,
	"LogMaxFileSize": 1048576,
	"NVIDIAP0State": false,
	"EnableFanControl": false,
	"ApiBindPortPoolStart": 5100,
	"MinimumProfit": 0,
	"Use3rdPartyMiners": 0,
	"ExcavatorExtraStartupParameters": "",
	"ExcavatorNVIDIAStatsQuery": true,
	"ExcavatorAMDStatsQuery": false,
	"ExcavatorIgnoreAMD": false,
	"IgnoreStartupWarnings": false,
	"LastDevicesSettup": [
		{
			"Name": "Intel(R) Celeron(R) CPU G3930 @ 2.90GHz",
			"Enabled": false,
			"UUID": "GEN-88c319ab13903ed29d9af2faf0316b4d0d34f57ffc298146e34888e8af356362"
		},
		{
			"Name": "Gigabyte GeForce GTX 1070",
			"Enabled": true,
			"UUID": "GPU-2dd13053-c943-6d58-1e31-575a7ad66843"
		},
		{
			"Name": "MSI GeForce GTX 1070",
			"Enabled": true,
			"UUID": "GPU-16dfaf29-525f-7167-d384-c2a713734c4e"
		},
		{
			"Name": "MSI GeForce GTX 1070",
			"Enabled": true,
			"UUID": "GPU-3305298a-04f6-b96a-b9cf-4b4d6b0bb4b6"
		},
		{
			"Name": "Gigabyte GeForce GTX 1070",
			"Enabled": true,
			"UUID": "GPU-a41626e7-00be-9e6f-8905-51b51eac8025"
		}
	],
	"IgnoredWarnings": [],
	"SwitchSMATimeCheckRangeSeconds": [
		34,
		55
	],
	"SwitchSMAStableTicksRangeCount": [
		2,
		3
	],
	"SwitchSMAUnstableTicksRangeCount": [
		5,
		13
	],
	"hwid": "fedd9c8d0469c7770e80f42e2e8c1dca79d8a53831913c08ea1eb75d6a4b7350",
	"agreedWithTOS": 3,
	"riskAcknowledgementAgreedWithTOS": 3
}

**Comment by dropky** [comment]
Oh, you're using NHM (you should mentioned it before). Does it work if you run only one algorithm at the time? Disable all algorithms except one (e.g. lyra2rev2 or equihash) so NHM will run the same algorithm on all cards. 

Btw, you said you have 7 cards but in your config file there are only 4 listed. Does NHM recognise all your devices? Is this the latest General.json file?

**Comment by tinkyisretarded** [comment]
yes, it recognise all cards. this is the latest General.json made after crashing.
it crash also if i rung the same algo on all cards with all other algos disabled

**Comment by dropky** [comment]
If you try to run standalone excavator does it work? 

You'll have to run excavator.exe using windows command prompt with the next command:
.\excavator.exe -c config.json

Copy/paste this to your config.json file (don't forget to change your_btc_address):
```
[
	{"time":0,"commands":[
		{"id":1,"method":"algorithm.add","params":["lyra2rev2","lyra2rev2.eu.nicehash.com:3347","your_btc_address"]}
	]},
	{"time":1,"commands":[
		{"id":1,"method":"worker.add","params":["0","0"]},
		{"id":1,"method":"worker.add","params":["0","1"]},
		{"id":1,"method":"worker.add","params":["0","2"]},
		{"id":1,"method":"worker.add","params":["0","3"]},
		{"id":1,"method":"worker.add","params":["0","4"]},
		{"id":1,"method":"worker.add","params":["0","5"]},
		{"id":1,"method":"worker.add","params":["0","6"]}
	]},
	{"time":10,"loop":20,"commands":[
		{"id":1,"method":"algorithm.print.speeds","params":[]}
	]}
]
```

**Comment by tinkyisretarded** [comment]
i do not have a config.json file on my computer

**Comment by tinkyisretarded** [comment]
did that. still crashes

**Comment by dropky** [comment]
Did you start excavator via command line (not with NiceHash Miner)? Can you make a screenshot of the cmd window please?

**Comment by tinkyisretarded** [comment]
of course i did it. i started the excavator from c:\users\...\AppData\Roaming\nhm2\bin\excavatpr_cuda9.1

**Comment by tinkyisretarded** [comment]
also tried with older version of excavator. same result

**Comment by dropky** [comment]
Did you try to do a clean reinstall of the drivers?

**Comment by tinkyisretarded** [comment]
yes, of course

**Comment by tinkyisretarded** [comment]
wrong. all my rigs are mixed. even 1070 &1080ti or 1070 and 1080 mixed and all working. this one also worked perfect for about 2 months.

**Comment by dropky** [comment]
> this one also worked perfect for about 2 months.

Try to detect what changed since then (driver version, windows update .. ). Also, check your risers, if everything is connected ok. It's possible that something is wrong with one of the cards and it's crashing the driver. Try running excavator on one card at the time and see if it works on each card.

**Comment by tinkyisretarded** [comment]
working on it. i will get back once done

**Comment by tinkyisretarded** [comment]
so, i reinstalled windows, card by card up to 6 cards, run ok for about 6 hours and then starting to crush again each time i start mining

**Comment by tinkyisretarded** [comment]
@dropky @EvgeniyKorepov found smth interesting. running stable for last 20 minutes. i will keep you updated

**Comment by tinkyisretarded** [comment]
seems like it is a hardware problem. risers does not receive proper power from the PSU. so problem is solved now. thanks alot for your time spent with me. gl
