### ISSUE TITLE
Net error: JSON memeber missing: "error", when using daggerhashimoto with nanopool

### ISSUE THREAD

**Issue by Spyrox99** [nicehash/excavator#192]
I just jumped from mining zcach to ethereum and miner is not working anymore. It seems like issue with conecting to nanopool. My .json looks like this, i think there is nothing wrong with it. But i still get this error mesage. 

.json:

 _[
	{"time":0,"commands":[
		{"id":1,"method":"algorithm.add","params":["daggerhashimoto","eth-eu1.nanopool.org:9999","0x83e3e9a3646b1588e04b970d98f14e390305ccee.main01"]}
	]},
	{"time":3,"commands":[
		{"id":1,"method":"worker.add","params":["0","0"]}
	]},
	{"time":10,"loop":10,"commands":[
		{"id":1,"method":"worker.print.speed","params":["0"]},
		{"id":1,"method":"algorithm.print.speeds","params":["0"]}
	]}
]_

error:

![image](https://user-images.githubusercontent.com/36592378/36350646-1e987f20-149c-11e8-9d29-f206bf417b27.png)

**Comment by dropky** [comment]
Unfortunately, some pools are not compatible with our stratum protocol.

**Comment by dropky** [comment]
See #162
