### ISSUE TITLE
Missing excavator server

### ISSUE THREAD

**Issue by Emon172** [nicehash/excavator#193]
So I just downloaded the software from nicehash's website and installed but when I went for benchmarking it showed that I have no minier file of any of the algorithms. 
![missing](https://user-images.githubusercontent.com/36608432/36356992-d61f8de2-1522-11e8-9915-671df5f64f23.png)

I still tried to mine but it says that,"excavator_server" missing. Not "excavator_server_91" just "excavator_server". Why so? 
![excavator](https://user-images.githubusercontent.com/36608432/36356949-a49015c6-1522-11e8-99a5-67c472d129f2.png)

Here's a picture of the excavator_server folder
![server](https://user-images.githubusercontent.com/36608432/36357147-ee96bc46-1523-11e8-81d2-5085874db1b1.png)
 
So how should I fix this guys? Please let me know

**Comment by dropky** [comment]
Please refer to https://github.com/nicehash/excavator/issues/157#issuecomment-361853442

**Comment by dropky** [comment]
> I still tried to mine but it says that,"excavator_server" missing. Not "excavator_server_91" just "excavator_server". Why so?

NHM will use excavator_server9.1 if you have driver version 387.xx or more recent.
