### ISSUE TITLE
printing temperature in command window

### ISSUE THREAD

**Issue by adrianTNT** [nicehash/excavator#194]
Is there a way to also print temperature in command window next to speed ?

I tried these in command file (didn't work), I know it shows temp in web interface but for me is nicer to see them in live command/output window.

`		{"id":1,"method":"worker.print.gpu_temp","params":["0"]},
		{"id":1,"method":"worker.print.temp","params":["1"]},
		{"id":1,"method":"worker.print.temperature","params":["2"]}
`

**Comment by dropky** [comment]
No, excavator doesn't support that. Sorry.
