### ISSUE TITLE
P104-100 low hashrate?

### ISSUE THREAD

**Issue by davidhonasan** [nicehash/excavator#196]
I'm using 1 Manli P104-100. and I test it on DaggerHashimoto in Excavator, I could only got 30MH/s. While on Claymore Single ETH in Nicehash Miner Legacy I could get up to 39 MH/s. any idea why it's getting so low hashrate on excavator?

btw, i also get 450 sol/s on excavator, while i could get 490sol/s on dstm

**Comment by dropky** [comment]
It looks like excavator is not fully optimized for p104 cards. We'll look into it.

**Comment by davidhonasan** [comment]
it's hashrate is kinda like 1070 cards btw.

**Comment by nicehashdev** [comment]
Hashrate is low for all 1xxx cards. You need to run eth pill to get higher hashrate. Closing.
