### ISSUE TITLE
Web server for monitoring multiple rigs

### ISSUE THREAD

**Issue by TrantorRWS** [nicehash/excavator#2]
I have multi rigs like lot of people and I would love to view all of them in a single place.
Will it be possible to have one "master" web server in order to display informations of all rigs ?

excavator will connect to an existing management web server on the network like a simple client

If it possible it will be AMAZING 🥇

**Comment by nicehashdev** [comment]
It is already possible if you modify index.html in folder web.

Use one excavator for getting html data, and the rest for getting API data over js.

**Comment by TrantorRWS** [comment]
Great news :D
But which part should I update in index.html ?
I'm a total noob in web :(

**Comment by nicehashdev** [comment]
We have no plans to make default page available for multiple miners.

By default, excavator binds to localhost and can be accessed only on local PC. If you need access in your LAN, then you should bind to your LAN IP.

**Comment by Kayfolom** [comment]
I have plans to write a simple application for Android to monitor the excavator.
Maybe next week I will publish the application here https://play.google.com/store/apps/developer?id=%D0%95%D0%B2%D0%B3%D0%B5%D0%BD%D0%B8%D0%B9+%D0%9A%D0%BE%D1%80%D0%B5%D0%BF%D0%BE%D0%B2

**Comment by TrantorRWS** [comment]
I have already edited the config file to bind to LAN IP.
I can access excavator web page from other computer in the same LAN but can't from mobile devices.

**Comment by Kayfolom** [comment]
> Я уже отредактированный файл конфигурации для привязки к IP - сети. 
> Я могу получить доступ к веб - страницу экскаватор с другого компьютера в той же локальной сети , но не может с мобильных устройств.

Try use "How to enable JavaScript in your iphone"
http://aboutjavascript.com/en/how-to-enable-javascript-in-safari.html

**Comment by Kayfolom** [comment]
Excavator Monitor
https://play.google.com/store/apps/details?id=ru.flintnet.ExcavatorMonitor

**Comment by eewartlu** [comment]
Like this?

![dash](https://user-images.githubusercontent.com/34083048/36018591-e8e06620-0dae-11e8-95fc-462c0fe3e981.PNG)

**Comment by nicehashdev** [comment]
Web is not supported anymore. Closing.
