### ISSUE TITLE
Use API - How to stop work?

### ISSUE THREAD

**Issue by Kayfolom** [nicehash/excavator#20]
How to stop work via API?
1. Consistently remove the workers, then remove the algorithms, then remove the overclocking?
2. Delete algorithms? What will happen?

Can add the stop command to the API? Which will return the miner to idle with zero acceleration.

**Comment by nicehashdev** [comment]
1. You can free workers or you can simply remove algorithm which will also cause all workers attached to that algorithm to be freed (removed).

2. Read 1.

To stop mining you can either free workers or remove algorithm.
