### ISSUE TITLE
Shares rejected 'share above target' - Excavator

### ISSUE THREAD

**Issue by pookie1** [nicehash/excavator#203]
Hi, in the last few days I am now getting many shares rejected when on Algorithm 'daggerhashimoto_decred'. It isn't every share, but many.

Using NiceHashMiner latest version. 

[05:45:48][0x00000744][info] net | Share #93 rejected
                                reason: Share above target.
[05:45:52][0x00000744][info] core | Algorithm 'daggerhashimoto_decred' total speed: 82.429402 MH/s & 2.637741 GH/s
[05:45:54][0x00000744][info] algo-daggerhashimoto_decred | New job_0 '0000001a4ae37334', diff=0.5
[05:45:55][0x0000174c][info] net | Share #94 rejected
                                reason: Share above target.
[05:45:57][0x00000744][info] net | Share #236 accepted
[05:45:57][0x00000744][info] core | Algorithm 'daggerhashimoto_decred' total speed: 82.439885 MH/s & 2.638076 GH/s

How do I fix this, please?

Thanks

Pookie

**Comment by dropky** [comment]
Which shares get rejected (shares for daggerhashimoto or shares for decred)? You can check that on the miner website, check which algorithm has rejected pool speed.

**Comment by pookie1** [comment]
Hi. It's Daggerhishimoto.
Cheers 
Pj

Sent from Yahoo7 Mail on Android 
 
  On Fri, 2 Mar 2018 at 8:50 PM, dropky<notifications@github.com> wrote:   
Which shares get rejected (shares for daggerhashimoto or shares for decred)? You can check that on the miner website, check which algorithm has rejected pool speed.

**Comment by Mkekala** [comment]
I've gotten 53.9% of my DaggerHashimoto shares rejected as well, all Decred shares accepted.

**Comment by dropky** [comment]
Can any of you provide excavator log files? 

Check here how to enable excavator file logging - https://github.com/nicehash/excavator/issues/135#issuecomment-364583892

**Comment by pookie1** [comment]
Hi
Please find attached a short logfile showing at least one rejected share.
Cheers
PJ

**Comment by dropky** [comment]
I need to see the logs with -f 0 parameter in order to get the received data for the job so we can simulate it. On which stratum are you connected?

**Comment by dropky** [comment]
@pookie1 Oh, you did send the log file, my mistake.. Unfortunately, I can't see the attachment here on github. You'll have to upload the log file here or send it to support@nicehash.com (state in email that the logs are for excavator team). Thanks

**Comment by pookie1** [comment]
Hi,
Did you get the logfile I sent to support@nicehash.com ?
I have noticed the past few days that I am now getting alot more rejected shares (4-5%) as opposed to previously 1-2%. 
The errors overnight were all "Shares Above Target", however, yesterday they also included "Duplicate Shares". 
I'm not sure if it's related or not, but my profit has also dropped from $9 per day to $4 per day :(
Cheers
PJ

**Comment by dropky** [comment]
Yes, I did, nothing unusual in the logs. What are your overclocking settings? If you set your cards to the stock settings (try for an hour), do you still get rejected shares?
