### ISSUE TITLE
100% CPU usage on GPU mining

### ISSUE THREAD

**Issue by ilgrank** [nicehash/excavator#205]
It seems that the issue appeared on 2.0.1.4 and solved in 2.0.1.5:
nicehash/excavator#63
nicehash/excavator#176
has popped up again:
GPU only mining, Excavator starts at 10% CPU usage but gets to 100% after a few hours.
Closing and restarting, and the same happens (starts low, gets to 100%)

**Comment by dropky** [comment]
Thanks for the report, we're gonna take a look.

**Comment by dropky** [comment]
@ilgrank Which algorithms are you mostly running? Did you enable all of them or just specific ones? Which OS do you use? What GPUs and CPU do you have?

**Comment by ilgrank** [comment]
Currently mostly Ethhash (dagger solo). Using 3x1070 on W10 Pro.

Other enabled algos: Neoscrypt, Equihash.

In the past days, when Neo and Equi were more profitable, I did not have this issue.

At first I tought of a problem with overclocks (which were 100% stable using Neo and Equi) so to have the most clean possible scenario, I reset to base clocks and the issue is still present.

The Windows UI becomes very non-responsive, and cpu skyrockets.


________________________________

**Comment by dropky** [comment]
Are you using the latest version of excavator? What about teamviewer? We noticed some high CPU spikes when connecting to the rig via teamviewer. Does the CPU load stays at 100% or does it falls down eventually (e.g. after the algorithm switching)?

**Comment by elwappoalot** [comment]
I'm having the same issue, new rig running 8 GPU's. Al NVIDIA cards using NVIDIA drivers version  391.01 and NicehashMiner v2.0.1.10 and v2.0.1.11
Can't seem to get NeoScrypt to run without getting a CUDA error, and when I disable it the other algos run OK for awhile but I see that Excavator is using 80-100% CPU. Then after several hours the rig seems to freeze.
Been struggling with this for a week now, I have another rig that's running 7 GPUs thats a lot more stable and it's a mixed rig of NVIDIA and AMD

**Comment by elwappoalot** [comment]
Back to running 5 GPUs and everything seems to be stable, I read a few places that running multiple versions of Nicehash may also help. I did try that before and it didn't seem to work, I will have to try different combinations of GPUs.

**Comment by dropky** [comment]
> I can't seem to get NeoScrypt to run without getting a CUDA error

Increase virtual memory, you should have as much virtual+regular mem as combined memory of all GPUs.

> Back to running 5 GPUs and everything seems to be stable

CPU load isn't increased if you have only 5 GPUs?

**Comment by elwappoalot** [comment]
I already increased Virtual memory to 32GB + the 8GB of RAM I have installed. 

The CPU still running higher (20-30%+ higher)  compared to my other rig running 7 GPUs

**Comment by nicehashdev** [comment]
There were some bugs related to high CPU usage that were fixed. Closing.
