### ISSUE TITLE
Keeps crashing when many GeForce GTX 1080 / since December

### ISSUE THREAD

**Issue by macekCZ** [nicehash/excavator#206]
Hi
I still have problem when using more than one GeForce GTX 1080 ... I have this problem since december I think :( I have 6 cards, run Excavator ( or Nicehash GUI ) and it tells some red errors, decrease number of GPUs to 5 and working ,.. same problem on 4 GPUs PC, it starts with 4, red error then mining on 3 cards. Sometimes it also happen on my PC with 2cards. ( all  GTX 1080 )
Restart of PC do not move back that non working GPU. I must unplug power, then plug back and then I can see 6 cards. But, crash to 5 immediately ,..

I have this problem on many algorithms, not only Neoscrypt. I also tried to mix algorithms but I have not find any working solution.

I tried latest drivers, I downloaded excavator 1.4.4 ,.. nothing helped me. But I remember that I was able to mine on 12 GPUs on one PC at November ! Since December, I mixed those cards to multiple PCs ,... It worked some time, but now sometimes two cards not working and decrease to one.

![excavator_144](https://user-images.githubusercontent.com/878400/36951578-bd619064-2005-11e8-91ea-6dbfe7a2cc05.jpg)

**Comment by dropky** [comment]
Check your power supplies if they're strong enough, also recheck your risers, if everything is connected ok. Next, you should increase your virtual memory (if you haven't already), also take a look at our troubleshooter, you might find something useful there - https://miner.nicehash.com/guides/NHM_troubleshooter_en.pdf. One more thing that you could check is if Windows performed any auto updates, in that case, try to do a clean reinstall of the drivers.

**Comment by nicehashdev** [comment]
This algorithm not supported anymore. Closing.
