### ISSUE TITLE
GTX 560 not working

### ISSUE THREAD

**Issue by mayhem7** [nicehash/excavator#207]
The card works perfectly but Excavator doesn't recognize it :( i know it's not the best card to mining but it's really cheap and still gives more than it consumes, better than nothing.

**Comment by dropky** [comment]
Your card is not supported. We're supporting only CUDA devices with SM 5.0 and higher.

You can check here supported CUDA level for each card:
https://en.wikipedia.org/wiki/CUDA#GPUs_supported
