### ISSUE TITLE
DaggerHashimoto connection refused

### ISSUE THREAD

**Issue by michalss** [nicehash/excavator#208]
https://user-images.githubusercontent.com/1000729/37019024-e9041bee-2116-11e8-8530-f910673684fe.png

Its strange it was working last night, all other algos are ok...

**Comment by EvgeniyKorepov** [comment]
Just use the miner with failover. And taking into account the electricity when calculating the profitability. For example, the sia algorithm (-$0.6 on 1080Ti) (and daggerhashimoto_sia) is now unprofitable.

**Comment by dropky** [comment]
There might be some temporary stratum issues. It's working for me right now. Try to connect again, it should work.

**Comment by michalss** [comment]
well still problem, so im not using it..
