### ISSUE TITLE
CUDA ids mixed

### ISSUE THREAD

**Issue by mayhem7** [nicehash/excavator#210]
If i run nvidia-smi.exe -L i get:
GTX 1050
GTX 1060
GTX 960
GTX 750
GTX 1050

But, when i run excavator ids are mixed (when it lists devices) amd then it crashes because i set overclock for cards following the nvidia-smi ids, so how can i list the ids for excavator to avoid this?

**Comment by EvgeniyKorepov** [comment]
In browser http://127.0.0.1:38080/api?command={"id":1,"method":"device.list","params":[]}
You will receive a list of GPUs with the correct ID

**Comment by mayhem7** [comment]
Thanks sir ;)
