### ISSUE TITLE
No compatible devices found, while running 1080Ti.

### ISSUE THREAD

**Issue by PaS3** [nicehash/excavator#211]
After upgrade  from Excavator 1.3.8 to 1.4.4a, the new excavator said, "No compatible devices found"

01:00.0 VGA compatible controller: NVIDIA Corporation Device 1b06 (rev a1)

1b06  =>>   Nvidia 1080Ti
Here is my environment:
4.13.0-36-generic #40~16.04.1-Ubuntu (Xenas-Xerox - aka Xenial Xerus)

options nvidia_390_drm modeset=1

ii  bbswitch-dkms              0.8-3ubuntu1   amd64        Interface for toggling the power on NVIDIA Optimus video cards
ii  libcublas7.5:amd64         7.5.18-0ubuntu1                 amd64        NVIDIA cuBLAS Library
ii  libcuda1-390               390.25-0ubuntu0~gpu16.04.1      amd64        NVIDIA CUDA runtime library
ii  libcudart7.5:amd64         7.5.18-0ubuntu1                 amd64        NVIDIA CUDA Runtime Library
ii  libcufft7.5:amd64          7.5.18-0ubuntu1                 amd64        NVIDIA cuFFT Library
ii  libcufftw7.5:amd64         7.5.18-0ubuntu1                 amd64        NVIDIA cuFFTW Library
ii  libcuinj64-7.5:amd64       7.5.18-0ubuntu1                 amd64        NVIDIA CUINJ Library (64-bit)
ii  libcurand7.5:amd64         7.5.18-0ubuntu1                 amd64        NVIDIA cuRAND Library
ii  libcusolver7.5:amd64       7.5.18-0ubuntu1                 amd64        NVIDIA cuSOLVER Library
ii  libcusparse7.5:amd64       7.5.18-0ubuntu1                 amd64        NVIDIA cuSPARSE Library
ii  libnppc7.5:amd64           7.5.18-0ubuntu1                 amd64        NVIDIA Performance Primitives core runtime library
ii  libnppi7.5:amd64           7.5.18-0ubuntu1                 amd64        NVIDIA Performance Primitives for image processing runtime library
ii  libnpps7.5:amd64           7.5.18-0ubuntu1                 amd64        NVIDIA Performance Primitives for signal processing runtime library
ii  libnvrtc7.5:amd64          7.5.18-0ubuntu1                 amd64        CUDA Runtime Compilation (NVIDIA NVRTC Library)
ii  libnvtoolsext1:amd64       7.5.18-0ubuntu1                 amd64        NVIDIA Tools Extension Library
ii  libnvvm3:amd64             7.5.18-0ubuntu1                 amd64        NVIDIA NVVM Library
ii  nvidia-390                 390.25-0ubuntu0~gpu16.04.1      amd64        NVIDIA binary driver - version 390.25
ii  nvidia-390-dev             390.25-0ubuntu0~gpu16.04.1      amd64        NVIDIA binary Xorg driver development files
ii  nvidia-common              1:0.4.17.7     amd64        transitional package for ubuntu-drivers-common
ii  nvidia-cuda-dev            7.5.18-0ubuntu1                 amd64        NVIDIA CUDA development files
ii  nvidia-cuda-doc            7.5.18-0ubuntu1                 all          NVIDIA CUDA and OpenCL documentation
ii  nvidia-cuda-gdb            7.5.18-0ubuntu1                 amd64        NVIDIA CUDA Debugger (GDB)
ii  nvidia-cuda-toolkit        7.5.18-0ubuntu1                 amd64        NVIDIA CUDA development toolkit
ii  nvidia-modprobe            361.28-1       amd64        utility to load NVIDIA kernel modules and create device nodes
ii  nvidia-opencl-dev:amd64    7.5.18-0ubuntu1                 amd64        NVIDIA OpenCL development files
ii  nvidia-opencl-icd-390      390.25-0ubuntu0~gpu16.04.1      amd64        NVIDIA OpenCL ICD
ii  nvidia-prime               0.8.2          amd64        Tools to enable NVIDIA's Prime
ii  nvidia-profiler            7.5.18-0ubuntu1                 amd64        NVIDIA Profiler for CUDA and OpenCL
ii  nvidia-settings            390.25-0ubuntu0~gpu16.04.1      amd64        Tool for configuring the NVIDIA graphics driver
ii  nvidia-visual-profiler     7.5.18-0ubuntu1                 amd64        NVIDIA Visual Profiler for CUDA and OpenCL

**Comment by dropky** [comment]
Can you post here the nvidia-smi output?

**Comment by monodrone** [comment]
Working fine now! 

I had the Ubuntu version of nvidia official packages installed, which sounds ironic.
So I removed them and used the NVidia installer executable, which does not know what it is doing half the time (closed source issues) but worked this time.  Here is the rundown : 

  sudo apt purge nvidia* 
  sudo reboot 
  sudo ./NVIDIA-Linux-x86_64-390.25.run

The other issue is the network:    Some ban?

[cryptonight.usa.nicehash.com:3355] connect error: "connection timed out"
[cryptonight.usa.nicehash.com:3355] read error: "connection reset by peer"

 Connected. Logging in...
 SOCKET ERROR - RECEIVE error:
 Pool connection lost. Waiting 10 s before retry.

**Comment by dropky** [comment]
There is no network ban, at least not on our side. Does this happen every couple of minutes? If yes, it's probably due to the high difficulty on the cryptonight. If the miner doesn't find and send any shares in X minutes (it should be around 10 minutes, but I might be wrong) the socket connection gets closed and then opened again.

**Comment by nicehashdev** [comment]
Ubuntu not supported for now. Closing.
