### ISSUE TITLE
Daggerhashimoto underperforms vs. ethminer

### ISSUE THREAD

**Issue by gordan-bobic** [nicehash/excavator#212]
I am seeing hash rates that are consistently approximately 3.5% lower than with ethminer.
On 1070/1070Ti with a long calibration run:
excavator: 28.83 MH/s
ethminer: 29.80 MH/s

It also seems to require about 2 extra watts (97W vs 94W)

This can make a substantial difference on a large farm.

**Comment by nicehashdev** [comment]
This should be fixed now. Closing.
