### ISSUE TITLE
net error: json member "error" not expected type: array

### ISSUE THREAD

**Issue by mayhem7** [nicehash/excavator#215]
What title says, getting this since yesterday, GPUs get 0% usage and getting that error spammed, then works again for a few min and back to errors (in fact thre're warnings), using coinfoundry.org pool, only getting this error with Excavator.

**Comment by dropky** [comment]
The error that you're describing happens due to non-compatible stratum protocols. Some pools are not compatible with excavator.

**Comment by mayhem7** [comment]
It was working fine until yesterday :s, i changed nothing... also tried suprnova and get same error.

**Comment by dropky** [comment]
Which algorithm are you running?

**Comment by mayhem7** [comment]
Equihash, tried same in both pools, starts working fine but after a while it starts getting that error.

**Comment by dropky** [comment]
Run excavator with -f 0 parameter to enable file logging and post the logs here or send them to support@nicehash.com (state in email that logs are for excavator team).
