### ISSUE TITLE
excavator_v1.2.9a_Win64 cause BSOD

### ISSUE THREAD

**Issue by miesdr** [nicehash/excavator#22]
Hi..

My rig will trigger BSOD if i run this version. Below is my detail:

OS: Windows 7 SP1 x64
GPU: NVIDIA GTX1060

**Comment by Kayfolom** [comment]
Delete the file phymem.sys

**Comment by nicehashdev** [comment]
This should be fixed in next version that is coming soon.

**Comment by nicehashdev** [comment]
Try it now and reopen this ticket if it isn't fixed for you.
