### ISSUE TITLE
Wrong hashrate?

### ISSUE THREAD

**Issue by Student992** [nicehash/excavator#220]
Hello guys.

I am trying to mine "cryptonight" with 4 nvidia P100 setup.

I am getting maybe a wrong hash rate and no shares accepted neither rejected.

![screenshot_1](https://user-images.githubusercontent.com/36270748/37613628-428ce05e-2b87-11e8-879a-16608d3e2933.png)

Am i doing something wrong?

Thank you very much!

**Comment by dropky** [comment]
6.0 architecture is currently not supported. We'll add support for P100 in upcoming release.
