### ISSUE TITLE
stratum client.reconnect issue

### ISSUE THREAD

**Issue by husanu** [nicehash/excavator#221]
want to use excavator with miningrigrentals and had this issue

> =========================== www.nicehash.com =========================
>            Excavator v1.4.4a_nvidia GPU Miner for NiceHash.
>            Copyright (C) 2018 NiceHash. All rights reserved.
>                               Developed by
> 		djeZo, dropky, voidstar, and agiz
>                    with help and contributions from
>            zawawa, pallas, Vorksholk, bitbandi, ocminer, and Genoil.
> =========================== www.nicehash.com =========================
> 
> Build time: 2018-02-13 09:03:15+01:00
> Build number: 450201690
> [2018-03-21 00:43:10.438233] [0x00007f8923830740] [info]    Log started
> 
> ...
> 
> [2018-03-21 00:43:10.821880] [0x00007f8923830740] [info]    core | Initialized!
> [2018-03-21 00:43:11.822097] [0x00007f891edcb700] [trace]   Executing: {"id":1,"method":"algorithm.add","params":["equihash","eu-01.miningrigrentals.com:3333","myusername:x"]}
> [2018-03-21 00:43:11.822177] [0x00007f891edcb700] [debug]   core | Command method: algorithm.add
> [2018-03-21 00:43:11.843379] [0x00007f891edcb700] [info]    net | Connecting to 188.166.37.58:3333 (eu-01.miningrigrentals.com)
> [2018-03-21 00:43:11.843533] [0x00007f891edcb700] [trace]   Response: {"algorithm_id":0,"id":1,"error":null}
> [2018-03-21 00:43:11.885682] [0x00007f891e5ca700] [info]    net | Connected!
> [2018-03-21 00:43:11.885728] [0x00007f891e5ca700] [debug]   net | Sending mining.subscribe message
> [2018-03-21 00:43:11.885745] [0x00007f891e5ca700] [trace]   net | Sending: {"id":1,"method":"mining.subscribe","params":["excavator/1.4.4a_nvidia","eu-01.miningrigrentals.com",3333,null]}
> [2018-03-21 00:43:11.885791] [0x00007f891e5ca700] [debug]   net | Sending mining.authorize message
> [2018-03-21 00:43:11.885812] [0x00007f891e5ca700] [trace]   net | Sending: {"id":2,"method":"mining.authorize","params":["myusername","x"]}
> [2018-03-21 00:43:11.885839] [0x00007f891e5ca700] [debug]   net | Sending mining.extranonce.subscribe message
> [2018-03-21 00:43:11.885857] [0x00007f891e5ca700] [trace]   net | Sending: {"id":3,"method":"mining.extranonce.subscribe","params":[]}
> [2018-03-21 00:43:11.992533] [0x00007f891edcb700] [trace]   net | Received: {"error": null, "id": 2, "result": true}
> [2018-03-21 00:43:11.992586] [0x00007f891edcb700] [info]    net | Authorized as myusername
> [2018-03-21 00:43:12.042581] [0x00007f891e5ca700] [trace]   net | Received: {"method": "client.reconnect", "id": 0, "error": null, "params": ["eu-01.miningrigrentals.com","52112"]}
> [2018-03-21 00:43:12.042778] [0x00007f891e5ca700] [warning] net | Net error: JSON member "error" not expected type: Array
> [2018-03-21 00:43:12.042886] [0x00007f891e5ca700] [info]    net | Connection lost! Reconnecting in 10 seconds

they have a workaround to specify the custom port, but will be nice to have this feature in excavator

**Comment by dropky** [comment]
client.reconnect is not supported for the security purposes.

**Comment by husanu** [comment]
> Note that for security purposes, clients may ignore such requests if the destination is not the same or similar.

https://en.bitcoin.it/wiki/Stratum_mining_protocol#client.reconnect

and they use same hostname
