### ISSUE TITLE
-p not working in 1.4.4

### ISSUE THREAD

**Issue by Angel996** [nicehash/excavator#222]
Upgraded from 1.3.7 to 1.4.4 (Ubuntu), found -p 0 CLI option not working. If I use -p with any number, I get the _Usage: /usr/bin/excavator-run_ prompt.

**Comment by dropky** [comment]
How exactly are you running excavator? Can you post here the command?

**Comment by Angel996** [comment]
This works:

`/usr/bin/excavator-run -u NICEHASH_BITCOIN_USERNAME -a equihash
`
This does not work:

`/usr/bin/excavator-run -u NICEHASH_BITCOIN_USERNAME -a equihash -p 0`

**Comment by borzaka** [comment]
> Default API bind port is 3456, but you can change it with '-p' command line parameter.

> HTTP API is disabled by default. You can enable it by configuring command line parameters.

https://github.com/nicehash/excavator/blob/f994250d4ed26fcf47d47715ad1dfdc27ad8ec37/README.md#cmdline

**Comment by nicehashdev** [comment]
Linux not supported currently. Closing.
