### ISSUE TITLE
Low Hash Rate

### ISSUE THREAD

**Issue by Luke240** [nicehash/excavator#23]
Running (4) GTX 1070's on Windows 10 using the excavator+web+restart_script.bat to test I'm only getting about 1.65 kH/s. Trying to figure out what I'm missing. I see all 4 cards in the web status window running at about 90% utilization connected to the US equihash server. Thanks in advance for the help.

**Comment by nicehashdev** [comment]
For max equihash performance, you need to set at least 2 workers per card.

**Comment by Luke240** [comment]
So running this in my default command file shows me two workers in the web interface but has them both running at about 840 H/s. Sorry if I'm missing something stupid. 

[
	{"time":1,"commands":[
		{"id":1,"method":"algorithm.add","params":["equihash","equihash.usa.nicehash.com:3357","BitcoinAddress.Wallet"]},
		{"id":2,"method":"algorithm.add","params":["equihash","equihash.usa.nicehash.com:3357","BitcoinAddress.Walle2"]}
	]},
	{"time":2,"commands":[
		{"id":1,"method":"worker.add","params":["0","0"]},
		{"id":1,"method":"worker.add","params":["0","1"]},
		{"id":1,"method":"worker.add","params":["0","2"]},
		{"id":1,"method":"worker.add","params":["0","3"]},
		{"id":1,"method":"worker.add","params":["1","0"]},
		{"id":1,"method":"worker.add","params":["1","1"]},
		{"id":1,"method":"worker.add","params":["1","2"]},
		{"id":1,"method":"worker.add","params":["1","3"]}
	]},
	{"time":5,"commands":[
		{"id":1,"method":"device.set.tdp","params":["0","75"]},
		{"id":1,"method":"device.set.core_delta","params":["0","50"]},
		{"id":1,"method":"device.set.memory_delta","params":["0","650"]},
		{"id":1,"method":"device.set.tdp","params":["1","75"]},
		{"id":1,"method":"device.set.core_delta","params":["1","50"]},
		{"id":1,"method":"device.set.memory_delta","params":["1","650"]},
		{"id":1,"method":"device.set.tdp","params":["2","75"]},
		{"id":1,"method":"device.set.core_delta","params":["2","50"]},
		{"id":1,"method":"device.set.memory_delta","params":["2","650"]},
		{"id":1,"method":"device.set.tdp","params":["3","75"]},
		{"id":1,"method":"device.set.core_delta","params":["3","50"]},
		{"id":1,"method":"device.set.memory_delta","params":["3","650"]}
	]},
	{"time":10,"commands":[
		{"id":1,"method":"worker.reset","params":["0"]},
		{"id":1,"method":"worker.reset","params":["1"]},
		{"id":1,"method":"worker.reset","params":["2"]},
		{"id":1,"method":"worker.reset","params":["3"]},
		{"id":1,"method":"worker.reset","params":["4"]},
		{"id":1,"method":"worker.reset","params":["5"]},
		{"id":1,"method":"worker.reset","params":["6"]}
	]},
	{"time":15,"loop":15,"commands":[
	  	{"id":1,"method":"algorithm.print.speeds","params":[]}
	]},
	{"event":"on_quit","commands":[
		{"id":1,"method":"device.set.tdp","params":["0","100"]},
		{"id":1,"method":"device.set.core_delta","params":["0","0"]},
		{"id":1,"method":"device.set.memory_delta","params":["0","0"]},
		{"id":1,"method":"device.set.tdp","params":["1","100"]},
		{"id":1,"method":"device.set.core_delta","params":["1","0"]},
		{"id":1,"method":"device.set.memory_delta","params":["1","0"]},
		{"id":1,"method":"device.set.tdp","params":["2","100"]},
		{"id":1,"method":"device.set.core_delta","params":["2","0"]},
		{"id":1,"method":"device.set.memory_delta","params":["2","0"]},
		{"id":1,"method":"device.set.tdp","params":["3","100"]},
		{"id":1,"method":"device.set.core_delta","params":["3","0"]},
		{"id":1,"method":"device.set.memory_delta","params":["3","0"]}
	]}
]

**Comment by nicehashdev** [comment]
You should only add one algorithm, then link device multiple times with worker add.
