### ISSUE TITLE
performance regression with 390.48 in Linux

### ISSUE THREAD

**Issue by aleqx** [nicehash/excavator#233]
I'm seeing visible and consistent performance drop in Linux after upgrading to 390.48, compared to 390.25 or 390.12. I'm using 1.4.4a on Neoscrypt with GTX 1080 Ti. Drop is about 2%. The default B,M params that I have been using are `M=3, B=1720`, which were working fine with the older drivers.

Thing is, this drop is only in Excavator. The other miners I use for other algorithms (ethash or equihash) are unaffected.

I installed and reinstalled those drivers many times.

Anyone else?

**Comment by nicehashdev** [comment]
Linux is not supported currently. Closing.
