### ISSUE TITLE
Changing the numbering of the GPU when one of the cards falls.

### ISSUE THREAD

**Issue by EvgeniyKorepov** [nicehash/excavator#234]
Changing the numbering of the GPU when one of the cards falls. After that effective management of GPUs of different types becomes impossible. What are the ways to get around this error?

P.S. The truth is this huge advantage is destroyed in API 1.5, now the perfect model - one copy of the Excavator on one farm with GPU of different types has remained in the past... Now only separate copies of the excavator for each type of GPU, different control ports and other inconveniences... :-(

**Comment by dropky** [comment]
Handling with devices hasn't changed with the new API, excavator lists the devices in the same order than CUDA. The issue that you're describing could be solved by adding an option to handle with the GPUs by their UUID or bus id. We'll think about it. 

I'm not sure that I understand the issue here. No changes that were made should affect excavator in a way that you would need to have a multiple copies of excavator for different GPUs. Can you give me an example?

**Comment by EvgeniyKorepov** [comment]
Here are some examples:
1. Different names of workers (and different bitcoin adsress) for different types of GPUs are now not possible 
2. Same algorithms, but different difficulty for different types of GPU is now not possible

Found another problem - I can not determine the state of connecting to the stratum server. Described in https://github.com/nicehash/excavator/tree/master/api#algorithm-list reply field "algorithms[i]/connected" now missing. 
A method https://github.com/nicehash/excavator/tree/master/api#subscribe-info in the "error" field only issues "Connecting." 
It would help a description of possible errors. Connection error, disconnection of the stratum during operation. In general, you can rely on this field to determine the errors of the stratum?

**Comment by dropky** [comment]
Hm.. I see. Unfortunately, with the new mining protocol different names for workers/btc addresses are not possible. How did you get different diffs for each type of GPU before? With multiple instances of the same algorithm? That's also not possible anymore.  Sorry. 

The connection state can be retrieved with subscribe.info method. If the connection is not yet established excavator will return "Connecting".  

>  In general, you can rely on this field to determine the errors of the stratum?


Yes, in case of the server side failure the error response field is the response that excavator gets from the stratum.

To monitor the algorithms you should check response field "algorithms[i]/got_job" (it will be true in case connection to server is established, the algorithm add was successful and excavator got the job).
