### ISSUE TITLE
Win 7 SP1

### ISSUE THREAD

**Issue by MichaelMiner** [nicehash/excavator#235]
It's painful to see how, a very good miner excavator, turned into a dead man!
No start excavator (1.50 and 1.51) on Win7 pro SP1

![no_start](https://user-images.githubusercontent.com/33788644/38269478-4d133e70-3789-11e8-8a6f-6f2f4da955ba.jpg)

**Comment by MichaelMiner** [comment]
And it was impossible to correct in 1,5,2a?

**Comment by EvgeniyKorepov** [comment]
I have everything working on one of the test benches. Perhaps there is not enough of a redistributive?

![image](https://user-images.githubusercontent.com/35364901/38977854-4211215e-43be-11e8-8eea-99fd4372ef67.png)

![image](https://user-images.githubusercontent.com/35364901/38977896-63de1ee0-43be-11e8-89ec-f7e4a09504bf.png)

**Comment by MichaelMiner** [comment]
1.4.4 and less work, but  1.5.0 1.5.1 1.5.2 not work

**Comment by nicehashdev** [comment]
Windows 7 is not supported, only Windows 10 64bit is supported.
