### ISSUE TITLE
Any way to alternative pool?

### ISSUE THREAD

**Issue by mayhem7** [nicehash/excavator#236]
So is there any way to change pool if excavator can't connect? like...
Connection lost, try to reconnect x times, if can't connect mine on other pool, after x time try again the previous time.

**Comment by dropky** [comment]
Excavator doesn't support backup pools. You could monitor the connection using the [subscribe.info](https://github.com/nicehash/excavator/tree/master/api#-subscribeinfo) method (in case of failing it will return a non-null error response field). Then call [unsubscribe](https://github.com/nicehash/excavator/tree/master/api#-unsubscribe) so excavator will stop trying to reconnect and [subscribe](https://github.com/nicehash/excavator/tree/master/api#-subscribe) with different stratum location.
