### ISSUE TITLE
0.000000 H/s after disconnect

### ISSUE THREAD

**Issue by borzaka** [nicehash/excavator#237]
This is not my issue, I just read on [Facebook](https://www.facebook.com/photo.php?fbid=10213539266974217&set=p.10213539266974217&type=3&theater) under the new NiceHash Miner release post, and copied here, hope it helps.

![image](https://user-images.githubusercontent.com/1230402/38376880-e775a7e8-38f9-11e8-8178-c94ce4a7fc01.png)
![image](https://user-images.githubusercontent.com/1230402/38376917-f53fcbba-38f9-11e8-9713-2fb069aa609e.png)

**Comment by dropky** [comment]
Thanks, but without log files there isn't much we can do. I'll see if I can get access to one of those. Thanks again for pointing it out.
