### ISSUE TITLE
GTX 1060 6GB vs 3GB

### ISSUE THREAD

**Issue by mayhem7** [nicehash/excavator#239]
I have 2 Gigabyte GTX 1060, the 6GB one shows fan RPM in the web but the 3GB one shows -1, is not supported or is a bug? thanks!

**Comment by dropky** [comment]
Can you run excavator with -d 0 parameter and config file (excavator.exe -d 0 -c config_file.json):

```
[
    {"time":2,"commands":[
        {"id":1,"method":"devices.get","params":[]}
    ]}
]
```

Please post the command line output here.

**Comment by mayhem7** [comment]
Problem fixed after restarting the OS, thanks for your time :)
