### ISSUE TITLE
Hard Restart When Connecting To Pool

### ISSUE THREAD

**Issue by g00tch** [nicehash/excavator#240]
I've come across a problem with mining.

I've been mining for months with my Gigabyte GTX 1060 3GB card without issues. About a week ago while mining Komodo on the equihash algo, my PC shut down instantly with a hard restart. It would then load Windows, but after 30 seconds to 1 minute, it would hard restart again, putting it in a constant restarting loop.

There were no error logs created which would tell me what was going on. The temps were fine, fan speeds were good, there were no indications of a problem, even though it's evident there is.

I uninstalled my gfx completely, and the restart loop stopped. I downloaded and installed the latest driver, and fired up Excavator again. The instant it connected to the pool, it hard restarted my PC again, and I was back to the above problem.

I've since tried using CCminer, Bminer, SGminer, etc, and all of them cause the hard restart. 

If I don't use a miner, everything is fine. I can game on high/ultra settings without issue. It's as if there's no problem at all, unless I try to mine.

I'm on Windows 10 Pro 64bit
Gigabyte GTX 1060 3GB
Intel Core i5-3470 CPU @ 3.20GHz
16GB RAM
700W PSU

**Comment by EvgeniyKorepov** [comment]
Most likely your problem is connected with degradation of the power unit. Try to temporarily replace the power supply and check the result.

**Comment by g00tch** [comment]
That was exactly the issue.

Thank you.
