### ISSUE TITLE
Titan V and Lyra2RE2

### ISSUE THREAD

**Issue by papacheal** [nicehash/excavator#242]
Were the optimizations introduced in 1.51 for Titan V/Lyra2RE2 just tweaks to the default tuning parameters or actual kernel-specific changes?

If they were just config tweaks, are we able to supply those same tuning parameters to the 1.4.4a Excavator release so we get the benefits on normal stratum vs. the new stratum protocol? The "T" parameter looks the same on the output so I'm not sure what else could be adjusted.

**Comment by dropky** [comment]
Were made kernel-specific changes in the code, so no, it cannot be applied to 1.4.x versions. You could try to increase the T parameter.
