### ISSUE TITLE
Getting "nhmp handshake: end of stream"

### ISSUE THREAD

**Issue by GotyMetal** [nicehash/excavator#243]
Just that' seems that can't connect to the pool with the 1.5.1 version, it shows that in the console again and again and i'm not able to connect.

**Comment by mayhem7** [comment]
Wait wait wait... why did that? why doesn't allow normal stratum servers???

**Comment by dropky** [comment]
@mayhem7 We implemented our own stratum protocol in order to reduce network traffic.

**Comment by mayhem7** [comment]
So... there's no way we can use any non-nicehash pool now...

**Comment by GotyMetal** [comment]
There must be anyway... i'm in love with excavator but if we can't mine other pools...

**Comment by dropky** [comment]
With the 1.5.0 version or higher only NH stratum is supported. You can still use older versions to mine on other pools, but they'll not be updated.

**Comment by EvgeniyKorepov** [comment]
@dropky And the protocol specifications will be published? Reverse-engineering protocol as I understand is not desirable? I could write a proxy, but I will not ;-)

**Comment by dropky** [comment]
As far as I know currently there is no plan to open source the new protocol. For the reason you mentioned ;)
