### ISSUE TITLE
1.5.2 removed algorithms Nist5 and CryptoNight

### ISSUE THREAD

**Issue by MichaelMiner** [nicehash/excavator#245]
Why?

**Comment by dropky** [comment]
Support for Nist5 and CryptoNight was dropped since both algorithms have been overtaken by ASICs. You can see how the Nist5 hashing speed increased:
![capture](https://user-images.githubusercontent.com/10920195/38915933-d26d4752-42e5-11e8-9f95-e74fc5883eb5.PNG)

**Comment by EvgeniyKorepov** [comment]
@MichaelMiner At the GPU, they are unprofitable:
![image](https://user-images.githubusercontent.com/35364901/38922340-a09fdd96-4300-11e8-888e-9e83343bc041.png)

**Comment by dropky** [comment]
@EvgeniyKorepov Looking at your screenshot, maybe we should remove sia and lbry as well :/

**Comment by EvgeniyKorepov** [comment]
@dropky Then add more algorithms. And then soon nothing will remain ;-)

**Comment by dropky** [comment]
Will do ;)
