### ISSUE TITLE
API http server keep alive?

### ISSUE THREAD

**Issue by EvgeniyKorepov** [nicehash/excavator#248]
Is it possible to support for Kepe Alive in the http server?
Now for each request a new connection is created, if I'm not mistaken?

**Comment by dropky** [comment]
> Now for each request a new connection is created, if I'm not mistaken?

You're right. 

> Is it possible to support for Kepe Alive in the http server?

Currently is not possible (when using http).

**Comment by nicehashdev** [comment]
We will not support this as we believe it is not needed. Keep alive feature is needed for high traffic servers, excavator is not high traffic server. Closing.
