### ISSUE TITLE
lyra2rev2 bug in version 1.4.4

### ISSUE THREAD

**Issue by borzaka** [nicehash/excavator#254]
I just saw the 1.5.4 release note:
> fixed lyra2rev2 bug that was causing lower pool speed on some pools

I know it's a favor, but can you guys fix the lyra2rev2 bug in version 1.4.4 as well? It's the last version that can be used not only on Nicehash pools, and it's still rocks!

Thank you in advance.

**Comment by dropky** [comment]
Sorry, but we dropped support for older versions of excavator.

**Comment by borzaka** [comment]
Worth a try, thanks!
