### ISSUE TITLE
Scrolling Excavator window gives rejected shares

### ISSUE THREAD

**Issue by borzaka** [nicehash/excavator#255]
Basic info:
- NiceHash Miner v2.0.2.4 Beta
- Excavator Version 1.5.4 alpha NVIDIA

How to reproducate:
- mining for a long time so you can scroll back far
- grab and hold the scrollbar, scroll up - hold it and scroll for a while - the long you scroll more the rejected shares are
- when you release the scrollbar you should see some rejected shares
- I don't know what other algo does this as well, but daggerhashimoto does

![image](https://user-images.githubusercontent.com/1230402/40907232-7ab2ca82-67e3-11e8-8638-a546dc9607e0.png)

A done again; when I released the scrollbar handle, it scrolls down, and I was seeing this:
![image](https://user-images.githubusercontent.com/1230402/40907519-6a825b4a-67e4-11e8-9cc4-cd9d790307fd.png)

**No shares accepted during the scrolling.**

**Comment by dropky** [comment]
I'll take a look, thanks for pointing it out. My first guess would be this are some stale/old shares that somehow got stuck in the thread that's writing to the command line.

**Comment by EvgeniyKorepov** [comment]
@dropky I also noticed similar problems. 
It seems that some of the important code is executed in the main thread, or part of the exchange between the threads passes through the main thread.
If I'm not mistaken, the main thread of the console application stops when scrolling, pasting / copying, dragging the window?, resizing the window?.

**Comment by nicehashdev** [comment]
This is something we will not fix - it happens because threads get blocked and shares are not submitted then. Do not scroll. Suggest using API to get information about mining. Closing.
