### ISSUE TITLE
can't get http api to work

### ISSUE THREAD

**Issue by albgz** [nicehash/excavator#256]
Hi! I'm using Excavator v1.5.4a_nvidia and I can't seem to get the remote api to work. I'm currently starting the miner with 
`
excavator -c lyra.json -wp 4000 -wi 0.0.0.0
`
Calling curl -g http://0.0.0.0:4000/api?command={"id":1,"method":"info","params":[]} I get the following error (I have 3 gpus):
```

{"id":0,"error":"Invalid JSON message."}{"id":0,"error":"Invalid JSON message."}{"id":0,"error":"Invalid JSON message."}
```

Any suggestions?

**Comment by S74nk0** [comment]
@albgz 
Try it like this maybe: `curl -H "Accept: application/json" -H "{\"id\":1,\"method\":\"device.list\",\"params\":[]}" --request GET IP:port`

The JSON string in bash can be `'{"id":1,"method":"device.list","params":[]}'` but this one  seems to fail in command prompt or power-shell so the previous example is using the escaped quotes (`\"`)

**Comment by igorvoltaic** [comment]
@albgz 
for your poor & address
`excavator -c lyra.json -wp 4000 -wi 0.0.0.0`
 do it like this:
`curl -g 'http://0.0.0.0:4000/api?command={"id":1,"method":"info","params":[]}'`

**Comment by nicehashdev** [comment]
This works. Closing.
