### ISSUE TITLE
Feature request: count and display errors per algo (and maybe per worker)

### ISSUE THREAD

**Issue by borzaka** [nicehash/excavator#257]
Count errors (by type) per algo/worker and display these statistics to the window.

Distinguish and count errors:
- rejected share (low difficulty, job not found, share above target, etc.)
- invalid share
- invalid result
- etc.

... per algo, per worker

With this feature we would know:
- which card is having issues (!)
- how many rejected/invalid shares there are - we could determine is it ok, or too much: need checking, etc.
- nice statistics :)

Thx in advance.

**Comment by dropky** [comment]
Currently, you can get number of accepted and rejected shares for each algorithm from [algorithm.list](https://github.com/nicehash/excavator/tree/master/api#-algorithmlist) method. We could distinguish them by type of error, not a problem. But to get statistics per worker, that's a little more complicated.

**Comment by borzaka** [comment]
I see, so the data is there. Then displaying these errors statistics (`accepted_shares`/`rejected_shares`) to the window time to time would be nice.

**Comment by nicehashdev** [comment]
This is already done. Call devices.get to get information about hw err count. Closing.
