### ISSUE TITLE
Add optional API password

### ISSUE THREAD

**Issue by Kayfolom** [nicehash/excavator#26]
Add optional API password (Security token).
I think that the Excavator has a great future, but we need to take care of safety now. Otherwise, it is very easy for an attacker to scan the ports, find the port of the excavator and reconfigure the mining for himself.

example:
excavator.exe -wi 0.0.0.0 -wp 38080 -apipassword c4rc34rcq34
excavator.exe -i 0.0.0.0 -p 38080 -apipassword c4rc34rcq34
for request
{"id":1, "password": "c4rc34rcq34", "method":"device.list","params":[]}

**Comment by nicehashdev** [comment]
There is already API authorization token, read more here: https://github.com/nicehash/excavator/tree/master/api

**Comment by Kayfolom** [comment]
It's fine! It's a good idea to pass a token in the http header. I apologize for not reading the documentation carefully!
