### ISSUE TITLE
Equihash sometimes goes to a zero hash rate

### ISSUE THREAD

**Issue by teckel12** [nicehash/excavator#260]
Running v1.5.4a on a 750 Ti mining Equihash.  Sometimes, the hash rate goes to zero and stays there.  This doesn't trigger a warning and doesn't restart.  It just stays at zero till I notice.  I restart mining and it all works again, until the next time.

Two things.  First, something must be wrong for it to go to a zero hash rate.  Secondly, if the hash rate is zero for a certain amount of time, it would probably be a good idea to restart automatically.

Thanks!

**Comment by dropky** [comment]
With what M parameter are you running equihash? Default one? You can read the mode from the cmd window. 
![capture](https://user-images.githubusercontent.com/10920195/41356181-9c8db7d8-6f23-11e8-866b-c3f8e5a138a0.PNG)

Also, excavator logs would be a big help. Run excavator with -f 0 flag to enable file logging.

**Comment by teckel12** [comment]
@dropky `M=1`

Excavator is running via Nicehash, so I'm not sure how to run it with a flag.  That's why I came here to begin with, to find out how to send parameters to Excavator and if there was a parameter for minimum hash rate (like with Claymore miners).

Thanks again.

**Comment by teckel12** [comment]
Done and running.  When it started I noticed the `-f 0` in the startup command line.  The `archived_logs` folder was created, but at this time there's no log files contained within.

I'll keep an eye on it and when it fails I'll post the log file here.

**Comment by teckel12** [comment]
Here's my log file from a failure already:

[logs.zip](https://github.com/nicehash/excavator/files/2102897/logs.zip)

I cycled power before restarting just in case it was something like that.  I've also been running on this box for a couple months without any issues till the last few days.  I can't say that it was linked to any kind of update or anything else.  This box isn't used for anything else, it's just an extra PC I had laying around.  Finally, I changed my NiceHash hash in the log file as I wasn't sure if that was private or not.

Let me know what you see and thanks again.

**Comment by dropky** [comment]
I went over the log file and the reason for equihash speed dropping to zero is because miner.stop method is called. Please check if you enabled the minimum income option in NiceHash Miner, under configuration? If you have then probably the profitability is lower than the one provided with minimum income and consequently the miner has stopped mining. 

![capture](https://user-images.githubusercontent.com/10920195/41454672-91d6e654-707a-11e8-9e8d-66d95050e66e.PNG)

Let me know if that's the case.

**Comment by teckel12** [comment]
@dropky That's odd because it was still mining CryptoNightV7.  And NiceHash wasn't saying that it wasn't mining due to being below the minimum income level.  Also, when I would restart, it was over the minimum.

I changed the minimum to 0 and it hasn't stopped since.  But, it seems there's some kind of problem with the minimum code.  Is the minimum for each miner or each device or total?  As there's only one minimum, I assumed it was for all combined.

**Comment by dropky** [comment]
Minimum income is for all devices combined. Your problem might be related to the recent problems that we had with exchange rates and profit calculations. Anyway.. I'm closing this issue since it works now.

**Comment by teckel12** [comment]
Sounds good.
