### ISSUE TITLE
Request for information: Minimum memory requirement

### ISSUE THREAD

**Issue by UselessGuru** [nicehash/excavator#262]
Could you please document the minimum memory requirements (RAM & graphics card mem) for each supported algorithm? This for single and multiple worker configurations.

Thank you very much!

**Comment by dropky** [comment]
Will do. Hopefully next week. Any specific card you're interested in? Because for some algorithms amount of memory needed is different for each card.

**Comment by UselessGuru** [comment]
I am developing a miner file for MultiPoolMiner. It will run on basically any NVIDIA cards, so so we should cover the most current card generations.

> Because for some algorithms amount of memory needed is different for each card.
Is there a way to calculate the amount from the amount of installed memory?

**Comment by dropky** [comment]
I wouldn't recommend running two workers per device, it won't gain that much more performance, but it will cause more instability. Some algorithms will even crash, like lyra2rev2, and as you said yes, the amount of needed memory will double. All algorithms are tuned and tested for most of the NVIDIA cards, so there shouldn't be any problem related to not enough GPU memory. 

Also.. You can always check how much GPU memory is each algorithm using with [device.get](https://github.com/nicehash/excavator/tree/master/api#-deviceget) method. Check the gpu_memory_used field.

**Comment by nicehashdev** [comment]
Only Daggerhashimoto is supported for cards with 6+ GB of memory. Closing.
