### ISSUE TITLE
Nice Hash Miner 2 Excavator Server start takes forever

### ISSUE THREAD

**Issue by armzBTC** [nicehash/excavator#263]
Hi everyone,
so I just started mining (not bc of profit but im very intrested in mining crypto currencies) with Nice Hash Miner 2 and it worked just fine. After a time I noticed that I can include my  "Graphics-Card" by installing an NVIDIA-Driver. After that, when It tries to start its stuck on "Starting Excavator Server". Well, there was already a conversation anout this, but unfortunatelly there was no solution for my problem. I already tried reinstalling because I thought it might have something to do with uncomplete libraries but that didnt help either. I also checked the Files in the folder manually, it was complete. I dont know what to try next since Im a beginner. Does anyone else has a simular problem?
Thank you very much in advance,
~Vince from Germany

**Comment by dropky** [comment]
Hi @armzBTC, check if excavator.exe is located at `C:\Users\username\AppData\Roaming\nhm2\bin\excavator_server` directory. If it's missing from there, then probably your antivirus deleted it and you'll have to manually download it from github. If you can see excavator.exe, try double clicking on it and tell me what you see (you should see cmd window and the list of your devices).

**Comment by armzBTC** [comment]
Thanks for the quick response!
You are right, theres no "excavator.exe"file. I didnt notice that it was missing at first.
But the location of the excavator_server folder is correct.
Where can I download it? (Im running win8 64bit)

**Comment by dropky** [comment]
You can download it from here: https://github.com/nicehash/excavator/releases/tag/v1.5.5a. Make sure to download the correct file - excavator_v1.5.5a_NVIDIA_Win64.zip. Copy the content of the zip file into excavator_server folder (you should have excavator.exe inside excavator_server directory).

**Comment by armzBTC** [comment]
@dropky I downloaded it and moved it into the folder and it stayed in there until I started nhm2, it seems to be deleted if someone tries to execute it, but I didnt tested starting it manually, so thats what Im going to try next I think.

**Comment by armzBTC** [comment]
Oh, I see. I dont have enough "System Recources", does that mean my Computer is not strong enough? And if yes, then why could I run it before?

**Comment by dropky** [comment]
@armzBTC can you take a screenshot of the error and post it here?

**Comment by armzBTC** [comment]
![err](https://user-images.githubusercontent.com/40492432/41800928-01560c8c-7678-11e8-94b9-deecbe804628.PNG)

It says I dont have enough "System Recources to execute the service", I guess this means RAM, but otherwise Im far under 100%, at least this is what the Task Manager shows me. Im gonna try some restarts.

**Comment by armzBTC** [comment]
Now I see this Error more often and this really seems to be because of the RAM, I tried cleaning it but no result... Do you have any ideas?

**Comment by armzBTC** [comment]
"Insufficient system resources exist to complete the requested service"
thats what it is in English.

**Comment by dropky** [comment]
Unfortunately, I haven't seen this error before (also no other user reported it). It looks like a windows issue though, try googling for possible solutions. This might help: https://answers.microsoft.com/en-us/windows/forum/windows_10-files-winpc/insufficient-system-resources-exist-to-complete/7e25e005-f01d-40aa-b5ba-9c1ba44568c7

**Comment by dropky** [comment]
You could try one more thing. Try running excavator from the download folder (not from the nhm2/bin/excavator_server). Do you get the same error?

**Comment by Libayi** [comment]
Sorry for my bad English. I have same issue, but when i use excavator v. 1.5.4a/1.5.5a, My Nicehash stack on excavator server, but when i use excavator v. 1.3.9a nicehash not stack BUT always fail on test benchmark.
Please someone help me.

**Comment by dropky** [comment]
@Libayi 1.3.9a version fails on benchmark because it's an older version with an old API. Only 1.5.x will work with NiceHash Miner. Try double clicking on 1.5.5a version of excavator, does it start normally or do you see any issues?

**Comment by nicehashdev** [comment]
Deprecated. Closing.
