### ISSUE TITLE
Change logging levels

### ISSUE THREAD

**Issue by UselessGuru** [nicehash/excavator#264]
Log level "-d 2" displays too much information
Log level "-d 3" displays too little 
:-)
I am looking for a way to suppress these messages, but keep all non-yellow messages from "-d 2"

![image](https://user-images.githubusercontent.com/30080938/41778707-d9f8a94e-762f-11e8-9b6a-3693aeae0174.png)

**Comment by nicehashdev** [comment]
We have no intentions of changing this for now. Closing.
