### ISSUE TITLE
Excavator 1.5.9a + NHM 2.0.2.5 ?

### ISSUE THREAD

**Issue by niknewb** [nicehash/excavator#269]
Are they compatible with each other? Can I update excavator to the latest version to use it with NHM2?

**Comment by dropky** [comment]
Yes, it's compatible, but make sure to disable sia, lbry and daggerhashimoto_sia algorithms, since they were removed from the excavator. Also don't forget to re-benchmark lyra2z - this version includes some speed optimisations.
