### ISSUE TITLE
nhmp resolve no such host in known 

### ISSUE THREAD

**Issue by niknewb** [nicehash/excavator#271]
I'm getting nhmp resolve and nhmp connect issues on 1 mining rig. This is very strange because everything worked fine and nothing changed for ages, even the second mining rig standing nearby with same connection type to the same router is working fine and this exact rig can't mine for 6+ hours atm. I have already done router+rig reboot, also did factory reset on router= no effect. Any suggestions? I'm using latest excavator and latest nhm2 miner(also tried reinstalling them as well).
EDIT. Okay, now every single one of my rigs is down, I guess it is nicehash server related problems.

**Comment by dkozlov** [comment]
try nhmp.in.nicehash.com or nhmp.br.nicehash.com

**Comment by borzaka** [comment]
NiceHash servers were under DDoS attacks. Now they should work in every location.

NiceHash service status:
https://status.nicehash.com/

**Comment by dropky** [comment]
As @borzaka said.
