### ISSUE TITLE
End of file and end of stream warnings

### ISSUE THREAD

**Issue by borzaka** [nicehash/excavator#274]
[log.txt](https://github.com/nicehash/excavator/files/2293344/log.txt)

![excavator_end_of_file_1105](https://user-images.githubusercontent.com/1230402/44203418-1dd84080-a14f-11e8-89b7-d9e61f95cecc.png)

![excavator_daggerhasimoto_1110](https://user-images.githubusercontent.com/1230402/44203422-216bc780-a14f-11e8-9e35-d37a4f721c54.png)

![excavator_daggerhasimoto_end_of_stream_1123](https://user-images.githubusercontent.com/1230402/44203424-2466b800-a14f-11e8-8bcb-8652db2d603a.png)

![excavator_end_of_stream_1150](https://user-images.githubusercontent.com/1230402/44203432-2892d580-a14f-11e8-9696-30fcf408a760.png)

**Comment by josemanblan** [comment]
I have same problem!

**Comment by dropky** [comment]
Is this still going on? We were under constant DDOS attack in the past two weeks. All problems regarding the nhmp connection were probably related to that.

**Comment by borzaka** [comment]
No, I haven't seen this since then.
