### ISSUE TITLE
RTX 2080ti CUDA error DRIVER: '300'

### ISSUE THREAD

**Issue by Sixthdim** [nicehash/excavator#275]
I am trying out my new 2080ti's and I'm getting the following error during the benchmark:
`CUDA error DRIVER: '300' in func 'kernel_launcher::kernel_launcher' line 332`
NiceHash is now also rerunning the benchmark every time I start mining. I am running nVidia driver version 416.34. I have an SLI bridge connected, but SLI is disabled. Here is a video screenshot (sorry for the potato quality). Any thoughts?

![cuda-error-300](https://user-images.githubusercontent.com/2130552/47892762-89b17780-de27-11e8-91ad-6700256e4740.PNG)

**Comment by dropky** [comment]
You should use Excavator CUDA 10 build. Download it from here - https://github.com/nicehash/excavator/releases and replace the excavator.exe used in NiceHash Miner.

**Comment by Sixthdim** [comment]
Finally got a chance to try the CUDA 10 build, and it fixed my issue. Thanks!
