### ISSUE TITLE
When Grin Cuckaroo29?

### ISSUE THREAD

**Issue by salighie** [nicehash/excavator#278]
Any plans to add Grin Cuckaroo29 to excavator?

Got some NVIDIA 1070Tis that would love to mine it.

**Comment by dropky** [comment]
Unfortunately, we terminated the development of Excavator.

**Comment by salighie** [comment]
is there an official announcement? any recommendations from NH on how to continue to mine on NH?

is it all moving to NHLM platform?

sorry if i missed it, have been out of the loop - have been mining Daggerhashimoto for a while. 

even recently downloaded last release 1.5.15 dated Jan 14th - didn't see any announcement or recommendations.  

would appreciate it if you could point me in the right direction.

thanks

**Comment by dropky** [comment]
There was an official announcement couple of days ago - https://www.nicehash.com/news/nhmv2-discontinued-nhml-is-twice-as-profitable.

Yes, it is recommended to use NHML. NHML uses all the latest 3rd party miners so it's more profitable than Excavator + NHM2.
