### ISSUE TITLE
 GPU1 CUDA error in CudaProgram.cu:456 : unknown error (999)

### ISSUE THREAD

**Issue by MustyTang** [nicehash/excavator#283]
I'm using a GTX 980TI and keep getting this error I have tried two miners and it is the same problem
[log20200325_141129.txt](https://github.com/nicehash/excavator/files/4383039/log20200325_141129.txt)

**Comment by nicehashdev** [comment]
Maxwell cards not supported anymore. Closing.

**Comment by wjd000** [comment]
I'm using RTX 2070super and getting the same error.
CUDA error in CudaProgram.cu:465 : unknown error (999)
CUDA error in CudaProgram.cu:267 : unknown error (999)
GPU1 search error: unknown error
Fatal error detected. Restarting.

**Comment by jbmanwell** [comment]
Not to be a jerk but that's extremely unhelpful, @nicehashdev. So it _did_ work, but now it doesn't... No explanation of why something that _did_ work, now _doesn't_? No suggestions of using a previous version?.. No workarounds... nothing.  

Thanks for confirming shit doesn't work, which is to say, thanks for nothing. Hopefully, you're not getting paid for such excellent customer service.
