### ISSUE TITLE
No compatible devices

### ISSUE THREAD

**Issue by acos0874** [nicehash/excavator#285]
Hi, I'm trying to launch this from desktop and I get this error...

![image](https://user-images.githubusercontent.com/42582444/104220024-d006b600-5436-11eb-8ed3-136016f2a3e9.png)

This is on a 2070 super.

**Comment by nicehashdev** [comment]
What is your driver version?

**Comment by acos0874** [comment]
442.19

**Comment by nicehashdev** [comment]
That is unfortunately too old driver. If you wish to use Excavator, you will have to update your NVIDIA driver to at least 450.xx (or perhaps higher ver).
