### ISSUE TITLE
How to edit commands when running NiceHash Miner?

### ISSUE THREAD

**Issue by kugaevsky** [nicehash/excavator#288]
`cmd_1.json` resets and drops any changes when Excavator starts from Nicehash application. How could I apply all my API commands without using HTTP API?

**Comment by nicehashdev** [comment]
Unfortunately you cannot adjust commands NHM is giving  Excavator (yet). I suggest you open this ticket in NHM repo.

Alternatively, if you restrict yourself to daggerhashimoto mining only, you may try out following experimental wrapper: https://github.com/nicehash/excavator/tree/master/experimental

It has watchdog (restarts Excavator if it crashes...) and Windows autostart service. Additionally, you may apply overclocks and no 3rd party tool is needed to take care of it. It is a pretty solid mining solution that takes care of everything.

**Comment by kugaevsky** [comment]
Thanks for the great advice, but I've solved this issue another way. Probably someone will find it useful. 

I've put the file with custom commands to Excavator directory in Nicehash plugins and added custom arguments to `Extra launch parameters` in `Benchmark` tab of Nicehash application. With `-c commands.json -wp 18000` parameters Excavator started from Nicehash loads my OC profile and perfectly tunes with `octune.html`.

**Comment by kugaevsky** [comment]
I believe that moving custom command-line arguments for miners/plugins to a more obvious place will make Nicehash UI more user friendly.

**Comment by nicehashdev** [comment]
Okay great! I will leave this issue open for others, if anyone wants to do the same.

**Comment by ben1628** [comment]
> -c commands.json -wp 18000 <

How does your commands.json looks like?

{"time":10,"commands":[
		{"id":1,"method":"device.set.oc_profile","params":["0","-150","1300","130","50"]},
		{"id":1,"method":"worker.reset","params":["0"]}
	]}

Try to add this but I cannot get passed


=========================== www.nicehash.com =========================
           Excavator v1.6.2a GPU Miner for NiceHash.
           Copyright (C) 2021 NiceHash. All rights reserved.
=========================== www.nicehash.com =========================

Build number: 514
Provided startup commandline: -p 4000 -c cmd_1.json -m -qx -c commands.json

[16:50:19][0x00001c18][info] Log started, build v514
[16:50:19][0x00001c18][info] core | Found (0) CUDA device: GeForce RTX 3060 Ti
[16:50:19][0x00001c18][info] api | Listening on 127.0.0.1:4000
[16:50:19][0x00001c18][info] core | Initialized!

**Comment by ben1628** [comment]
okay, looks like I can generate the commands.json from the octune.html.

**Comment by ben1628** [comment]
still get a problem, when I add -c command.json, it just freeze at core initialized.
