### ISSUE TITLE
Add a second parameter to accept a second commands.json

### ISSUE THREAD

**Issue by goofygrin** [nicehash/excavator#290]
Most of us likely are running excavator in Hicehash GUI and it is dynamically creating a cmd_x.json at run time.  We can specify additional parameters in the UI of Nicehash, but we can't override the command file.

It would be nice to be able to add a runtime parameter (say "-ac" - additional commands) to allow us to add additional commands to excavator.

For me this is important because I need to have Excavator manage my overclocking settings due to the DAG cache generation bug.

**Comment by nicehashdev** [comment]
The last specified command file (-c) will be parsed. Someone has already found a nice solution: https://github.com/nicehash/excavator/issues/288

Closing duplicate issue.

**Comment by goofygrin** [comment]
Thanks!  Didn't even think to try that.
