### ISSUE TITLE
0Mh/s with Excavator?

### ISSUE THREAD

**Issue by goofygrin** [nicehash/excavator#291]
I had Excavator running well on my GTX 1660 for a few days.  I replaced my motherboard and CPU and it was working fine.  After an hour or so, the hash rate dropped from ~26.5Mh/s to ~20Mh/s.  I stopped and restarted Excavator and now it continuously is 0Mh/s.

I ran excavator from the command line at log level 0 (so I got all logs) and there were no errors reported or anything.

I turned off Excavator and am running with Phoenix with no issues for the last 12 hours.

How can I help you debug this?

**Comment by nicehashdev** [comment]
Submit logs that were generated with -f 0 please. Also comment out your private data (such as your BTC address).

**Comment by goofygrin** [comment]
[log.log](https://github.com/nicehash/excavator/files/5837326/log.log)

Stripped my address & GPU guid.

Interesting that the efficiency is showing 50% of what I set in the config (35W vs 70W).  Watching in performance monitor, 4GB of the video memory was in use and CUDA utilization was 100%.

**Comment by nicehashdev** [comment]
It looks like the only problem you have is that you are calling worker.reset before worker.print.efficiencies. When you call worker.reset, speeds are set to 0 so then, when you try to obtain speed, it will be 0, because nothing was measured in between. You need to give it some time. It is better to measure speed first and then reset it.

**Comment by goofygrin** [comment]
Thanks... here's my relevant section of the commands.json.  This doesn't jibe with what you're describing.  Also note that this happened with the generated cmd_#.json that the nicehash GUI generates.  If you look [here on line 107](https://github.com/nicehash/NiceHashMiner/blob/master/src/Miners/Excavator/Excavator.cs) you can see the template they're generating.

```
{"time":15,"loop":30,"commands":[
	{"id":1,"method":"worker.print.efficiencies","params":[]},
	{"id":2,"method":"worker.reset","params":["0"]}
]}
```

**Comment by nicehashdev** [comment]
Yes, the commands above are OK, because worker.print.efficiencies is executed BEFORE worker.reset.

**Comment by nicehashdev** [comment]
Is there anything else? Otherwise, I am closing this.
