### ISSUE TITLE
No description of API methods

### ISSUE THREAD

**Issue by EvgeniyKorepov** [nicehash/excavator#292]
No description of API methods

device.set.oc_profile | Sets overclocking profile 
https://github.com/nicehash/excavator/tree/master/api#device-set-oc-reset

device.set.oc_reset | Resets overclocking profile.
https://github.com/nicehash/excavator/tree/master/api#device-set-oc-reset

**Comment by nicehashdev** [comment]
I was kinda busy.. will try to get this sorted now.

**Comment by nicehashdev** [comment]
Here done. I know there are some other API methods needing description, but I am so busy lately, so I am sorry for that.
