### ISSUE TITLE
Job not found issue when click on the scroll bar or scrolling up in the log window

### ISSUE THREAD

**Issue by Bronsens** [nicehash/excavator#293]
I found a bug if you scroll up on the log window for some reason it acts as if the miner has been paused until you click somewhere else in the window. then it says job not found and gives a bunch of doesn't happen in any other miner.

I can reproduce it at anytime if you need me to submit screenshots.

**Comment by Bronsens** [comment]
![image](https://user-images.githubusercontent.com/29926234/107007749-f3d0c980-6760-11eb-85e3-1ee24c302d94.png)

**Comment by nicehashdev** [comment]
This is an old well known bug. There are no plans to fix this for now as it would involve too much changes (basically, whole logging system would need its own thread). If you want to check the history, I suggest turning on file logging and searching in files.
