### ISSUE TITLE
API HTTP answer error?

### ISSUE THREAD

**Issue by EvgeniyKorepov** [nicehash/excavator#294]
I get WINHTTP error 12152 when I try to access the API via HTTP WinAPI - ERROR_WINHTTP_INVALID_SERVER_RESPONSE 12152 The server response cannot be parsed.

I suspect that the error appears due to an incorrect header given by the excavator:

![image](https://user-images.githubusercontent.com/35364901/107157726-d8e79a80-6996-11eb-8776-351664ba5c02.png)

```
HTTP/1.0 200 OK
Content-Length: 21
Content-Type: application/json
Pragma: no-cache
Cache-Control: no-cache
Expires: 0
Excavator-Version: 1.6.2b
Access-Control-Allow-Origin: *
Access-Control-Allow-Methods: POST, GET, DELETE, PUT, PATCH
x-request-id,x-user-agent: 

{"id":1,"error":null}
```

**Comment by nicehashdev** [comment]
You are right. Thanks. Will be fixed in next version.

**Comment by nicehashdev** [comment]
Fixed.
