### ISSUE TITLE
Memory temperature issues in 3080/3090 - Great idea, who will check first? )

### ISSUE THREAD

**Issue by EvgeniyKorepov** [nicehash/excavator#295]
Speculation: Memory temperature issues in 3080/3090 are increased by physically contiguous DAG file loading in GDDR6X chips, distributing the DAG file would give thermal improvements

https://github.com/trexminer/T-Rex/issues/187

**Comment by nicehashdev** [comment]
As far as I know, on the physical level, memory is striped over all chips - this is how faster bandwidth is achieved.

Implementing any kind of spacings could actually create reverse effect - getting certain memory chips hotter.

**Comment by EvgeniyKorepov** [comment]
It's a pity if so (And then you have to mine like this for 3090)))
![image](https://user-images.githubusercontent.com/35364901/107415940-f3e81500-6b24-11eb-9b55-e3b29e11685b.png)

**Comment by nicehashdev** [comment]
Closing as this idea is not going to work.
