### ISSUE TITLE
add command file freeze at initialization

### ISSUE THREAD

**Issue by ben1628** [nicehash/excavator#296]
As suggested by others, I use OCTune to tune and create a commands.json file, I tried to use that by adding

-c commands.json as the extra lunch in NiceHash Miner's Benchmark, so when run excavator, I get this

========================== www.nicehash.com =========================
           Excavator v1.6.2a GPU Miner for NiceHash.
           Copyright (C) 2021 NiceHash. All rights reserved.
=========================== www.nicehash.com =========================

Build time: 2021-01-18 00:08:50
Build number: 514
Provided startup commandline: -p 4000 -c cmd_1.json -m -qx -c commands.json

[12:46:33][0x00000bbc][info] Log started, build v514
[12:46:33][0x00000bbc][info] core | Found (0) CUDA device: GeForce RTX 3060 Ti
[12:46:33][0x00000bbc][info] api | Listening on 127.0.0.1:4000
[12:46:33][0x00000bbc][info] core | Initialized!

and then it just stuck here.  Do I have to have admin right to RTX 3060 Ti, if so, how do I do that?

**Comment by nicehashdev** [comment]
What exactly would you like to achieve? 

I suggest you to simply use NiceHash QuickMiner: https://github.com/nicehash/NiceHashQuickMiner

With latest version(s) it is becoming very powerful and decent mining tool.
