### ISSUE TITLE
Need to set overclocks after you start the miner and the dag is loaded. 

### ISSUE THREAD

**Issue by ben1628** [nicehash/excavator#297]
Need to set overclocks after you start the miner and the dag is loaded. T-Rex fixed that, phoenix no, and excavator NO.

Hopefully this get fixed soon, I'm forced to use T-Rex for now.

**Comment by nicehashdev** [comment]
Excavator sets memory OC to 0 for the time DAG is generated, but it needs to be launched with elevated privileges to be able to do that (run as administrator).
