### ISSUE TITLE
API commands

### ISSUE THREAD

**Issue by Kayfolom** [nicehash/excavator#3]
Add UPTIME to the excavator API.
This is a indicator that allows you to determine how long the miner works without crashing or rebooting.

It is good to have a command SUMMARY - Output of all information in one JSON
for example:
`{
	"devices": [{
		"device_id": 0,
		"name": "GeForce GTX 1080 Ti",
		"gpgpu_type": 1,
		"details": {
			"cuda_id": 0,
			"sm_major": 6,
			"sm_minor": 1,
			"bus_id": 7
		},
		"more_detail": {
			"id": 1,
			"error": null,
			"device_id": 0,
			"name": "GeForce GTX 1080 Ti",
			"gpgpu_type": 1,
			"details": {
				"cuda_id": 0,
				"sm_major": 6,
				"sm_minor": 1,
				"bus_id": 7
			},
			"uuid": "GPU-238aa18d-b50f-05b9-3c56-d8c9f1e0d8bd",
			"gpu_temp": 82,
			"gpu_load": 100,
			"gpu_load_memctrl": 77,
			"gpu_power_usage": 292.1730041503906,
			"gpu_power_limit_current": 300.0,
			"gpu_power_limit_min": 125.0,
			"gpu_power_limit_max": 300.0,
			"gpu_tdp_current": 120.0,
			"gpu_clock_core_max": 2075,
			"gpu_clock_memory": 5705,
			"gpu_fan_speed": 75,
			"gpu_fan_speed_rpm": 2869
		}
	}],
	"algorithms": [{
		"algorithm_id": 0,
		"name": "equihash",
		"connected": true,
		"got_job": true,
		"address": "zen.suprnova.cc:3618",
		"login": "Kayfolom.node10:x",
		"workers": [{
			"worker_id": 0,
			"device_id": 0,
			"params": [],
			"speed": 356.15
		}, {
			"worker_id": 1,
			"device_id": 0,
			"params": [],
			"speed": 354.01
		}]
	}]
}`

**Comment by nicehashdev** [comment]
Uptime is already reported, check here: https://github.com/nicehash/excavator/tree/master/api#info

With next release, we are also adding some system info such as CPU and RAM load.
