### ISSUE TITLE
Amd fan error

### ISSUE THREAD

**Issue by V3T3RaN** [nicehash/excavator#30]
My rig: 2x480, 2x1070. Mine only 1070s on Excavator.
If do NOT disable AMD support(-na), amd fans reset to 0% and dont changes to other value. 

P.S. And phymem.sys, phymem_vista_win7_win8.sys crashing system on Win-7x64, so this issue dont fixed.

**Comment by zawawawa** [comment]
That is a known bug in the AMD driver. I will implement a workaround. Could you also try it without 1070's?

**Comment by zawawawa** [comment]
I already fixed the fan bug. The next version won't have this issue.

**Comment by V3T3RaN** [comment]
Nice work =))
Still need to check without 1070's? (i think need remove 1070's from worker.add and add 480's?)

And if i rename phymem_vista_win7_win8 to phymem, win7 crash. If dont rename, Excavator dont load phymem (turn-driver-signature-enforcement-off activated). Simple phymem.sys crash system too.

**Comment by zawawawa** [comment]
That's very helpful to know. Excavator is supposed to load phymem_vista_win7_win8.sys automatically on Windows 7, and the driver is properly signed for that. It might be the case that Microsoft changed driver signing requirements for Windows 7. I will look into this.

As for 1070's, it would be great if could physically take out 1070's and try excavator only with RX 480's. (Some motherboards allow practically the same thing with dip switches.) If it is too much trouble, you could just wait for the next version, which should be available shortly.

**Comment by cTn-dev** [comment]
Any info about when the next version will be released? 
(Since the device.set.fan.speed API was already updated as supported).

**Comment by modus2017** [comment]
I can also confirm using windows MSI 7950 ... no matter what i try with MSI afterburner to control my fan speed.. Excavator continuously down-clocks my fan speed to almost zero. Is there anyway to control the fan speed again?  After a few test run using the "start-admin.bat" i was supppppppper impressed with the hash speeds. 
I truly thank-you for your efforts .

**Comment by zawawawa** [comment]
This bug has been fixed. Please use Version 1.2.11a.
