### ISSUE TITLE
API - perhaps a mistake in the naming of the key and type?

### ISSUE THREAD

**Issue by EvgeniyKorepov** [nicehash/excavator#303]
Method **device.get** and **device.get**

Response field | Type | Description
-- | -- | --
hw_errors | int | Number of shares above target generated by this device.
hw_errors_success | array | Number of accepted shares generated by this device.

hw_errors_success - these are not errors, but the accepted shares? And the type is not an array, but an integer?

**Comment by nicehashdev** [comment]
Yes, it is int, that is my mistake. It is still being marked there so you can then compare ratio of accepted vs rejected-target (not rejected stale).
