### ISSUE TITLE
RX 6800 miner recommendation

### ISSUE THREAD

**Issue by ben1628** [nicehash/excavator#304]
I am using quick miner on my rtx 3060 TI, and it is working very well with consistent hashrate, GREAT!

I am now also mining with RX 6800 (I know I should use RTX, but can't get one).  What miner do you guys recommend?

Currently using NBMiner with 62.67 MH/s, setting is 2100, 1500.  However, it gets reset to default values if it needs to restart. I'm using afterburner to do overclocking.

**Comment by nicehashdev** [comment]
AMD cards are not supported by Excavator.
