### ISSUE TITLE
The ordinal 40 could not be located in the dynamic link library Cabinet.dll

### ISSUE THREAD

**Issue by sen7inel** [nicehash/excavator#307]
I'm getting an error "The ordinal 40 could not be located in the dynamic link library Cabinet.dll" on attempting to start Excavator running Win 7 x64.  Can this be resolved without upgrading to Windows 10?

**Comment by nicehashdev** [comment]
Yes, Excavator does not work on Windows 7. You have to upgrade to Windows 10 and this problem will be solved.
