### ISSUE TITLE
Excavator v1.6.7c hanging at "Initialized"

### ISSUE THREAD

**Issue by HPCMine** [nicehash/excavator#309]
![Excavator](https://user-images.githubusercontent.com/80962373/111783300-74223880-8890-11eb-86a5-7d0aa0678a48.jpg)

**Comment by HPCMine** [comment]
It had been running successfully for days. Stopped to play games. Started hanging after attempting to restart.

**Comment by nicehashdev** [comment]
You need to start it. You can do it locally through right click of NiceHash icon or you can do it using Rig Manager - click "play" button.
