### ISSUE TITLE
Add algorithm.print.speed

### ISSUE THREAD

**Issue by nirvanaosc** [nicehash/excavator#31]
Hi,

Is it possible to add a new method to the web api to print the speed of a specific algorithm?
Something like:

algorithm.print.speed
Prints speed of algorithm to console output.

Example usage:
{"id":1,"method":"algorithm.print.speed","params":["0"]}

Command parameter # | Type | Description
1 | string | Algorithm ID.

Example response:
{
   "id":1,
   "error":null
}

It would be really useful to me.
Thank you in advance.

Keep the great work!

**Comment by nicehashdev** [comment]
What is wrong with current API: https://github.com/nicehash/excavator/tree/master/api#algorithm-print-speeds ?

It print speeds for all algorithms. We added this mostly for debugging purposes. If you want anything more serious, please, use API algorithm.list and calculate speeds on your own.

**Comment by nirvanaosc** [comment]
I was trying to keep my framewoek simple. Managing 25 rigs is not an easy task, but I also understand that you have limited resources.

Thank you very much for your reply.
Keep the excellent work.
