### ISSUE TITLE
Nicehash excavator Error "CUDA error out of memory in func cuda_daggerhashimoto" when i use more than 2 GPUs at the same time

### ISSUE THREAD

**Issue by Calsterman** [nicehash/excavator#311]
Hi,
I have a mining rig with the following components:
Asus z270-a
i5-6500
8GB RAM
Windows 10 PRO
7x RTX 3070

Everytime i start mining with more than 2 cards at the same time the error will occur.
If i use the cards individually or 2 at a time they will work perfectly fine.
Ive so far tried to reinstall the drivers, change the clock to standard, nicehash reinstall and also different algorythims which will also crash under the same circumstances.

I dont really know what to do anymore, any help is appreciated!
Thank you

**Comment by nicehashdev** [comment]
You should definitely increase virtual memory size in Windows. That is most likely the problem you have here. You will need to set it to pretty large value - somewhere around 40-60 GB.

**Comment by Calsterman** [comment]
> 
> 
> You should definitely increase virtual memory size in Windows. That is most likely the problem you have here. You will need to set it to pretty large value - somewhere around 40-60 GB.

I actually managed to fix the issue by simply putting 23gb of ram in it i had laying around. 
Thank you for your reply

**Comment by nicehashdev** [comment]
Adding RAM is another option to solve this issue, but it is not completely free ;)
