### ISSUE TITLE
I just started getting "device #0 is running too hot..." with hotspot temperature reported as 79 degrees

### ISSUE THREAD

**Issue by differentprogramming** [nicehash/excavator#314]
I just started getting "device #0 is running too hot..." with hotspot temperature reported as 79 degrees after mining for a month.
The card is an Asus Dual 2060 super OC 
I'm using the latest version of nicehash.
And I think it was throttling way down.
GPU temp was 66 degrees.
But isn't 79 degrees a bit low to be throttling? 
I tried getting rid of the slight memory overclock and turning the fans up from 90% to 95%.
That brought the temp to 65 and the hotspot temp went back and forth from 78 to 79 degrees
The whole card already had the target power set as low as possible.
It still would occasionally report throttling.

I would tag this as a question if I could figure out how to.

**Comment by nicehashdev** [comment]
Did you modify max temperature? By default this value is over 80 C. It is possible to modify it with afterburner.
