### ISSUE TITLE
Latest Windows 10 update

### ISSUE THREAD

**Issue by qwewer0** [nicehash/excavator#317]
### Description
<s>After the latest windows 10 updates (KB5000842, KB4589212, KB4601554) I get constant `invalid dag generated is your memory is too high` issue with previously good overclock. By reverting the updates (KB5000842, KB4589212, KB4601554) the issue is gone. (not sure which update(s) could be the culprit)

I write this to inform the dev team and other miners and maybe in hope that this can be fixed on the excavator side, as it is harder to convince Microsoft to fix it if it isn't a widespread issue...</s>

**Comment by nicehashdev** [comment]
Are you running Excavator standalone or inside NHQM?

If you are running standalone, do you run it as admin so it can revert memory clock to 0 to prevent invalid DAG generation?

**Comment by qwewer0** [comment]
> Are you running Excavator standalone or inside NHQM?
> 
> If you are running standalone, do you run it as admin so it can revert memory clock to 0 to prevent invalid DAG generation?

NHM 3.0.6.3

**Comment by qwewer0** [comment]
Might not be this easy, as I wrote. It could be that the latest release [1.6.11a build 800](https://github.com/nicehash/excavator/releases/tag/v1.6.11a) causes it, as it seems I still have the issue, just didn't get it for a while and that is why I thought reverting the windows update fixed it.

@nicehashdev Is there a way to add an older release manually?

**Comment by qwewer0** [comment]
Tested NHM 3.0.5.6 and excavator 1.6.7c build 742, but I still get `invalid dag generated is your memory is too high` issue.

@nicehashdev Not sure if or what I can help on this, so until further notice I will keep this issue open, but if wanted, this issue can be closed.

**Comment by qwewer0** [comment]
PS: Don't have any issue on NBMiner

**Comment by nicehashdev** [comment]
First, try latest Excavator which you can get inside latest NHQM package.

Then, you need to run NiceHash Miner as Admin so Excavator can revert mem clock to 0 when generating DAG.

**Comment by qwewer0** [comment]
> First, try latest Excavator which you can get inside latest NHQM package.
> 
> Then, you need to run NiceHash Miner as Admin so Excavator can revert mem clock to 0 when generating DAG.

Tried it, and it seems that NHQM OC doesn't apply for GTX1060.
After manually reapplying the OC, at the moment I don't get the error, but time will tell.

If anything changes, I will let you know.

**Comment by qwewer0** [comment]
@nicehashdev Thank you for the guidance.

I uninstalled and reinstalled NHM 3.0.6.3, and with excavator 1.6.11a, I right away get `invalid dag generated is your memory is too high`
but with NHQM Prerelease v0.4.5.3 RC (same excavator 1.6.11a) I don't have that issue. (will try Prerelease v0.4.5.4 RC)

I still would love to use NHM instead of NHQM, but for now I will use NHQM, and see if on the long run I will have the issue or not.

**Comment by qwewer0** [comment]
Sorry for the quick (invalid?) updates.

Manually updated NHM's excavator to v1.6.11c (that NHQM Prerelease v0.4.5.3 RC uses) and it seems to be working as it did before my issue.

**Comment by qwewer0** [comment]
Not sure if this is any help, but here it is...

- excavator to v1.6.11c works (at least for now...)
- excavator to v1.6.11d has the same problem as excavator to v1.6.11a have.

**Comment by nicehashdev** [comment]
If you are referring to invalid DAG being built, then I told you already what you have to do. Run it as admin so it can lower mem clock when generating DAG.

It is normal that DAG gets corrupted with high memory OC. If there was no corruption then NVIDIA could already tweak mem of all cards +1000 and have better performing cards, but they don't do it.

**Comment by qwewer0** [comment]
> If you are referring to invalid DAG being built, then I told you already what you have to do. Run it as admin so it can lower mem clock when generating DAG.
> 
> It is normal that DAG gets corrupted with high memory OC. If there was no corruption then NVIDIA could already tweak mem of all cards +1000 and have better performing cards, but they don't do it.

All right, I get that, and I did that.

For now, NHM works on ex. 1.6.11c for about a half an hour now, with my original oc that I used without any problem for over a month now.

@nicehashdev If you have any task for me to test, I'm more than happy to try it out, but for now I will close this issue. Thank you for your patience.
