### ISSUE TITLE
after update to 1.6.11f not working anymore

### ISSUE THREAD

**Issue by MrEnergy64** [nicehash/excavator#318]
today I updated the excavator with the auto update to version 1.6.11f and rebooted the Windows 10 (build 19042.906) machine.
Excavator started as usal but then it hangs (no local firewall ist active), also no access to localhost:18000 anymore as well. Also GPU fan is running at 100%.

I just see this screen output:

![image](https://user-images.githubusercontent.com/58075655/113400945-e754a000-93a2-11eb-9630-e06bc650a349.png)

For the time being I will deinstall the new version and use the older version instead.

**Comment by nicehashdev** [comment]
Install latest RC 0.4.6.0.

**Comment by MrEnergy64** [comment]
I had to de-install the Excavator, after the automatic update, complete from my system, and did a fresh new install with 1.6.1f, then it works again.
