### ISSUE TITLE
Linux release

### ISSUE THREAD

**Issue by Tomas-M** [nicehash/excavator#32]
Please release precompiled binary for Linux. You know there is a huge amount of users who use Linux, especially on big mining farms. A binary which works in Ubuntu will be best for most users I guess.

**Comment by cTn-dev** [comment]
Hi, this is on an internal todo list, but since Excavator it self doesn't have a linux version (yet), there is nothing i can do at the moment.
I will be definitely looking into making a linux version when linux version for Excavator is released.

**Comment by nicehashdev** [comment]
Linux version is being worked on.

**Comment by fgarpe** [comment]
Any news about a Linux version?

**Comment by dropky** [comment]
Linux is supported with v1.3.1a and higher. 

https://github.com/nicehash/excavator/releases/tag/v1.3.1a
