### ISSUE TITLE
Nicehash miner's Excavator setting for 1080Ti ?

### ISSUE THREAD

**Issue by tumsd923** [nicehash/excavator#320]
[What is Excavator ?](https://www.nicehash.com/blog/post/what-is-excavator)

Now I'm using Phoenix miner with --straps 2 and getting around 44 mh

And I saw hashrate table from the above link that 1080Ti can get 44-ish mh, 
so, I wanna try out but I'm still not sure about the setting.

Do I need to use with ETHPill to reach that hashrate or the Excavator will automatically detect and adjust for me ?

Thanks

**Comment by nicehashdev** [comment]
Modify memory timings: https://github.com/nicehash/NiceHashQuickMiner/wiki/Memory-timings
