### ISSUE TITLE
Uncaught ReferenceError: change_fan_speed is not defined   at HTMLInputElement.onchange

### ISSUE THREAD

**Issue by lfsando** [nicehash/excavator#323]
When I try to change max fan speed using the buttons on Octune, I get a reference error for change_fan_speed. Latest version

**Comment by nicehashdev** [comment]
Please, update with the provided extra OCTune files from [here](https://github.com/nicehash/NiceHashQuickMiner/releases/download/v0.5.1.3/octune_optimize_profiles.zip).
