### ISSUE TITLE
Any plans to add nist5 algorithm?

### ISSUE THREAD

**Issue by nirvanaosc** [nicehash/excavator#33]
I noticed that sometimes **nist5** algorithm is more profitable on my GTX 1080 Tis (65% power, P2 state disabled) than any other algorithm on NiceHash using ccminer on Windows (I keep track of nist5, neoscrypt, lyra2rev2, blake256r8, daggerhashimoto, decred, cryptonight, lbry, equihash, pascal, x11gost, sia and blake2s profitability). Most of the time lbry/equihash/blake2s are the winners, but sometimes nist5 is more profitable.

Any plans to add this algo in the near future?

Thank you very much in advance.
Keep the awesome work!

**Comment by nicehashdev** [comment]
At this time, we have no plans, but if Nist5 gains in popularity, we will consider adding it.

**Comment by nirvanaosc** [comment]
Just to give some feedback: profitability as of now with one of my rigs:

nist5			estimated profit: 0.00990851 BTC/day
neoscrypt		estimated profit: 0.00665614 BTC/day
lyra2rev2			estimated profit: 0.00928830 BTC/day
blake256r8		estimated profit: 0.00334481 BTC/day
daggerhashimoto	estimated profit: 0.00929093 BTC/day
decred			estimated profit: 0.00921137 BTC/day
cryptonight		estimated profit: 0.00424904 BTC/day
lbry				estimated profit: 0.00969858 BTC/day
equihash			estimated profit: 0.01035970 BTC/day
pascal			estimated profit: 0.00564282 BTC/day
x11gost			estimated profit: 0.00764746 BTC/day
sia				estimated profit: 0.00657303 BTC/day
blake2s			estimated profit: 0.01006611 BTC/day

nist5 on the top4 around 80% of the time in the last weeks.
Regards!

**Comment by nirvanaosc** [comment]
And that is with ccminer. I honestly think it would be quite better with excavator. You did a great work with all algorithms implemented. Power consumption is quite stable in excavator, with ccminer, my GPUs have a hard time to be stable power-wise.

**Comment by nirvanaosc** [comment]
Some more feedback:

Profitability for each of my GTX 1080 Tis (as I have them configured).
My earnings are 97.7% of what NiceHash reports, so it is quite accurate.

Nist5 was the most profitable algorithm 23.9% of the time in the last month.

https://new.nicehash.com/profitability-calculator/custom?e=0.1&currency=USD&power=165&cost=0.1&algo0=0&algo1=0&algo2=0&algo3=0&algo4=0&algo5=0&algo6=0&algo7=64.64&algo8=0&algo9=0&algo10=0&algo11=0&algo12=0&algo13=0&algo14=52.857&algo15=0&algo16=6.7143&algo17=0&algo18=0&algo19=0&algo20=34.464&algo21=4.3343&algo22=0.8325&algo23=0.438&algo24=610&algo25=1.61386&algo26=0&algo27=2.609&algo28=6.28714

Regards!

**Comment by nirvanaosc** [comment]
Another update:

Nist5 was the most profitable algorithm 60% of the time in the last day, and 37% in the last week (second most profitable, after equihash) for my GTX 1080 Tis.

Regards.

**Comment by nicehashdev** [comment]
You may want to try and use NiceHash Miner Legacy which has support for Nist5.

We have no plans to add this algorithm for now as it requires a lot of recoding and work to put it in.

**Comment by nirvanaosc** [comment]
I will. Thank you.
I just wanted to keep you updated in case this is relevant information for you.
I will stop now, I don't want to spam you.
Thank you for your hard work again.
