### ISSUE TITLE
PCI Slot information for device.get

### ISSUE THREAD

**Issue by cTn-dev** [nicehash/excavator#34]
Hi guys, would you be willing to add PCI Slot (location) information to the device.get properties?
One of my GUI users pointed out that it would be handy to also display this value in the UI.
![example](https://user-images.githubusercontent.com/2289413/27987024-ce5971d0-6407-11e7-9591-c93458fcecc8.png)

**Comment by nicehashdev** [comment]
You can already get BUS ID of NVIDIA device, check API: https://github.com/nicehash/excavator/blob/master/api/README.md#device-get

Regarding AMD: you need to ask @zawawawa this.

**Comment by cTn-dev** [comment]
Yup, the BUS ID is indeed there, but as far i know you can't get the PCI Slot info from that.
Maybe @zawawawa can indeed shine some light on this subject?

**Comment by zawawawa** [comment]
Well, you could try the UINumber field in the IRP_MN_QUERY_CAPABILITIES request, but I'm not sure if you want to go that far...
https://msdn.microsoft.com/en-us/library/windows/hardware/ff551687(v=vs.85).aspx
https://msdn.microsoft.com/en-us/library/windows/hardware/ff546599(v=vs.85).aspx

**Comment by zawawawa** [comment]
Actually, I found that piece of info in HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Enum\PCI

**Comment by zawawawa** [comment]
![registry](https://user-images.githubusercontent.com/23463506/27989525-4bc72c3e-63ef-11e7-8ba5-953ac9d272a1.png)

**Comment by zawawawa** [comment]
There shouldn't be any problems matching up the bus number with a slot number. Please let us know if anything.

**Comment by cTn-dev** [comment]
Awesome find there, this is actually the reason why i wanted to have it in the API it self, since grabbing this would require quite a bit of tinkering (my GUI uses the http api and more "system" related operations are handled by default node.js package).
Even if you decide to not have it in the API, i got a clue how to tackle the problem now.
Thank you.

**Comment by zawawawa** [comment]
My pleasure. It certainly makes more sense to have it in the API. I would look into this further after the Linux port.

**Comment by cTn-dev** [comment]
That would be amazing, take your time (this is hardly a must have feature).
From what i saw on the forums, everyone seems to be "demanding" a linux version, so i fully understand that.
I am super happy that Excavator has an http API, its the whole reason why i decided to make a GUI for it :-)

**Comment by nicehashdev** [comment]
This will be available in next version. Closing.
