### ISSUE TITLE
Is it possible to apply memory offsets beyond -500?

### ISSUE THREAD

**Issue by nirvanaosc** [nicehash/excavator#36]
Hi,

I am changing my framework (that uses excavator to mine), to adjust memory speeds for each algorithm in order to maximise my GTX 1080 Tis.
I've noticed that decred, lbry, pascal, sia and blake2s doesn't require fast memory. The lower the memory, the faster excavator mines on this algorithms, because there is more power available to the core, hence higher core clocks with the same TDP.

I have P2 disabled to avoid any problems with going to P0 with +500 memory offset (to mine daggerhashimoto/equihash). Reliability is important with 23 rigs, but this renders me unable to go below 5000Mhz (-500 offset) on the memory using excavator.

I did some investigations in order to find out how faster the mentioned algorithms get with lower memory speeds. NvidiaInspector allowed me to set -1000 offset. This, on top of P2 allowed me to go as low as 4000MHz.

The results relative to P0 are:

decred +0	= 29.20		
decred -500	= 29.74	(+1.8%)
decred -1000	= 29.85	(+2.2%)
decred -1500	= 30.34	(+3.9%)

lbry +0		= 3			
lbry -500		= 3		(+0%)
lbry -1000	= 3.0397	(+1.3%)
lbry -1500	= 3.0657	(+2.2%)

pascal +0		= 11.0225
pascal -500	= 11.117	(+0.8%)
pascal -1000	= 11.198	(+1.6%)
pascal -1500	= 11.297	(+2.5%)

sia +0		= 17.743
sia -500		= 17.920	(+1%)
sia -1000		= 18.067	(+1.8%)
sia -1500		= 18.263	(+2.9%)

blake2s +0	= 42.84
blake2s -500	= 43.25	(+1%)
blake2s -1000	= 43.64	(+1.8%)
blake2s -1500	= 44.01	(+2.7%)

I know I can achieve -1000 (relative to P0) with excavator setting -500 (maximum) offset in P2, but I don't want to enable P2 due to reliability.

I was wondering if it is possible to allow excavator to apply bigger offsets to memory, in order to go to 4000MHz or even lower (I would like to find out when those algorithms start getting worse due too slow memory speed, but I have the feeling that they could improve even further).

Thank you in advance and keep the awesome work!

**Comment by nicehashdev** [comment]
We will make more relaxed boundaries for next version. However, you should note that if you set value too big or too small, it may fail to be applied. Not all cards support going -2000 on memory. Most of them only allow -500.

**Comment by nirvanaosc** [comment]
Yes, we understand that. The framework doesn't go to production until memory/core clock offsets are tested in all cards! We need to be conservative to avoid issues.

Thank you.

**Comment by UselessGuru** [comment]
Hi nirvanosc
>> I have **P2 disabled** to avoid any problems with going to P0 
How do you do this on a 1080TI (under windows)?
TIA

**Comment by nirvanaosc** [comment]
Hi UselessGuru,

I am using Nvidia Profile inspector version 2.1.3.7. Other versions doesn't have the option, for some reason.
The option is called "CUDA - Force P2 state" (under section: 5 - Common). You have to turn this option off.

You can download it from here:
https://ci.appveyor.com/project/Orbmu2k/nvidiaprofileinspector/build/2.1.3.7/artifacts

**Comment by nirvanaosc** [comment]
Should this be open? I closed it because you mentioned that it was going to be on next version, but I just noticed that you did the same with a bug and kept it opened.

Regards.

**Comment by nicehashdev** [comment]
This feature has already been applied and will be available in next ver.

**Comment by nirvanaosc** [comment]
I am very looking forward to the next version.
May I ask how relaxed are the memory offsets now and when you think next version will be released?
Thank you very much in advance.
