### ISSUE TITLE
daggerhashimoto worker problem when using API

### ISSUE THREAD

**Issue by cTn-dev** [nicehash/excavator#38]
Hi, this is an odd bug i found recently by accident.
1. Start an dagger algorithm (i used 1 gpu and 1 worker), let it mine couple of shares.
2. Then remove the worker through worker.free, wait couple of minutes (2-3, just to be sure).
3. Add new worker for the still active algorithm.

What will happen now, all the shares will be rejected (reasons: above target or job not found).
Am i using the API wrong, or is this a bug? (doing the same thing with equihash works just fine)

Can you guys confirm this?

**Comment by nicehashdev** [comment]
We will take a look into this.

**Comment by zawawawa** [comment]
Which GPU were you using?

**Comment by cTn-dev** [comment]
@zawawawa I tried it on GTX 1080

**Comment by nicehashdev** [comment]
Run it with -f 0, then attach log here please, when it happens.

**Comment by cTn-dev** [comment]
Sure, give me a few minutes as it takes a little while to get shares with 27 MH/s, i will report back ASAP.

**Comment by cTn-dev** [comment]
Wow, for some odd reason i am unable to replicate the problem anymore (while before i managed to replicate it on the first try), this bug was brought to my attention by another user, unfortunately i wasn't able to get a full log from him either :(

I did seen in the log that the DAG cache "re-generated" while mining and that resulted in a rejected share (job not found), but it recovered on its own after that.

I will let the miner run for couple of hours and try to re-test afterwards as i am 100% sure something is breaking on the miner side, just can't seem to create the right conditions to break it right now :/

**Comment by nicehashdev** [comment]
Well, it is nothing unusual if the stale share was done during DAG regeneration. This process takes some time. The problem would be, if you had rejects AFTER dag was done for several more minutes, but if it was only few seconds after DAG regeneration, that is normal.

**Comment by cTn-dev** [comment]
I also thought the rejected share during DAG generation is normal.
Ill keep testing, since the user that first reported this said the problem started occurring after 1-3 hours of mining.

The only odd thing i managed experience while hunting for this bug (i should say that this have never happened before), the HTTP API completely stopped receiving requests for no apparent reason, i had 0 level logging enabled, so i made a little data cut out for it.

From a small inspection there doesn't seem to be any useful info there about it, i am appending it anyway in case you would see something i don't.

I send API calls periodically every 5 seconds, in the beginning of the log you can see the last one that is processed.

[cut_out.txt](https://github.com/nicehash/excavator/files/1133943/cut_out.txt)

**Comment by nicehashdev** [comment]
This can happen, because DAG cache generation on CPU is generated by the same worker thread(s) that process networking, API etc... so they may get "blocked" for a short period of time.

**Comment by cTn-dev** [comment]
I understand, i posted the log as well to show that there was no DAG generation happening at that moment, it stopped receiving commands out of the blue and never recovered (while the miner continued to mine without any issues), that's why i thought its worth mentioning even thought it might not have anything in common with the issue that i initially reported.

**Comment by dropky** [comment]
Let me know if you still have these issues with the latest Excavator.
