### ISSUE TITLE
Incomplete algorithm.list response after worker.reset

### ISSUE THREAD

**Issue by nirvanaosc** [nicehash/excavator#39]
I noticed (by mistake) that if you call worker.reset in all workers and immediately call algorithm.list, the response is incomplete:

{"algorithms":[{"algorithm_id":0,"name":"equihash","connected":true,"got_job":true,"details":{"total_shares":333,"total_accepted":333,"total_rejected":0,"last_efficiency":1.0},"address":"equihash.eu.nicehash.com:3357","login":"BTCADDRESS:x","workers":[{"worker_id":0,"device_id":0,"params":[],"speed":312.5},{"worker_id":1,"device_id":0,"params":[],"speed":312.5},{"worker_id":2,"device_id":1,"params":[],"speed":187.5},{"worker_id":3,"device_id":1,"params":[],"speed":187.5},{"worker_id":4,"device_id":2,"params":[],"speed":187.5},{"worker_id":5,"device_id":2,"params":[],"speed":312.5},{"worker_id":6,"device_id":3,"params":[],"speed":187.5},{"worker_id":7,"device_id":3,"params":[],"speed":312.5},{"worker_id":8,"device_id":4,"params":[],"speed":62.5},{"worker_id":9,"device_id":4,"params":[],"speed":375.0},{"worker_id":10,"device_id":5,"params":[],"speed":0.0},{"worker_id":11,"device_id":5,"params":[],"speed":250.0},{"worker_id":12,"device_id":6,"params":[],"speed":

The way the response is truncated suggests that there was a problem when retrieving a worker's speed.

Regards.

**Comment by nicehashdev** [comment]
Thanks for report. Will be fixed in next version.

**Comment by nicehashdev** [comment]
This has been fixed.
