### ISSUE TITLE
1.2.4 Alpha - Can't load phymem.sys - unsigned driver

### ISSUE THREAD

**Issue by natv** [nicehash/excavator#4]
I'm running Windows 10, running excavator as administrator. (tried as regular user and then as administrator) **It's complaining that it's an unsigned driver.**

I tried this and rebooted:
**bcdedit.exe /set nointegritychecks on**

But I still get the same error. Any known other workaround?

Thanks

![image](https://user-images.githubusercontent.com/1175232/26960163-0d559b9c-4ca3-11e7-8658-2f8e1bff92fc.png)

**Comment by nicehashdev** [comment]
Please, read here: https://github.com/nicehash/excavator/tree/master/amd#equihash
