### ISSUE TITLE
Cuda illegal memory access and worker issue

### ISSUE THREAD

**Issue by Phuzzyhead** [nicehash/excavator#41]
I'm getting cuda illegal memory access error, stopping my miner while running daggerhashimoto.
- Excavator does detect that and shuts down api, http etc, but not excavator itself. Would be great if you could make it shut down properly and maybe even auto-restart.
- Worker names are strange in general. I would guess worker 0-0 ist the first worker on the first GPU, followed by 1-1 (w1 gpu1), 2-2, 0-3, 1-4, 2-5 (I'm using 3x1070). See next point on why I'm not sure about that.
- I thought GPU RAM OC might be at fault here, but I get 1 error each from 2 workers and judging by the names of the workers, these should not be on the same card (e.g. worker 1-2 and 2-4). I would consider it very unlikely that mem runs without problem for a while (1-2 days even) just to suddenly hit a problem on 2 cards at the exact same moment. Maybe since it's always 2 cards, something about the dag copying/caching from 1 card through host RAM is going wrong?
- Usually 2 workers per card are initialised, but after auto profit switching, sometimes only 1 per gpu is started. Sometimes this doesn't change anything, not even the hashrate. Sometimes excavator will freeze and just stop without any warning whatsoever, leaving the last speed report as the last line.

Would be great if you could help.
Regards,
Daniel

**Comment by nicehashdev** [comment]
Please, let us know your cmd file.

Regarding cuda errors - when they happen, excavator has to quit. If it doesn't, please provide log file when this happens.

**Comment by Phuzzyhead** [comment]
Excavator is run by the NiceHashMiner2 for me. I don't know where to find the command NHM2 uses. Is it the default file?
Please point me there and I will provide it.

Same goes for logs. Which one exactly do you need? The logs in nhm2/logs/ do not date back far enough, so in that case I will have to wait for it to happen again.

FYI: Today when starting excavator (manually through button in nhm2), only 1 worker per GPU is started. What would be the correct behaviour for 1070s? 1 or 2 workers per GPU?

**Comment by nicehashdev** [comment]
Only equihash needs 2 workers, otherwise, 1 worker per GPU.

I suggest you to file bug report to NHMv2.

**Comment by nirvanaosc** [comment]
I have experienced the illegal memory access on daggerhashimoto too. This happened to me when I was testing with different argument values to find a better combination for my GPUs.
I created a python script to test each argument  combination for 2 minutes, then stopping all workers to add new ones with the next argument values. I experienced this issue randomly, usually within the first 20 minutes.
I am happy with sharing my script for debug purposes,  but not publicly, although I believe that if you create a script to stop all workers and add new ones with 2 minutes in between you should experience this issue.

Unfortunately I am away for the rest of the week with no access to my computers, so if you need me to provide something to help debugging this issue, and it will have to be next week. 

Regards.

**Comment by nirvanaosc** [comment]
PS: I was going to open a bug for this once I'm back next week, but since I noticed this one, I decided to share my experiences in case they are of any help now.

**Comment by nirvanaosc** [comment]
I am back.
I created a simple version of the python script that reproduces the issue. It usually takes less than 10 minutes with 8 GPUs.
As I described before, the script starts and stops the workers. I am happy to provide you with the script, but I don't want to share it publicly. Let me know an email address you want me to send it to you.

Regards.

**Comment by nicehashdev** [comment]
Did you perform these tests with any overclocks or with stock clocks?

**Comment by nirvanaosc** [comment]
Stock core and memory clocks, also P2 enabled (default). I would have specified alterations otherwise.

**Comment by nicehashdev** [comment]
illegal memory access is indicator that something was overclocked too much.. or there is a code error.

Do you get same results with 1 card? Maybe trying to find out the faulty card.

**Comment by nirvanaosc** [comment]
I agree with you. As a compute driver developer, I had to deal with illegal memory access at my work many times.
I do not think that there is any faulty card, because I tried stopping excavator and starting it again (instead stopping the workers and adding new ones) and this resulted in the script working flawlessly for the length of the test (48 hours).

**Comment by dropky** [comment]
Please, run latest Excavator/NHMv2 and report back if you still have this issue. Thank you.
