### ISSUE TITLE
Decred stuck at <5% GPU load

### ISSUE THREAD

**Issue by nirvanaosc** [nicehash/excavator#43]
Our framework starts excavator and adds/removes workers based on the most profitable algorithm.
We have noticed that after excavator has been running for some time (1-2 hours), if we stop all workers and add new ones for Decred algorithm (default arguments), the GPUs are stuck at less than 5% load.
Interestingly, the speed reported by the workers seems buggy too, it being 100 times more than GPUs@100% load.

When this happens, if excavator is stopped and started again, the problem goes away.

**Comment by nicehashdev** [comment]
That sounds as a driver crash in the middle + failures to launch kernel, for which we haven't been able to find a way to detect properly. We will take a look how to detect kernel failures.

**Comment by nirvanaosc** [comment]
It only happens with Decred though, if we don't restart excavator and we change again to another algorithm by removing/adding workers, excavator work flawlessly, but when it goes back to Decred, it happens again.

**Comment by nicehashdev** [comment]
This is the same issue that can happen with ccminer - launch failure that isn't reported as error so excavator keeps going on.

If your cards are OCed, reduce OC.

**Comment by nirvanaosc** [comment]
Ok, I found the issue(s).

There are two things here:

The first one is that if you
- start a worker with custom arguments (i.e. lbry with B=6144,TPB=768,NPT=16)
- stop the worker
- add a new worker on decred **without custom arguments**
it will use the custom ones used in lbry. I assume it's because it's reusing the CUDA thread with the custom arguments, because if I add a new decred worker without stopping the lbry one (hence creating a new thread) it start it with default arguments.

The second issue is that, even though B=6144,TPB=768,NPT=16 are within the argument limits specified for decred in the documentation, it doesn't work with those arguments. This is an issue I was going to report with other arguments, since I sampled the argument space with many combinations for daggerhashimoto, lbry and decred and I found combinations that were not working despite of being within the limits stated in the documentation.

**Comment by nicehashdev** [comment]
Yep, that could be it! Nice catch, thank you!

You can verify if this is the case by calling API algorithm.list which will also list workers and their parameters. If there is something you did not add, then this is trully the issue.

Will be fixed in next version.

**Comment by nirvanaosc** [comment]
Looks like algorithm.list always shows the parameters empty:

**Add lbry workers with arguments B=6144,TPB=768,NPT=16**

[21:33:24][0x000006c8][info] wrkr3-3 | Algorithm: CUDA-lbry parameters: B=6144,TPB=768,NPT=16
[21:33:25][0x00001ec8][info] wrkr5-5 | Algorithm: CUDA-lbry parameters: B=6144,TPB=768,NPT=16
[21:33:27][0x000006d8][info] wrkr7-7 | Algorithm: CUDA-lbry parameters: B=6144,TPB=768,NPT=16
[21:33:27][0x0000177c][info] wrkr6-6 | Algorithm: CUDA-lbry parameters: B=6144,TPB=768,NPT=16
[21:33:30][0x00002108][info] wrkr0-0 | Algorithm: CUDA-lbry parameters: B=6144,TPB=768,NPT=16
[21:33:30][0x000011d8][info] wrkr1-1 | Algorithm: CUDA-lbry parameters: B=6144,TPB=768,NPT=16
[21:33:30][0x00000ae8][info] wrkr2-2 | Algorithm: CUDA-lbry parameters: B=6144,TPB=768,NPT=16
[21:33:31][0x000020b4][info] wrkr4-4 | Algorithm: CUDA-lbry parameters: B=6144,TPB=768,NPT=16

{'algorithms':
	[{'algorithm_id': 0,
	  'name': 'lbry',
	  'connected': True,
	  'got_job': True,
	  'details': {'total_shares': 10,
				  'total_accepted': 10,
				  'total_rejected': 0,
				  'last_efficiency': 1.0},
	  'address': 'lbry.eu.nicehash.com:3356',
	  'login': 'x:x',
	  'workers': [{'worker_id': 0, 'device_id': 0, 'params': [], 'speed': 391009781.61415625},
				  {'worker_id': 1, 'device_id': 1, 'params': [], 'speed': 391009781.61415625},
				  {'worker_id': 2, 'device_id': 2, 'params': [], 'speed': 391009781.61415625},
				  {'worker_id': 3, 'device_id': 3, 'params': [], 'speed': 426823087.4625873},
				  {'worker_id': 4, 'device_id': 4, 'params': [], 'speed': 393728667.535854},
				  {'worker_id': 5, 'device_id': 5, 'params': [], 'speed': 418158225.5044178},
				  {'worker_id': 6, 'device_id': 6, 'params': [], 'speed': 415705440.8525755},
				  {'worker_id': 7, 'device_id': 7, 'params': [], 'speed': 415705440.8525755}]
	}],
'id': 1,
'error': None
}

**Remove workers**
**Add decred workers with no arguments**

[21:33:43][0x000011d8][info] wrkr1-1 | Algorithm: CUDA-decred parameters: B=6144,TPB=768,NPT=16
[21:33:43][0x000006d8][info] wrkr7-7 | Algorithm: CUDA-decred parameters: B=6144,TPB=768,NPT=16
[21:33:43][0x0000177c][info] wrkr6-6 | Algorithm: CUDA-decred parameters: B=6144,TPB=768,NPT=16
[21:33:43][0x00001ec8][info] wrkr5-5 | Algorithm: CUDA-decred parameters: B=6144,TPB=768,NPT=16
[21:33:43][0x000020b4][info] wrkr4-4 | Algorithm: CUDA-decred parameters: B=6144,TPB=768,NPT=16
[21:33:43][0x00000ae8][info] wrkr2-2 | Algorithm: CUDA-decred parameters: B=6144,TPB=768,NPT=16
[21:33:43][0x00002108][info] wrkr0-0 | Algorithm: CUDA-decred parameters: B=6144,TPB=768,NPT=16
[21:33:43][0x000006c8][info] wrkr3-3 | Algorithm: CUDA-decred parameters: B=6144,TPB=768,NPT=16

{'algorithms':
	[{'algorithm_id': 1,
	  'name': 'decred',
	  'connected': True,
	  'got_job': True,
	  'details': {'total_shares': 0,
				  'total_accepted': 0,
				  'total_rejected': 0,
				  'last_efficiency': 1.0},
	  'address': 'decred.eu.nicehash.com:3354',
	  'login': 'x:x',
	  'workers': [{'worker_id': 0, 'device_id': 0, 'params': [], 'speed': 363666194920.3757},
				  {'worker_id': 1, 'device_id': 1, 'params': [], 'speed': 360316232231.9314},
				  {'worker_id': 2, 'device_id': 2, 'params': [], 'speed': 396066294173.94855},
				  {'worker_id': 3, 'device_id': 3, 'params': [], 'speed': 351756358245.81464},
				  {'worker_id': 4, 'device_id': 4, 'params': [], 'speed': 368280100586.36176},
				  {'worker_id': 5, 'device_id': 5, 'params': [], 'speed': 400639096003.26666},
				  {'worker_id': 6, 'device_id': 6, 'params': [], 'speed': 373859946414.0466},
				  {'worker_id': 7, 'device_id': 7, 'params': [], 'speed': 342559374791.3434}]
	}],
'id': 1,
'error': None
}

**Comment by nicehashdev** [comment]
Will take a look into this too.

**Comment by dropky** [comment]
Both issues have been fixed. Thank you for the feedback!
