### ISSUE TITLE
Not sending shares

### ISSUE THREAD

**Issue by tryonex** [nicehash/excavator#45]
So I was using a Java Program to start Excavator and it seemed to work fine until I didn't get any shares. It seems that it finds nonces, but just doesn't send it to the server.
However when I was starting excavator using a batch file, everything worked as usual.
What could be reasons for excavator not sending shares?
Log File is attached.
Thanks for the help.

[logfile.txt](https://github.com/nicehash/excavator/files/1203378/logfile.txt)

**Comment by nicehashdev** [comment]
Make sure console window is not hidden.

**Comment by sasukexy** [comment]
Hi,
I am using excavator, it is connected successfully to pool but no share is being sent (shares accepted = 0)
the miner gets a new job from the pool but no work is done. 
it does display the hash rate.
![Uploading image.png…]()

**Comment by serdaroquai** [comment]
For those who would like to start Excavator from a java process can use: 

`Runtime.getRuntime().exec("cmd /c start excavator.exe");`
