### ISSUE TITLE
rejected shares: "Share above target" error

### ISSUE THREAD

**Issue by mrAnderson978** [nicehash/excavator#46]
Around 9% of my shares are rejected with the error "Share above target."

Rejected shares appear mostly after "Generating DAG cache..." appears in the output log.

**Comment by zawawawa** [comment]
I'm looking into this right now.

**Comment by m-asiatici** [comment]
Same here: in fact, depending on the time, I get as many as 60% rejected shares:
![image](https://user-images.githubusercontent.com/14234877/29487341-a703bf3a-84f7-11e7-9b20-276ec559bdc2.png)
I found no correlation with the "Generating DAG cache" in the log as mentioned by mrAnderson978. I'm using a GeForce GTX 1060 3 GB on Windows 7 64 bit, driver version 382.33, Nicehash 2.0.0.12. I'm based in Switzerland, so I guess I'm using the EU servers.

**Comment by mrAnderson978** [comment]
What m-asiatici describes above happened to me a few days ago.
I couldn't even turn the miner off by the usual means - I had to reboot my computer.

**Comment by usbport3** [comment]
All my shares are rejected as stale when more than one gpu is in operation. Also getting disconnecting by pool

**Comment by reaper3bot0** [comment]
yup same issue get this constantly at differnet times sometimes a wall of Rejected shares above target...

Really makes you want to switch to another pool like slush or something...

This happens with daggerhashimoto only for me.

**Comment by reaper3bot0** [comment]
Been happening since 2.0.0.8.... all the way to 2.0.0.12.
Would also like the stupid box for excavator to not be there till I start actually mining instead of being there when I start nicehash miner.

**Comment by mrAnderson978** [comment]
Appears fixed for me in the latest release

**Comment by reaper3bot0** [comment]
![nicehashindeed](https://user-images.githubusercontent.com/31227279/29857329-2dfa320e-8d26-11e7-94ce-e5ef84ca7514.jpg)

I wont use nicehash anymore they can go FUCK themselves they included trojans in there legacy 1.8 version and 2.0.0.12.

**Comment by mrAnderson978** [comment]
Malwarebytes _routinely_ picks up mining software as trojans.  It's not.
I don't know if it's because Malwarebytes (and several other anti-virus companies) are morons, or because they think the software has the _potential_ to be used as a trojan - I expect it's just the possibility it could be used as a trojan.
Think about it.  Imagine you could compile a version of ccminer which mined to your personal bitcoin address.  Then imagine you had a botnet working for you with a million computers.  this would make you thousands of $$$. 
This is probably why Malwarebytes has listed it as a trojan.
So long as you downloaded nicehash from the link provided, you've got nothing to worry about.

**Comment by reaper3bot0** [comment]
It sure in heck was trojans my computer was acting wierd ever since they removed it my computers been fine no more redirecting no more anything.

**Comment by aaronsace** [comment]
@reaper3bot0 Please just take in what @mrAnderson978 is saying and don't be one of those.

**Comment by m-asiatici** [comment]
Still an issue for me even on the new release:
![image](https://user-images.githubusercontent.com/14234877/29883980-390ca384-8db2-11e7-88a9-c914c9c97c78.png)

**Comment by reaper3bot0** [comment]
@aaronsace I took in everything I took in proof. I am a computer programmer they bundled there 2.0.0.12 with 2 trojan virus third party softwares. They also did it with the legacy 1.8.1.1
I wondered why my profit plumited and why all of a sudden my computer was acting funny. Then I started doing research on the redirects. They had installed spyware and trojans on my system with there 2 versions of software. I dont accept malicious software on my system. I could run a clean miner program on my computer and use nicehash but why the shit would I with the way they treat people. Doing crap like that was the last straw. Everyone should be wary of crap like this. Thats how you get hacked on accounts that matter by being spied on and getting your login info stolen.  I have money invested in cloud mining anyways right now Ill never touch scamhash again.

**Comment by reaper3bot0** [comment]
@m-asiatici have you run a malware scan / anti virus scan on your system? You've been warned.

Also ya that 0.02 BTC bullshit was down right dirty any time id go afk theyd have there systems drop the payout. Scamhash! Meanwhile they make $$$ off the buyer and scam the $$$ off our profit then scam us again with fees. We got no transaction fees. There are tons of good mining pools out there. You want to make great amounts of $$$$$$$$$ get out of Scamhash pool assign your hash power to a pool that will pay you properly.

**Comment by aaronsace** [comment]
@reaper3bot0 I am am a Software Engineer and have experience with every miner out there. Don't flame on GitHub.

**Comment by mrAnderson978** [comment]
m-asiatici, are you using 1.3.0a of excavator? That graph looks a lot different to my original problem. Turn down your overclock by 10% and see if the problem's still there.

**Comment by zawawawa** [comment]
This bug has been taken care of. Thank you for the feedback!

**Comment by xsteacy** [comment]
@reaper3bot0 Could you point the trojan in the source code, I can't find it... kufkufkuf

Oh and these Antiviruses started pointing trojan/virus because of the flood in the CPU mining, those on the web page or install on our computer without knowing it. They stopped this infestation ... but the algorithm for mining is the same as the one you have in a program that you have installed yourself. That algorithm is what and why those stupid antiviruses think that it's a virus...
You should really look foward to get another job, you're very bad in computer programming. VERY
