### ISSUE TITLE
excavator causing system instability

### ISSUE THREAD

**Issue by fszotyi** [nicehash/excavator#47]
Hi,
I have a MSI RX 480 Gaming X 8G on stock bios. Since nicehash miner version 2.0.0.9 excavator opens and remains opened indiferent that i use it or not. (cannot be closed, starts itself automatically). Problem still occurs with version 2.0.0.12,
If i start to mine my system gets instant black screen of death or in about 2-3mins. While it works i am getting awesome performance from the video card but it wont last much. Artifacts appear (image uploaded below) and the full system freezes, have to reset from button.  Tested with 17.7.1,.17.7,2, and blockchain beta driver. Its the same with every driver.
 I guess it has to do something with the hardware acceleration or excavator does some overclocking wich is to much for my card.
It doesnt matter that i mine with excavator or with for example claymore.
Temporary solution is that i start with -na parameter, but then Nicehash miner v2 needs at least 5 minutes to start, stucked on "starting excavator server" message. With -na paraeter my  system is rock stable even on 24/7.
In the future could you implement an adjustable overclock for AMD cards? (since it shuts down radeon setting and afterbuner) or start excavator like in miner 2.0.0.8 where it shut itself down after initialization or idk.
Thank you for reading this message.
![image](https://user-images.githubusercontent.com/31073164/29371404-f04d4042-82b0-11e7-92d5-1dfe3f7ba045.png)

**Comment by nicehashdev** [comment]
Excavator is not used by default with NHM v2.0.0.12 for AMD cards.

We are aware of many AMD-related issues. AMD is simply a can of worms. Perhaps @zawawawa can help you further here.

**Comment by reaper3bot0** [comment]
No its definatley 2.0.0.8 to 2.0.0.12 I have a Nvidia 1070 and same issue with excavator it starts on load of nicehash miner and just sits there if Im not using it it still sits there. Also getting alot of daggerhashimoto rejected shares above target. What ever you guys did since 2.0.0.7 you ruined the miner program nicehash...
That version did not have any issues like these.

**Comment by jeffstokes72** [comment]
@nicehashdev  Similar issue with my 1070. I get awesome calculation rates for Lyra2rev2 (yay!) however eventually my system will crash with an IRQL_NOT_LESS_OR_EQUAL bsod. Win10 non-insiders.

**Comment by dropky** [comment]
Please, run latest NHMv2 and report back if you still have these issues.

**Comment by pookie1** [comment]
I can confirm it's a prob still even with Nvidia 1070. Win 10. Latest HNMv2. It Was running no prob until last few days :(
