### ISSUE TITLE
Cuda Error with NH ver 2.0.1.1 beta

### ISSUE THREAD

**Issue by sriminer** [nicehash/excavator#50]
Hello Support,

I am using nvidia gtx 1070 and latest Nicehash version.  It works fine for daggerhashimoto/decreed while it switches to equihash the miner gets stuck with cuda error. This is seriously effecting the mining revenues.. had to check the miner manually every half an hour to restart it

Please see error below

![nh-cudaerror](https://user-images.githubusercontent.com/31249729/29998379-75a0694a-903a-11e7-9683-c403593801b5.png)

Let me know if anyone have any suggestions on sorting this out

Thanks

Best regards

**Comment by Cheesebaron** [comment]
My machine also has issues switching to equihash it is running a bunch of GTX 1070 too. It can run for a day or two just fine sometimes other times it runs for a couple of hours and it starts throwing errors. Restarting excavator or the nicehash miner doesn't help.

Something with cuda_eq_run, will take a screenshot next time this happens. Any guidelines on how to debug this, or what information to provide?

**Comment by dropky** [comment]
We fixed some issues that happened when switching to equihash. Please let me know if you still encounter this problem with the latest version of NHMv2 (v2.0.1.3).

**Comment by Cheesebaron** [comment]
@dropky it has been working pretty well the last 2 weeks or so. Thanks!

**Comment by juville** [comment]
![image](https://user-images.githubusercontent.com/34241492/33556800-248c0006-d940-11e7-951d-0040c8202022.png)

Anyone can help why did i encounter this issue?

**Comment by dropky** [comment]
@juville I suspect it is overclocking causing the problem. Try to downclock slowly to see the breaking point.
