### ISSUE TITLE
pool host dns resolution.

### ISSUE THREAD

**Issue by miningpoolhub** [nicehash/excavator#51]
When I input
```
{"id":1,"method":"algorithm.add","params":["daggerhashimoto","us-east.ethash-hub.miningpoolhub.com:20535","usename.workername"]}
```
then it doesn't work.

But when I replace hostname with IP address then it works.
{"id":1,"method":"algorithm.add","params":["daggerhashimoto","45.56.113.50:20535","usename.workername"]}

Same for other algo too.

Please fix this issue.

**Comment by nicehashdev** [comment]
We decided to block your pool after you violated our EULA. We will make further, harder to detect and more strict blocks if you continue to disrespect our EULA.

**Comment by aaronsace** [comment]
@miningpoolhub Some Karma? 

https://www.reddit.com/r/NiceHash/comments/7i0s6o/official_press_release_statement_by_nicehash/

**Comment by miningpoolhub** [comment]
@nicehashdev I didn't even ran your excavator miner before. I actually didn't even know until my miner told me about excavator mining program.
@aaronsace Hew... So much hacking these days.
