### ISSUE TITLE
Nvida not working

### ISSUE THREAD

**Issue by ownmask** [nicehash/excavator#52]
Is not working with nvida card. is trying to detect amdn driver and I don't have an amd card only nvida card.

**Comment by ownmask** [comment]
Why doesn't this work with an ASUS GT630 2GB DDR2 ?

**Comment by ExtendLord** [comment]
Your GPU is too weak for mining.
You will need at least gtx 960 or gtx 1050 to mine.
GTX 1050 will produce currently half dollar worth of BTC per day.

**Comment by dropky** [comment]
Only CUDA devices with SM 5.0 and higher are supported.
