### ISSUE TITLE
v1.3.3a  dea16d2 : CUDA error 'a PTX JIT compilation failed' in func 'get_device_bus_id_str' line 79

### ISSUE THREAD

**Issue by ar-nit** [nicehash/excavator#54]
![screenshot 137](https://user-images.githubusercontent.com/11644819/32003750-3ad11134-b9ca-11e7-82c4-0a7367187988.jpg)
![screenshot 138](https://user-images.githubusercontent.com/11644819/32003761-41f1ead8-b9ca-11e7-8530-ce182b12dc7a.jpg)

**Comment by dropky** [comment]
This looks like a compiling issue. @zawawawa can you please take a look into this?

**Comment by zawawawa** [comment]
Please upgrade the NVIDIA driver to the latest version.
