### ISSUE TITLE
How to use HTTP API on Ubuntu 14.04.4 LTS ?

### ISSUE THREAD

**Issue by ar-nit** [nicehash/excavator#57]
I execute command: excavator -c /opt/excavator/etc/default_command_file.json -d 2 -f 6 -p 0 -wp 38080 -wi 127.0.0.1 -wa 
![screenshot 144](https://user-images.githubusercontent.com/11644819/32332185-659359ce-c017-11e7-8ab3-fb39f4d28d09.jpg)
but I can't use HTTP API.
![screenshot 146](https://user-images.githubusercontent.com/11644819/32356773-1c55b394-c06a-11e7-8216-78e70819f8f2.jpg)

**Comment by Kayfolom** [comment]
try -wi 0.0.0.0 or -wi eth_ip_address

**Comment by ar-nit** [comment]
not work for me.
![screenshot 144](https://user-images.githubusercontent.com/11644819/32523968-390d3202-c450-11e7-84fe-cc789fa03de8.jpg)
![screenshot 145](https://user-images.githubusercontent.com/11644819/32524004-6000c298-c450-11e7-9d05-ac2d6cb00386.jpg)
