### ISSUE TITLE
Version 1.3.6 alpha NVIDIA - API is broken

### ISSUE THREAD

**Issue by Kayfolom** [nicehash/excavator#58]
Version 1.3.6 alpha NVIDIA - API is broken? 

In web interface:
"equihash | FAIL | **undefined** | 607.460 H/s | 0.000 H/J"

**Comment by dropky** [comment]
There is nothing wrong with the API. A mistake was made when preparing a release, attachment contained the old web/index.html file. I uploaded the latest one 5 minutes ago, please re-download the zip packet. Sorry for the inconvenience.

**Comment by Kayfolom** [comment]
There were no changes in the API? It would be nice to add the version number of the API to the description https://github.com/nicehash/excavator/tree/master/api and {"id":1,"method":"info","params":[]}
Otherwise, it is necessary to learn about this only after complaints from users in my application https://play.google.com/store/apps/details?id=ru.flintnet.ExcavatorMonitor

**Comment by zawawawa** [comment]
That makes perfect sense. I would imagine it was rather frustrating to keep track of undocumented changes to the API. We will also make sure to include breaking changes to the API in the Changelog. Thank you for your feedback!

**Comment by zawawawa** [comment]
I just added a version number and a Changelog to the API documentation: https://github.com/nicehash/excavator/tree/master/api
