### ISSUE TITLE
CUDA error DRIVER '715' in func 'run_single_stream' line 995

### ISSUE THREAD

**Issue by Miners007** [nicehash/excavator#59]
Hi,

Having some issues after I bought a new GPU.

Earlier I had 2 ASUS Geforce 1060 OC 3GB, running stable for weeks. Then I also bought a ASUS Geforce 1070 OC 8GB and started getting the error:
CUDA error DRIVER '715' in func 'run_single_stream' line 995
sometimes following error occours, at the same time. BUT not always:
CUDA error 'an illegal instruction was encountered' in fuc 'cuda_lyra2rev2::run' line 785 

Thought it could be afterburner OC, but set it to factory settings. Still the same. 
Upgraded Nicehash to v2.0.1.4, which installs excaviator v1.3.6a
Same issue. Miner gets error either just after startup or after 30 sec or so.
Checked GPU driver/bios....

Switched off one of the GPU's so I only runs 1x1060 and 1x1070, then it gets more stable and have not seen an error while running a couple of hours.

Started 2 Nicehash applications. first of the runs 1060 and 1070, other application runs the last 1060.
Then error occours randomly between 1min and x hour.

The 1060's has hyxin ram and the 1070 has Micron... -Yeah I'm so lucky!

Any good solutions to fix this?

**Comment by dropky** [comment]
Please take a look at #108 and let me know if anything mentioned there solves your problem (different version of the drivers, check your risers/connectors/cables, if everything is connected ok, check if your PSU is powerful enough).
