### ISSUE TITLE
Web root in config & command line

### ISSUE THREAD

**Issue by robmoggach** [nicehash/excavator#60]
I haven't found documentation on where the `web` folder is expected to live. Ideally this would be configurable to point to a user directory Eg. `/home/mine/web/excavator` either via command line flag `-wrd ---web-root-dir` or in the config file.

**Comment by robmoggach** [comment]
**label as feature request**

**Comment by lexkanev** [comment]
robmoggach, have you find solution of web folder placement?

**Comment by dropky** [comment]
@lexkanev web folder has to be in the same folder you run the binary from.

**Comment by lexkanev** [comment]
@dropky so, my binary is in /opt/excavator/bin/ and I copied there the web folder (with index.html in it), ran in bash "excavator -wp 8080 -wi 192.168.1.1 -c default.json", go to "http://192.168.1.1:8080/" and get "404 Not Found".
But when I do json request to http api I can get data properly.
What is my mistake?

**Comment by dropky** [comment]
Are you sure you're running excavator from /opt/excavator/bin directory? 

Like this: 
cd /opt/excavator/bin; excavator -wp 8080 -wi 192.168.1.1 -c default.json

**Comment by lexkanev** [comment]
@dropky thnx! Now it's working properly! Before this I used to start commands: "excavator ...." and "/opt/excavator/bin/excavator -wp ..." but not doing "cd " to the folder.
Thank you very much!

**Comment by dropky** [comment]
https://github.com/nicehash/excavator/releases/tag/v1.3.9a

Added '-wl' command line parameter to specify path to index.html.
