### ISSUE TITLE
json file for LyraREv2

### ISSUE THREAD

**Issue by gerardogarciag1** [nicehash/excavator#61]
I'm currently running excavator on a Ubuntu computer with 16.04
I would like to use the LyraREv2 algorithm with my computer in Ubuntu.

Could you please share it?

**Comment by Kayfolom** [comment]
GTX 1080Ti on nicehash lyra2rev2:
`[
	{"time":1,"commands":[
		{"id":1,"method":"algorithm.add","params":["lyra2rev2","lyra2rev2.eu.nicehash.com:3347","***************************.node10"]}
	]},
	{"time":2,"commands":[
		{"id":1,"method":"worker.add","params":["0","0"]},
		{"id":1,"method":"worker.add","params":["0","0"]}
	]},
	{"time":5,"commands":[
		{"id":1,"method":"device.set.tdp","params":					["0","100"]},
		{"id":1,"method":"device.set.core_delta","params":	["0","220"]},
		{"id":1,"method":"device.set.memory_delta","params":["0","-1000"]}
	]},
{"time":10,"commands":[
		{"id":1,"method":"worker.reset","params":["0"]},
		{"id":1,"method":"worker.reset","params":["1"]}
	]},
	{"time":15,"loop":20,"commands":[
		{"id":1,"method":"worker.print.speed","params":["0"]},
		{"id":1,"method":"worker.print.speed","params":["1"]},
		{"id":1,"method":"algorithm.print.speeds","params":["0"]}
	]},
	{"event":"on_quit","commands":[
		{"id":1,"method":"device.set.tdp","params":					["0","100"]},
		{"id":1,"method":"device.set.core_delta","params":	["0","0"]},
		{"id":1,"method":"device.set.memory_delta","params":["0","0"]}
	]}
]`

**Comment by gerardogarciag1** [comment]
what if I have 2 or 3 GTX 1080 Ti??

**Comment by dropky** [comment]
You have to add separate worker for each device. 
```

[
	{"time":0,"commands":[
		{"id":1,"method":"algorithm.add","params":["lyra2rev2","lyra2rev2.eu.nicehash.com:3347","***"]}
	]},
	{"time":3,"commands":[
		{"id":1,"method":"worker.add","params":["0","0"]},
		{"id":1,"method":"worker.add","params":["0","1"]},
		{"id":1,"method":"worker.add","params":["0","2"]}
	]},
	{"time":10,"commands":[
		{"id":1,"method":"worker.reset","params":["0"]},
		{"id":1,"method":"worker.reset","params":["1"]},
		{"id":1,"method":"worker.reset","params":["2"]}
	]},
	{"time":10,"loop":10,"commands":[
		{"id":1,"method":"algorithm.print.speeds","params":["0"]}
	]}
]

```
Please take a look into api documentation: https://github.com/nicehash/excavator/tree/master/api#worker-add
