### ISSUE TITLE
API method Info description

### ISSUE THREAD

**Issue by Kayfolom** [nicehash/excavator#66]
In the latest versions, new information was added to the Info method.
https://github.com/nicehash/excavator/tree/master/api#info :
`{  
   "version":"1.2.1a",
   "build_platform":"Windows",
   "build_time":"2017-05-18 13:39:44",
   "build_number":6,
   "uptime":21594,
   "id":1,
   "error":null
}`

The actual method call looks like this:
`{
	"version": "1.3.6a_nvidia",
	"build_platform": "Windows",
	"build_time": "2017-11-03 12:26:39",
	"build_number": 99,
	"uptime": 81533968,
	"cpu_load": 15.625,
	"cpu_usage": 3.125,
	"ram_load": 54.0,
	"ram_usage": 90.03515625,
	"id": 1,
	"error": null
}`
Can I get a description of the new fields? In which units of measurement are shown cpu_* and ram_*?
Thank you in advance for your response!

**Comment by dropky** [comment]
We will update docs shortly. Thanks for pointing it out. 

cpu_load: %
cpu_usage: %
ram_load: %
ram_usage: MB
All four variables are double.

**Comment by Kayfolom** [comment]
Thank you!
