### ISSUE TITLE
Change algorithms

### ISSUE THREAD

**Issue by MichaelMiner** [nicehash/excavator#68]
Please, tell me how to properly change algorithms HTTP API?

**Comment by MichaelMiner** [comment]
when I remove old algorithm and set new, workers speed is zero
and no errors with replay messages.

**Comment by dropky** [comment]
Could you post log file with -f 0 ? Thank you!

**Comment by MichaelMiner** [comment]
Hi

See attach

Best regards, Michael

**Comment by dropky** [comment]
I can't see any attachment. Please attach log here (on GitHub) please.

**Comment by MichaelMiner** [comment]
Ok

**Comment by MichaelMiner** [comment]
Attach
[excv.log](https://github.com/nicehash/excavator/files/1485473/excv.log)

**Comment by dropky** [comment]
I see that you're calling workers.free, algorithms.clear, algorithm.add and workers.add at the same time (within one second). What happens is that the algorithm is assigned to the worker before it's done with initialisation. You can see the response "No such algorithm".
```

[[2017-11-19 13:45:05.613311] [thread=0x00001bd4] [debug]]

	core | Command method: workers.add


[[2017-11-19 13:45:05.613311] [thread=0x00001bd4] [trace]]

	http | Sending: {"id":1,"status":[{"error":"No such algorithm."}]}

```
Please make one or two second delay between algorithm.add and worker.add methods. That should solve your problem. If the issue still happens make another delay between algorithm.clear and algorithm.add. 

Let me know how it goes.

**Comment by MichaelMiner** [comment]
Thank's

Best regards, Michael
