### ISSUE TITLE
Ubuntu 16.04.3 LTS - excavator-run

### ISSUE THREAD

**Issue by gerardogarciag1** [nicehash/excavator#69]
Great addition 

When executing 
excavator-run -u <Bitcoing wallet> -a <algorithm>

It goes to the .eu. pools
I'm in the US

Is there any way to specify that on the parameters

In addition, 
The _man_ command does not work for man **excavator-run** 

Is there any way to include a feature like the UI that will switch algorithns based on the most profitable.

**Comment by zawawawa** [comment]
Thank you for the report. I will fix these problems in the next version. Real-time algorithm switching is probably beyond the scope of this script, but I will consider it. Also, we are working on the Linux version of NHMv2. Just to let you know.

**Comment by kgiedrius** [comment]
you can open excavator-run  with vim or nano and change whatever you want
excavator-run is just a wrapper for excavator.
