### ISSUE TITLE
Nowhere is a list of supported algorithms

### ISSUE THREAD

**Issue by Kayfolom** [nicehash/excavator#7]
Nowhere is a list of supported algorithms:
https://github.com/nicehash/excavator/tree/master/api#info - Nothing
https://github.com/nicehash/excavator - Nothing
https://github.com/nicehash/excavator/blob/master/excavator-man-API.txt - Nothing
https://bitcointalk.org/index.php?topic=1777827.0 - Nothing
README.md - Nothing

I was trying to remember if the Excavator supports the Ethereum, but was surprised to find out that the information was nowhere to get...

**Comment by nicehashdev** [comment]
It depends whether you are looking this information for NVIDIA: https://github.com/nicehash/excavator/tree/master/nvidia

or AMD: https://github.com/nicehash/excavator/tree/master/amd
