### ISSUE TITLE
No change algoritms

### ISSUE THREAD

**Issue by MichaelMiner** [nicehash/excavator#70]
[excv.log](https://github.com/nicehash/excavator/files/1485648/excv.log)
Hi,
No evcavator change algorithms (see attach)
[[2017-11-19 17:55:58.407281] [thread=0x000012e0] [trace]]

	http | Sending: {"algorithms":[{"algorithm_id":1,"name":"equihash","pools":[{"connected":true,"got_job":true,"details":{"total_shares":0,"total_accepted":0,"total_rejected":0,"last_efficiency":1.0},"address":"equihash.eu.nicehash.com:3357","login":"39tdmcz9AKYBPCUvpvkoGEVbbrM8p37ANj.test:x"},{"connected":false,"got_job":false,"details":{},"address":"benchmark","login":"benchmark"}],"workers":[]}],"id":1,"error":null}

[[2017-11-19 17:55:58.408281] [thread=0x000012e0] [trace]]

	http | Requested: /api?command={"id":1,"method":"workers.add","params":["alg-0","0"]}

[[2017-11-19 17:55:58.408281] [thread=0x000012e0] [trace]]

	http | JSON command: {"id":1,"method":"workers.add","params":["alg-0","0"]}

[[2017-11-19 17:55:58.408281] [thread=0x000012e0] [debug]]

	core | Command method: workers.add

[[2017-11-19 17:55:58.408281] [thread=0x000012e0] [trace]]

	http | Sending: {"id":1,"status":[{"error":"No such algorithm."}]}

**Comment by dropky** [comment]
As I said before please add a one second delay between algorithm.add and worker.add methods. Looking at your logs, both are executed at 17:55:58.**, still within the same second. 

```
[[2017-11-19 17:55:58.099263] [thread=0x000012e0] [trace]]

	http | JSON command: {"id":1,"method":"algorithm.add","params":["equihash","equihash.eu.nicehash.com:3357","39tdmcz9AKYBPCUvpvkoGEVbbrM8p37ANj.test:x"]}


[[2017-11-19 17:55:58.099263] [thread=0x000012e0] [debug]]

	core | Command method: algorithm.add

[[2017-11-19 17:55:58.408281] [thread=0x000012e0] [trace]]

	http | Requested: /api?command={"id":1,"method":"workers.add","params":["alg-0","0"]}


[[2017-11-19 17:55:58.408281] [thread=0x000012e0] [trace]]

	http | JSON command: {"id":1,"method":"workers.add","params":["alg-0","0"]}


[[2017-11-19 17:55:58.408281] [thread=0x000012e0] [debug]]

	core | Command method: workers.add


[[2017-11-19 17:55:58.408281] [thread=0x000012e0] [trace]]

	http | Sending: {"id":1,"status":[{"error":"No such algorithm."}]}
```

**Comment by MichaelMiner** [comment]
Ok, I'm try set delay

**Comment by MichaelMiner** [comment]
Add delay
//--- Open new algorithm
        s:= 'http://127.0.0.1:38080/api?command={"id":1,"method":"algorithm.add","params":["' +
          MData.BestAlgo + '","' + MData.BestAlgo + '.' + MData.Location +
          '.nicehash.com:' + Port + '","' + MData.Wallet + '.' + MData.Worker + ':x"]}';
        res:= IdHTTP1.Get(s);
        if(Pos('error":null', res) > 0) then
        begin
          res:= IdHTTP1.Get('http://127.0.0.1:38080/api?command={"id":1,"method":"algorithm.list","params":[]}');
          if(Pos('error":null', res) > 0) then
          begin
//--- Wait untill algorithm connected
            isConnected:= false;
            while (not isConnected) do
            begin
              Sleep(300);
              res:= IdHTTP1.Get('http://127.0.0.1:38080/api?command={"id":1,"method":"algorithm.list","params":[]}');
              if(Pos('connected":true', res) > 0) then isConnected:= true;
            end;
//--- workers add
            Sleep(1000); ////Now add dalay!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
            s:= 'http://127.0.0.1:38080/api?command={"id":1,"method":"workers.add","params":[';
            param:= '';
            for i := 0 to MData.GPUCount - 1 do
              param:= param + '"alg-0","' + IntToStr(i) + '",';
            if(param[length(param)] = ',') then Delete(param, length(param), 1);
            s:= s + param + ']}';
            res:= IdHTTP1.Get(s);
          end;
        end;

Problem exists... No add workers
[excv.log](https://github.com/nicehash/excavator/files/1485725/excv.log)

**Comment by Kayfolom** [comment]
//--- Open new algorithm
s:= 'http://127.0.0.1:38080/api?command={"id":1,"method":"algorithm.add","params":["' +
MData.BestAlgo + '","' + MData.BestAlgo + '.' + MData.Location +
'.nicehash.com:' + Port + '","' + MData.Wallet + '.' + MData.Worker + ':x"]}';
res:= IdHTTP1.Get(s);
if(Pos('error":null', res) > 0) then
begin
// Exctract AlgorithmID from res //(Kayfolom)
//{
//   "algorithm_id":0,
//   "id":1,
//   "error":null
//}
AlgorithmID:=0; // or 1, or 2, or .....
//--- workers add
Sleep(1000); ////Now add dalay!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
s:= 'http://127.0.0.1:38080/api?command={"id":1,"method":"workers.add","params":[';
param:= '';
for i := 0 to MData.GPUCount - 1 do
begin
param:= param + '"alg-' + AlgorithmID + ""  ,"' + IntToStr(i) + '",'; // insert AlgoID //(Kayfolom)
//if(param[length(param)] = ',') then Delete(param, length(param), 1); //(Kayfolom)
param:= TrimRight(param, ','); // if use delphi //(Kayfolom)
s:= s + param + ']}';
res:= IdHTTP1.Get(s);
Sleep(100);
end;
end;
end;
---------------------------------------------------------------------------------------------
As it is so roughly

**Comment by MichaelMiner** [comment]
Слыш, умник, своё мнение можешь сасунуть себе в ж...

**Comment by Kayfolom** [comment]
I tried to help you, but you respond with insults. Cope yourself ...
