### ISSUE TITLE
equihash

### ISSUE THREAD

**Issue by MichaelMiner** [nicehash/excavator#75]
Readme NVidia
If no parameters are provided, device specific defaults are used (M=1). We suggest using two workers per device when running equihash with mode 0*, otherwise use one worker per device.
* To manage intensity of this algorithm, we suggest you to run only one worker to reach low intensity and multiple (suggest 2) workers per device to reach optimal speed.
WARNING: Mode 1 is currently unstable on some Windows systems.

How set command line (Please, example for 2 device mode M=2)

**Comment by dropky** [comment]
Here is the config file for two GPUs, running one worker per device with mode 2:

```
[
	{"time":0,"commands":[
		{"id":1,"method":"algorithm.add","params":["equihash","equihash.usa.nicehash.com:3357","34HKWdzLxWBduUfJE9JxaFhoXnfC6gmePG.testrig"]}
	]},
	{"time":3,"commands":[
		{"id":1,"method":"worker.add","params":["0","0","M=2"]},
		{"id":1,"method":"worker.add","params":["0","1","M=2"]}
	]},
	{"time":10,"loop":10,"commands":[
		{"id":1,"method":"worker.print.speed","params":["0"]},
		{"id":1,"method":"worker.print.speed","params":["1"]},
		{"id":1,"method":"algorithm.print.speeds","params":["0"]}
	]}
]

```

Brief explanation: 

{"id":1,"method":"worker.add","params":["0","0","M=2"]} -> link algorithm 0 (equihash) to worker on device 0, run with M=2
{"id":1,"method":"worker.add","params":["0","1","M=2"]} -> link algorithm 0 to worker on device 1, run with mode M=2

To add two workers per device just add another worker.add method:
```
...
{"time":3,"commands":[
     {"id":1,"method":"worker.add","params":["0","0","M=2"]},
     {"id":1,"method":"worker.add","params":["0","0","M=2"]},
     {"id":1,"method":"worker.add","params":["0","1","M=2"]},
     {"id":1,"method":"worker.add","params":["0","1","M=2"]}
]},
...
```
Please take a look at our api documentation as well:
https://github.com/nicehash/excavator/tree/master/api#worker-add
