### ISSUE TITLE
Cryptonight speed down on GTX 1070 & 1060 3Gb on v1.3.7a

### ISSUE THREAD

**Issue by Quake4** [nicehash/excavator#76]
Cryptonight's bug fixes & improvements move speed down.

1070:
excavator-133a ~ 575  H/s
excavator-137a ~ 538  H/s

1060 3G:
excavator-133a ~ 325  H/s
excavator-137a ~ 295  H/s

And please add tuning for 1060 3G to this algo.

**Comment by dropky** [comment]
We had to lower the intensity of the Cryptonight for a bit, the version in 1.3.3a was very intense, causing screen freezes on primary GPUs. We're working on Cryptonight optimizations as we speak.
