### ISSUE TITLE
GTX 580 problem

### ISSUE THREAD

**Issue by duncanmcl** [nicehash/excavator#79]
I have a GTX 580 card (supporting shader model 5.0) using geforce 388.31 driver on windows 10 64 bit. Excavator is giving the following error and exiting. 

[13:27:48][0x00001474][error] core | No compatible devices found!

**Comment by dropky** [comment]
Sorry, your card is not supported (Fermi architecture). 

We're supporting only cards with Maxwell and Pascal architecture (SM 5.x+).
