### ISSUE TITLE
Hangs on 4+ Nvidia 1080 TI GPUs

### ISSUE THREAD

**Issue by computeronix** [nicehash/excavator#8]
When utilizing excavator it starts up and runs for a few minutes then hangs and eventually it continues and then it hangs again

Only when 4+ Nvidia GPUs. (CPU / Memory are all medium or low usage)

To rule out HW: I switched over to ClaymoreDualMiner and its handling all 4 GPUs fine.

**Comment by nicehashdev** [comment]
What exactly are you running? And how? Command file?

**Comment by computeronix** [comment]
Utilizing the NiceHash GUI which is selecting excavator and running it with the command lines built into that program
\bin\excavator\excavator.exe

**Comment by computeronix** [comment]
When I start it, it runs and then has lots of rejects and eventually it hangs.  Then after it unhangs has lots of accepts and runs for a while and then eventually it hangs again and just keeps repeating.

Can pull the logs as needed too

**Comment by nicehashdev** [comment]
NHM1 is using old Excavator and not this new version, so this will not help us. You may try running latest Excavator you can download from release page here, but it is a bit harder to configure everything.
