### ISSUE TITLE
When Dual=1 gets stuck on "core | Initialized!" -- from debian package for 16.04

### ISSUE THREAD

**Issue by rootexpression** [nicehash/excavator#83]
Any time I try to run dual aglos, with any of the combinations I have tried, excavator gets stuck, and never moves on.  I have left it sitting for at least 20+ minutes without change.

```

 Build time: 2017-10-21 04:19:17
Build number: 20
[22:24:43][0x00007fd49dac8740][info] Log started
[22:24:43][0x00007fd49dac8740][info] core | Found CUDA device: [tried with many nVidia 10 series cards]
[22:24:43][0x00007fd49dac8740][info] api | Listening on 127.0.0.1:3456
[22:24:43][0x00007fd49dac8740][info] http | Listening on 127.0.0.1:38080
[22:24:43][0x00007fd49dac8740][info] core | Initialized!
```

It just sits there.

Example from excavator-run file:
```
alg="lyra2rev2"
alg1="daggerhashimoto"
gpu="0"
dual=1
workers=1
```

Turn off dual mining (set to 0 rather than 1), everything works. 

Running Debian package for 16.04 -- have not tried to replicate in Windows.

**Comment by rootexpression** [comment]
Forgot to add, this is the latest version, v1.3.8a

**Comment by dropky** [comment]
```
alg="lyra2rev2"
alg1="daggerhashimoto"
```

From the example that you posted I can see that you're trying to run dual with lyra2rev2, which is not supported. 

Please check here which algorithms are supported in Excavator:
https://github.com/nicehash/excavator/tree/master/nvidia

Dual mining should work with daggerhashimoto-decred, daggerhashimoto-pascal and daggerhashimoto-sia.
