### ISSUE TITLE
Continue job

### ISSUE THREAD

**Issue by MichaelMiner** [nicehash/excavator#87]
Hi!
You will continue to work on Excavator, despite the fact that NiceHash does not work?

**Comment by Kayfolom** [comment]
Do not throw the project! Publish an address for donations, we will support you!

**Comment by dropky** [comment]
Thanks for the support! We'll continue to work on Excavator, it may take a while though, before we fully re-establish our development process and make another release.

**Comment by MichaelMiner** [comment]
Thank you! Excavator the Best miner! Great job!
