### ISSUE TITLE
Any plans to digitally sign phymem.sys?

### ISSUE THREAD

**Issue by ChriscomIT** [nicehash/excavator#9]
As topic above says. If yes any estimated time frame?

**Comment by ChriscomIT** [comment]
Learned that it's only for needed for AMD GPUs so it's not a problem for me right now. There also seem to be no attempts so sign it officially whatsover from any party.

**Comment by zawawawa** [comment]
Actually, we do plan to submit it to Microsoft for signing. Also, hardware acceleration may be extended to NVIDIA GPU's in the future.

**Comment by ChriscomIT** [comment]
Wow, thanks for this great response. That sounds extremely good! Also, the second point you mentioned about extending hw acceleration for Nvidia GPU's sounds very promising. At the moment EWBF miner is slightly faster as excavator and therefore it's actually my main solution. Would be great if the performance of both would be on par or maybe excavator even gets a bit faster if possible. 
Especially when looking forward to the NiceHash miner v2 which implements excavator as its the main miner for all excavator supported algorithms. Looking forward to it and big thanks for the much-appreciated answer!

**Comment by ChriscomIT** [comment]
BTW would be great if you could try to completely stop the injection/installation attempts of phymem.sys from excavator if a NVIDIA GPU was detected prior and no AMD GPUs are detected.

Should the hw acceleration for NVIDIA GPUs based on phymem.sys as well? If yes then forget this suggestion as it does not make sense then.

**Comment by zawawawa** [comment]
Thank you for your suggestion. We would use phymem.sys for NVIDIA, but it should be turned off for now.
