### ISSUE TITLE
Add algorithm nist5

### ISSUE THREAD

**Issue by bompus** [nicehash/excavator#91]
Would you be able to add nist5 as an algorithm? Amazingly, I can run excavator on my primary desktop without any OS lag, with equihash at least, so allowing it to mine other algorithms would be a good addition.

Thanks!

**Comment by dropky** [comment]
I added nist5 to our backlog. But I can't promise anything at this time. I'll keep you updated.

**Comment by dropky** [comment]
Nist5 will be included in the next version.
