### ISSUE TITLE
Daggerhashimoto merged mining Decred Invalid Job provided by Stratum Server

### ISSUE THREAD

**Issue by ax-webwarren** [nicehash/excavator#92]
hi Excavator,

Daggerhashimoto merged mining decred returns invalid Job provided by Stratum Server.
But using only daggerhashimoto doesn't cause any issues.
And in the web status it only flag the decred that has issues.

Thanks

**Comment by Enterprize-1701** [comment]
I have the same issue. I think the stratum server does't support this miner.
We have to find some Decred pools wich support mining on the latest stratum protocol.

**Comment by dropky** [comment]
Like @Enterprize-1701 said, some pools do not honour stratum protocols.

**Comment by dropky** [comment]
You could run Excavator with full file logging, past log file here and we will know for sure if that's the problem.
