### ISSUE TITLE
How do I get excavator to mine autoswitch between lyra2rev and equihash?

### ISSUE THREAD

**Issue by winnal** [nicehash/excavator#94]
Using the command .json file?

**Comment by aaronsace** [comment]
MultiPoolMiner does that.

**Comment by winnal** [comment]
Oh, but I need it to do it without restart excavator, is that possible?

**Comment by aaronsace** [comment]
Yes but I've not implemented it yet. It requires API access.

**Comment by dropky** [comment]
You can't perform auto switching using the command .json file. You could write your own script to do that or use third party solution (like the one mentioned by @aaronsace ).
