### ISSUE TITLE
Problem with lyra2rev2 and miningpoolhub.com

### ISSUE THREAD

**Issue by jvictorfc** [nicehash/excavator#95]
Is there a known issue with excavator working in this pool:miningpoolhub.com? everything is set allright but it doesnt work, I am trying with lyra2rev2 algo, ports, wallet, all info are double checked. With suprnova(vertcoin) it worked great, I really need that extra hash excavator can give me with this algo.

**Comment by MichaelMiner** [comment]
What you wtite in .json file?

**Comment by miningpoolhub** [comment]
nicehash blocked miningpoolhub
https://github.com/nicehash/excavator/issues/51

**Comment by aaronsace** [comment]
@jvictorfc MultiPoolMiner works with together with both Excavator and MiningPoolHub. Just drop the Excavator files in folder '.\Bin\Excavator'. 

https://github.com/aaronsace/MultiPoolMiner/archive/master.zip

**Comment by jvictorfc** [comment]
Thank you @aaronsace and @miningpoolhub  , I will try it.

**Comment by dropky** [comment]
I'm closing this since the solution has been found.
